# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .air_quality_response_current import AirQualityResponseCurrent
from .air_quality_response_forecast_value import AirQualityResponseForecastValue
from .air_quality_response_location import AirQualityResponseLocation


class AirQualityResponse(UniversalBaseModel):
    location: typing.Optional[AirQualityResponseLocation] = pydantic.Field(default=None)
    """
    Location information
    """

    current: typing.Optional[AirQualityResponseCurrent] = pydantic.Field(default=None)
    """
    Current air quality data
    """

    forecast: typing.Optional[typing.Dict[str, AirQualityResponseForecastValue]] = pydantic.Field(default=None)
    """
    Air quality forecast data object
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
