# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata


class AirQualityResponseForecastValueHourlyItem(UniversalBaseModel):
    timestamp: typing.Optional[dt.datetime] = pydantic.Field(default=None)
    """
    ISO 8601 formatted timestamp
    """

    pm10: typing.Optional[float] = pydantic.Field(default=None)
    """
    Concentration of particulate matter ≤10 micrometers (μg/m³)
    """

    carbon_monoxide: typing.Optional[float] = pydantic.Field(default=None)
    """
    Concentration of carbon monoxide (μg/m³)
    """

    pm25: typing_extensions.Annotated[
        typing.Optional[float],
        FieldMetadata(alias="pm2_5"),
        pydantic.Field(alias="pm2_5", description="Concentration of particulate matter ≤2.5 micrometers (μg/m³)"),
    ] = None
    carbon_dioxide: typing.Optional[float] = pydantic.Field(default=None)
    """
    Concentration of carbon dioxide (ppm)
    """

    nitrogen_dioxide: typing.Optional[float] = pydantic.Field(default=None)
    """
    Concentration of nitrogen dioxide (μg/m³)
    """

    sulphur_dioxide: typing.Optional[float] = pydantic.Field(default=None)
    """
    Concentration of sulphur dioxide (μg/m³)
    """

    ozone: typing.Optional[float] = pydantic.Field(default=None)
    """
    Concentration of ozone (μg/m³)
    """

    dust: typing.Optional[float] = pydantic.Field(default=None)
    """
    Concentration of dust particles (μg/m³)
    """

    uv_index: typing.Optional[float] = pydantic.Field(default=None)
    """
    Ultraviolet radiation index
    """

    aerosol_optical_depth: typing.Optional[float] = pydantic.Field(default=None)
    """
    Aerosol optical depth
    """

    uv_index_clear_sky: typing.Optional[float] = pydantic.Field(default=None)
    """
    Ultraviolet radiation index under clear sky conditions
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
