# This file was auto-generated by Fern from our API Definition.

import typing

from .air_quality_response_location_city import AirQualityResponseLocationCity
from .air_quality_response_location_continent_code import AirQualityResponseLocationContinentCode
from .air_quality_response_location_zero import AirQualityResponseLocationZero

AirQualityResponseLocation = typing.Union[
    AirQualityResponseLocationZero, AirQualityResponseLocationContinentCode, AirQualityResponseLocationCity
]
