# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata


class AsnWhoisLookupResponseParsedWhoisResponseOrganization(UniversalBaseModel):
    handle: typing.Optional[str] = None
    name: typing.Optional[str] = None
    address: typing.Optional[typing.List[str]] = None
    street: typing.Optional[str] = None
    city: typing.Optional[str] = None
    state: typing.Optional[str] = None
    zip_code: typing.Optional[str] = None
    country: typing.Optional[typing.List[str]] = None
    address_country: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="addressCountry"), pydantic.Field(alias="addressCountry")
    ] = None
    date_created: typing.Optional[dt.date] = None
    date_updated: typing.Optional[dt.date] = None
    source: typing.Optional[str] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
