# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata


class AsnWhoisLookupResponseRouteObjectsItem(UniversalBaseModel):
    route: str
    origin: str
    origin_name: typing_extensions.Annotated[str, FieldMetadata(alias="originName"), pydantic.Field(alias="originName")]
    isp: str
    number_of_ips: typing_extensions.Annotated[
        int, FieldMetadata(alias="numberOfIps"), pydantic.Field(alias="numberOfIps")
    ]

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
