# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata


class AsnWhoisLookupResponseParsedWhoisResponseAutNumsItem(UniversalBaseModel):
    aut_num: str
    as_handle: str
    as_name: str
    tech_contacts: typing.List[str]
    abuse_contacts: typing.List[str]
    date_created: dt.date
    date_updated: dt.date
    source: str
    description: typing.Optional[str] = None
    country: typing.Optional[str] = None
    status: typing.Optional[typing.List[str]] = None
    member_of: typing.Optional[typing.List[str]] = None
    import_via: typing.Optional[typing.List[str]] = None
    import_: typing_extensions.Annotated[
        typing.Optional[typing.List[str]], FieldMetadata(alias="import"), pydantic.Field(alias="import")
    ] = None
    mp_import: typing.Optional[typing.List[str]] = None
    export_via: typing.Optional[typing.List[str]] = None
    export: typing.Optional[typing.List[str]] = None
    mp_export: typing.Optional[typing.List[str]] = None
    default: typing.Optional[typing.List[str]] = None
    mp_default: typing.Optional[typing.List[str]] = None
    organization: typing.Optional[str] = None
    sponsoring_organization: typing.Optional[str] = None
    admin_contacts: typing.Optional[typing.List[str]] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
