# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .asn_whois_lookup_response_contacts import AsnWhoisLookupResponseContacts
from .asn_whois_lookup_response_downstreams_item import AsnWhoisLookupResponseDownstreamsItem
from .asn_whois_lookup_response_parsed_whois_response import AsnWhoisLookupResponseParsedWhoisResponse
from .asn_whois_lookup_response_peers_item import AsnWhoisLookupResponsePeersItem
from .asn_whois_lookup_response_route_objects_item import AsnWhoisLookupResponseRouteObjectsItem
from .asn_whois_lookup_response_upstreams_item import AsnWhoisLookupResponseUpstreamsItem


class AsnWhoisLookupResponse(UniversalBaseModel):
    as_number: typing_extensions.Annotated[str, FieldMetadata(alias="asNumber"), pydantic.Field(alias="asNumber")]
    as_name: typing_extensions.Annotated[str, FieldMetadata(alias="asName"), pydantic.Field(alias="asName")]
    org_name: typing_extensions.Annotated[str, FieldMetadata(alias="orgName"), pydantic.Field(alias="orgName")]
    description: typing.Optional[str] = None
    org_handle: typing_extensions.Annotated[str, FieldMetadata(alias="orgHandle"), pydantic.Field(alias="orgHandle")]
    country: str
    domain: typing.Optional[str] = None
    website: typing.Optional[str] = None
    allocation_status: typing_extensions.Annotated[
        str, FieldMetadata(alias="allocationStatus"), pydantic.Field(alias="allocationStatus")
    ]
    num_of_i_pv4routes: typing_extensions.Annotated[
        str, FieldMetadata(alias="numOfIPv4Routes"), pydantic.Field(alias="numOfIPv4Routes")
    ]
    num_of_i_pv6routes: typing_extensions.Annotated[
        str, FieldMetadata(alias="numOfIPv6Routes"), pydantic.Field(alias="numOfIPv6Routes")
    ]
    whois_host: typing_extensions.Annotated[str, FieldMetadata(alias="whoisHost"), pydantic.Field(alias="whoisHost")]
    date_allocated: typing_extensions.Annotated[
        typing.Optional[dt.date], FieldMetadata(alias="dateAllocated"), pydantic.Field(alias="dateAllocated")
    ] = None
    type: str
    route_objects: typing_extensions.Annotated[
        typing.List[AsnWhoisLookupResponseRouteObjectsItem],
        FieldMetadata(alias="routeObjects"),
        pydantic.Field(alias="routeObjects"),
    ]
    whois_response: typing_extensions.Annotated[
        str, FieldMetadata(alias="whoisResponse"), pydantic.Field(alias="whoisResponse")
    ]
    downstreams: typing.List[AsnWhoisLookupResponseDownstreamsItem]
    parsed_whois_response: typing_extensions.Annotated[
        AsnWhoisLookupResponseParsedWhoisResponse,
        FieldMetadata(alias="parsedWhoisResponse"),
        pydantic.Field(alias="parsedWhoisResponse"),
    ]
    upstreams: typing.List[AsnWhoisLookupResponseUpstreamsItem]
    peers: typing.List[AsnWhoisLookupResponsePeersItem]
    contacts: AsnWhoisLookupResponseContacts
    legacy_routes: typing_extensions.Annotated[
        typing.List[str], FieldMetadata(alias="legacyRoutes"), pydantic.Field(alias="legacyRoutes")
    ]
    whois_raw_response: typing.Optional[str] = None
    r_whois_raw_response: typing.Optional[str] = None
    query_time: typing.Optional[str] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
