# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class AstronomyLookupResponseLocation(UniversalBaseModel):
    location_string: typing.Optional[str] = pydantic.Field(default=None)
    """
    The complete geographical location (returned when looking up by the location parameter).
    """

    continent_code: typing.Optional[str] = None
    continent_name: typing.Optional[str] = None
    country_code2: typing.Optional[str] = None
    country_code3: typing.Optional[str] = None
    country_name: str
    country_name_official: typing.Optional[str] = None
    is_eu: typing.Optional[bool] = None
    state_prov: str
    state_code: typing.Optional[str] = None
    district: typing.Optional[str] = None
    city: str
    zipcode: typing.Optional[str] = None
    latitude: str
    longitude: str
    locality: str
    elevation: str

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
