# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class AstronomyLookupV2ResponseAstronomyMorning(UniversalBaseModel):
    """
    Morning astronomical data including twilight, blue hour, and golden hour times.
    """

    astronomical_twilight_begin: str = pydantic.Field()
    """
    The start time of astronomical twilight in the morning
    """

    astronomical_twilight_end: str = pydantic.Field()
    """
    The end time of astronomical twilight in the morning
    """

    nautical_twilight_begin: str = pydantic.Field()
    """
    The start time of nautical twilight in the morning
    """

    nautical_twilight_end: str = pydantic.Field()
    """
    The end time of nautical twilight in the morning
    """

    civil_twilight_begin: str = pydantic.Field()
    """
    The start time of civil twilight in the morning
    """

    civil_twilight_end: str = pydantic.Field()
    """
    The end time of civil twilight in the morning
    """

    blue_hour_begin: str = pydantic.Field()
    """
    The beginning of the blue hour in the morning
    """

    blue_hour_end: str = pydantic.Field()
    """
    The end of the blue hour in the morning
    """

    golden_hour_begin: str = pydantic.Field()
    """
    The beginning of the golden hour in the morning
    """

    golden_hour_end: str = pydantic.Field()
    """
    The end of the golden hour in the morning
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
