# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .astronomy_lookup_v2_response_astronomy_evening import AstronomyLookupV2ResponseAstronomyEvening
from .astronomy_lookup_v2_response_astronomy_morning import AstronomyLookupV2ResponseAstronomyMorning


class AstronomyLookupV2ResponseAstronomy(UniversalBaseModel):
    """
    Complete astronomical data for the specified location and date.
    """

    time_zone: typing.Optional[str] = pydantic.Field(default=None)
    """
    Appears (with the provided value) only when the user includes a time_zone in the query to specify which time to observe.
    """

    date: str = pydantic.Field()
    """
    The date astronomy data was calculated for. Defaults to today's date; reflects the date query parameter's value when that parameter is supplied.
    """

    current_time: str = pydantic.Field()
    """
    The current time
    """

    mid_night: str = pydantic.Field()
    """
    The time of midnight (solar-based)
    """

    night_end: str = pydantic.Field()
    """
    The time when night ends (start of astronomical twilight)
    """

    morning: AstronomyLookupV2ResponseAstronomyMorning = pydantic.Field()
    """
    Morning astronomical data including twilight, blue hour, and golden hour times.
    """

    sunrise: str = pydantic.Field()
    """
    The time of sunrise
    """

    sunset: str = pydantic.Field()
    """
    The time of sunset
    """

    evening: AstronomyLookupV2ResponseAstronomyEvening = pydantic.Field()
    """
    Evening astronomical data including golden hour, blue hour, and twilight times.
    """

    night_begin: str = pydantic.Field()
    """
    The time when night begins (end of astronomical twilight)
    """

    sun_status: str = pydantic.Field()
    """
    The current status of the sun (e.g., "rising", "setting", "-")
    """

    solar_noon: str = pydantic.Field()
    """
    The time when the sun reaches its highest point in the sky
    """

    day_length: str = pydantic.Field()
    """
    The total duration of daylight
    """

    sun_altitude: float = pydantic.Field()
    """
    The altitude angle of the sun above the horizon in degrees
    """

    sun_distance: float = pydantic.Field()
    """
    The distance from the Earth to the sun in kilometers
    """

    sun_azimuth: float = pydantic.Field()
    """
    The azimuth angle of the sun in degrees from true north
    """

    moon_phase: str = pydantic.Field()
    """
    The current phase of the moon (e.g., "WAXING_GIBBOUS")
    """

    moonrise: str = pydantic.Field()
    """
    The time of moonrise
    """

    moonset: str = pydantic.Field()
    """
    The time of moonset
    """

    moon_status: str = pydantic.Field()
    """
    The current status of the moon (e.g., "rising", "setting", "-")
    """

    moon_altitude: float = pydantic.Field()
    """
    The altitude angle of the moon above the horizon in degrees
    """

    moon_distance: float = pydantic.Field()
    """
    The distance from the Earth to the moon in kilometers
    """

    moon_azimuth: float = pydantic.Field()
    """
    The azimuth angle of the moon in degrees from true north
    """

    moon_parallactic_angle: float = pydantic.Field()
    """
    The parallactic angle of the moon in degrees
    """

    moon_illumination_percentage: str = pydantic.Field()
    """
    The percentage of the moon illuminated by sunlight. A negative value indicates the moon is in a waning phase.
    """

    moon_angle: float = pydantic.Field()
    """
    The geometric angle of the moon relative to the observer
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
