# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class AstronomyLookupV2ResponseLocation(UniversalBaseModel):
    location_string: typing.Optional[str] = None
    continent_code: typing.Optional[str] = None
    continent_name: typing.Optional[str] = None
    country_code2: typing.Optional[str] = None
    country_code3: typing.Optional[str] = None
    country_name: typing.Optional[str] = None
    country_name_official: typing.Optional[str] = None
    is_eu: typing.Optional[bool] = None
    state_prov: typing.Optional[str] = None
    state_code: typing.Optional[str] = None
    district: typing.Optional[str] = None
    city: typing.Optional[str] = None
    locality: typing.Optional[str] = None
    zipcode: typing.Optional[str] = None
    latitude: typing.Optional[str] = None
    longitude: typing.Optional[str] = None
    elevation: typing.Optional[str] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class AstronomyLookupV2ResponseAstronomyMorning(UniversalBaseModel):
    astronomical_twilight_begin: typing.Optional[str] = None
    astronomical_twilight_end: typing.Optional[str] = None
    nautical_twilight_begin: typing.Optional[str] = None
    nautical_twilight_end: typing.Optional[str] = None
    civil_twilight_begin: typing.Optional[str] = None
    civil_twilight_end: typing.Optional[str] = None
    blue_hour_begin: typing.Optional[str] = None
    blue_hour_end: typing.Optional[str] = None
    golden_hour_begin: typing.Optional[str] = None
    golden_hour_end: typing.Optional[str] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class AstronomyLookupV2ResponseAstronomyEvening(UniversalBaseModel):
    golden_hour_begin: typing.Optional[str] = None
    golden_hour_end: typing.Optional[str] = None
    blue_hour_begin: typing.Optional[str] = None
    blue_hour_end: typing.Optional[str] = None
    civil_twilight_begin: typing.Optional[str] = None
    civil_twilight_end: typing.Optional[str] = None
    nautical_twilight_begin: typing.Optional[str] = None
    nautical_twilight_end: typing.Optional[str] = None
    astronomical_twilight_begin: typing.Optional[str] = None
    astronomical_twilight_end: typing.Optional[str] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class AstronomyLookupV2ResponseAstronomy(UniversalBaseModel):
    time_zone: typing.Optional[str] = None
    date: typing.Optional[str] = None
    current_time: typing.Optional[str] = None
    mid_night: typing.Optional[str] = None
    night_end: typing.Optional[str] = None
    night_begin: typing.Optional[str] = None
    morning: typing.Optional[AstronomyLookupV2ResponseAstronomyMorning] = None
    sunrise: typing.Optional[str] = None
    sunset: typing.Optional[str] = None
    sun_status: typing.Optional[str] = None
    solar_noon: typing.Optional[str] = None
    day_length: typing.Optional[str] = None
    sun_altitude: typing.Optional[float] = None
    sun_distance: typing.Optional[float] = None
    sun_azimuth: typing.Optional[float] = None
    evening: typing.Optional[AstronomyLookupV2ResponseAstronomyEvening] = None
    moonrise: typing.Optional[str] = None
    moonset: typing.Optional[str] = None
    moon_status: typing.Optional[str] = None
    moon_altitude: typing.Optional[float] = None
    moon_distance: typing.Optional[float] = None
    moon_azimuth: typing.Optional[float] = None
    moon_parallactic_angle: typing.Optional[float] = None
    moon_phase: typing.Optional[str] = None
    moon_illumination_percentage: typing.Optional[str] = None
    moon_angle: typing.Optional[float] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class AstronomyLookupV2Response(UniversalBaseModel):
    ip: typing.Optional[str] = None
    location: typing.Optional[AstronomyLookupV2ResponseLocation] = None
    astronomy: typing.Optional[AstronomyLookupV2ResponseAstronomy] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
