# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .astronomy_lookup_response_astronomy_evening import AstronomyLookupResponseAstronomyEvening
from .astronomy_lookup_response_astronomy_morning import AstronomyLookupResponseAstronomyMorning


class AstronomyLookupResponseAstronomy(UniversalBaseModel):
    time_zone: str = pydantic.Field()
    """
    Time zone to receive all time-based data in your preferred local time.
    """

    date: str = pydantic.Field()
    """
    Date for astronomy data (YYYY-MM-DD)
    """

    current_time: str = pydantic.Field()
    """
    Current time (HH:mm:ss.SSS)
    """

    mid_night: str = pydantic.Field()
    """
    Midnight time (HH:mm)
    """

    night_end: str = pydantic.Field()
    """
    Time when night ends (HH:mm)
    """

    morning: AstronomyLookupResponseAstronomyMorning
    sunrise: str = pydantic.Field()
    """
    Sunrise time (HH:mm)
    """

    sunset: str = pydantic.Field()
    """
    Sunset time (HH:mm)
    """

    evening: AstronomyLookupResponseAstronomyEvening
    night_begin: str = pydantic.Field()
    """
    Time when night begins (HH:mm)
    """

    sun_status: str = pydantic.Field()
    """
    Current status of the sun
    """

    solar_noon: str = pydantic.Field()
    """
    Solar noon time (HH:mm)
    """

    day_length: str = pydantic.Field()
    """
    Length of the day (HH:mm)
    """

    sun_altitude: float = pydantic.Field()
    """
    Sun altitude angle
    """

    sun_distance: float = pydantic.Field()
    """
    Distance from Earth to Sun
    """

    sun_azimuth: float = pydantic.Field()
    """
    Sun azimuth angle
    """

    moon_phase: str = pydantic.Field()
    """
    Moon phase
    """

    moonrise: str = pydantic.Field()
    """
    Moonrise time (HH:mm)
    """

    moonset: str = pydantic.Field()
    """
    Moonset time (HH:mm)
    """

    moon_status: str = pydantic.Field()
    """
    Current status of the moon
    """

    moon_altitude: float = pydantic.Field()
    """
    Moon altitude angle
    """

    moon_distance: float = pydantic.Field()
    """
    Distance from Earth to Moon
    """

    moon_azimuth: float = pydantic.Field()
    """
    Moon azimuth angle
    """

    moon_parallactic_angle: float = pydantic.Field()
    """
    Moon parallactic angle
    """

    moon_illumination_percentage: str = pydantic.Field()
    """
    Moon illumination percentage
    """

    moon_angle: float = pydantic.Field()
    """
    Moon angle
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
