# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .astronomy_lookup_response_astronomy import AstronomyLookupResponseAstronomy
from .astronomy_lookup_response_location import AstronomyLookupResponseLocation


class AstronomyLookupResponse(UniversalBaseModel):
    ip: typing.Optional[str] = None
    location: typing.Optional[AstronomyLookupResponseLocation] = None
    astronomy: AstronomyLookupResponseAstronomy

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
