# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class AstronomyLookupResponseAstronomyMorning(UniversalBaseModel):
    astronomical_twilight_begin: str
    astronomical_twilight_end: str
    nautical_twilight_begin: str
    nautical_twilight_end: str
    civil_twilight_begin: str
    civil_twilight_end: str
    blue_hour_begin: str
    blue_hour_end: str
    golden_hour_begin: str
    golden_hour_end: str

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
