# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .astronomy_lookup_v2_response_astronomy import AstronomyLookupV2ResponseAstronomy
from .astronomy_lookup_v2_response_location import AstronomyLookupV2ResponseLocation


class AstronomyLookupV2Response(UniversalBaseModel):
    """
    Astronomy data response containing location information and astronomical data.
    """

    ip: typing.Optional[str] = pydantic.Field(default=None)
    """
    IPv4 or IPv6 address used for the geo-IP lookup. Present when the ip parameter is passed explicitly, or when no location, lat/long, or ip parameter is supplied at all (the API falls back to the requesting client's IP address). Absent when location or lat/long is used.
    """

    location: typing.Optional[AstronomyLookupV2ResponseLocation] = pydantic.Field(default=None)
    """
    Geographic location information for the astronomy calculation. The set of populated fields depends on which lookup mode the request used: (1) location param (geocode-by-address) returns location_string plus a basic field set (country_name, state_prov, city, locality, latitude, longitude, elevation); (2) lat + long params (geocode-by-coordinates) returns the same basic field set minus location_string, and locality may be an empty string when the coordinates don't resolve to a named sub-area; (3) ip param, or no location/lat/long/ip param at all (falls back to geo-IP lookup of the client's IP), returns the full geo-IP field set — continent_code, continent_name, country_code2, country_code3, country_name_official, is_eu, state_code, district, zipcode — in addition to the basic fields, but never location_string. elevation can be an empty string when elevation data is unavailable for the resolved location.
    """

    astronomy: AstronomyLookupV2ResponseAstronomy = pydantic.Field()
    """
    Complete astronomical data for the specified location and date.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
