# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class AstronomyLookupV2ResponseLocation(UniversalBaseModel):
    """
    Geographic location information for the astronomy calculation. The set of populated fields depends on which lookup mode the request used: (1) location param (geocode-by-address) returns location_string plus a basic field set (country_name, state_prov, city, locality, latitude, longitude, elevation); (2) lat + long params (geocode-by-coordinates) returns the same basic field set minus location_string, and locality may be an empty string when the coordinates don't resolve to a named sub-area; (3) ip param, or no location/lat/long/ip param at all (falls back to geo-IP lookup of the client's IP), returns the full geo-IP field set — continent_code, continent_name, country_code2, country_code3, country_name_official, is_eu, state_code, district, zipcode — in addition to the basic fields, but never location_string. elevation can be an empty string when elevation data is unavailable for the resolved location.
    """

    location_string: typing.Optional[str] = pydantic.Field(default=None)
    """
    The location query parameter echoed back as-is. Present only for geocode-by-address lookups (location param); absent for lat/long and ip-based lookups.
    """

    continent_code: typing.Optional[str] = pydantic.Field(default=None)
    """
    The two-letter code of the continent (e.g., "NA"). Geo-IP field only: present for ip param or default client-IP lookups; absent for location/lat/long geocode lookups.
    """

    continent_name: typing.Optional[str] = pydantic.Field(default=None)
    """
    The full name of the continent (e.g., "North America"). Geo-IP field only: present for ip param or default client-IP lookups; absent for location/lat/long geocode lookups.
    """

    country_code2: typing.Optional[str] = pydantic.Field(default=None)
    """
    The ISO 3166-1 alpha-2 two-letter country code (e.g., "US"). Geo-IP field only: present for ip param or default client-IP lookups; absent for location/lat/long geocode lookups.
    """

    country_code3: typing.Optional[str] = pydantic.Field(default=None)
    """
    The ISO 3166-1 alpha-3 three-letter country code (e.g., "USA"). Geo-IP field only: present for ip param or default client-IP lookups; absent for location/lat/long geocode lookups.
    """

    country_name: typing.Optional[str] = pydantic.Field(default=None)
    """
    The common name of the country (e.g., "United States"). Present in all lookup modes.
    """

    country_name_official: typing.Optional[str] = pydantic.Field(default=None)
    """
    The official full name of the country (e.g., "United States of America"). Geo-IP field only: present for ip param or default client-IP lookups; absent for location/lat/long geocode lookups.
    """

    is_eu: typing.Optional[bool] = pydantic.Field(default=None)
    """
    Whether the country belongs to the European Union. Geo-IP field only: present for ip param or default client-IP lookups; absent for location/lat/long geocode lookups.
    """

    state_prov: typing.Optional[str] = pydantic.Field(default=None)
    """
    Name of the state/province/region. Present in all lookup modes.
    """

    state_code: typing.Optional[str] = pydantic.Field(default=None)
    """
    Code of the state/province/region. Geo-IP field only: present for ip param or default client-IP lookups; absent for location/lat/long geocode lookups.
    """

    district: typing.Optional[str] = pydantic.Field(default=None)
    """
    Name of the district or county. Geo-IP field only: present for ip param or default client-IP lookups; absent for location/lat/long geocode lookups.
    """

    city: typing.Optional[str] = pydantic.Field(default=None)
    """
    Name of the city. Present in all lookup modes.
    """

    zipcode: typing.Optional[str] = pydantic.Field(default=None)
    """
    ZIP/Postal code of the place. Geo-IP field only: present for ip param or default client-IP lookups; absent for location/lat/long geocode lookups.
    """

    latitude: str = pydantic.Field()
    """
    The geographic latitude of the location. Present in all lookup modes.
    """

    longitude: str = pydantic.Field()
    """
    The geographic longitude of the location. Present in all lookup modes.
    """

    locality: typing.Optional[str] = pydantic.Field(default=None)
    """
    Smaller area, part or region of a city. Present in all lookup modes, but may be an empty string for lat/long or geo-IP lookups when no named sub-area resolves.
    """

    elevation: typing.Optional[str] = pydantic.Field(default=None)
    """
    The elevation of the geographical location, in meters. Present in all lookup modes, but may be an empty string when elevation data is unavailable for the resolved location.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
