# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class AstronomyLookupV2ResponseAstronomyEvening(UniversalBaseModel):
    """
    Evening astronomical data including golden hour, blue hour, and twilight times.
    """

    golden_hour_begin: str = pydantic.Field()
    """
    The beginning of the golden hour in the evening
    """

    golden_hour_end: str = pydantic.Field()
    """
    The end of the golden hour in the evening
    """

    blue_hour_begin: str = pydantic.Field()
    """
    The beginning of the blue hour in the evening
    """

    blue_hour_end: str = pydantic.Field()
    """
    The end of the blue hour in the evening
    """

    civil_twilight_begin: str = pydantic.Field()
    """
    The start of civil twilight in the evening
    """

    civil_twilight_end: str = pydantic.Field()
    """
    The end of civil twilight in the evening
    """

    nautical_twilight_begin: str = pydantic.Field()
    """
    The start of nautical twilight in the evening
    """

    nautical_twilight_end: str = pydantic.Field()
    """
    The end of nautical twilight in the evening
    """

    astronomical_twilight_begin: str = pydantic.Field()
    """
    The start of astronomical twilight in the evening
    """

    astronomical_twilight_end: str = pydantic.Field()
    """
    The end of astronomical twilight in the evening
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
