# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class AstronomyLookupResponseAstronomyMorning(UniversalBaseModel):
    astronomical_twilight_begin: typing.Optional[str] = None
    astronomical_twilight_end: typing.Optional[str] = None
    nautical_twilight_begin: typing.Optional[str] = None
    nautical_twilight_end: typing.Optional[str] = None
    civil_twilight_begin: typing.Optional[str] = None
    civil_twilight_end: typing.Optional[str] = None
    blue_hour_begin: typing.Optional[str] = None
    blue_hour_end: typing.Optional[str] = None
    golden_hour_begin: typing.Optional[str] = None
    golden_hour_end: typing.Optional[str] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
