# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .bulk_current_weather_response_bulk_item_current import BulkCurrentWeatherResponseBulkItemCurrent
from .bulk_current_weather_response_bulk_item_location import BulkCurrentWeatherResponseBulkItemLocation


class BulkCurrentWeatherResponseBulkItem(UniversalBaseModel):
    location: BulkCurrentWeatherResponseBulkItemLocation = pydantic.Field()
    """
    Location information
    """

    current: BulkCurrentWeatherResponseBulkItemCurrent = pydantic.Field()
    """
    Current weather data
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
