# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class BulkUserAgentLookupResponseItemEngine(UniversalBaseModel):
    name: str = pydantic.Field()
    """
    Layout engine name or the underlying core that converts the HTML into visual
    """

    type: str = pydantic.Field()
    """
    Layout engine type. Possible values:
    1. Browser
    2. Mobile App
    3. Hacker
    4. Robot
    5. Unknown
    """

    version: str = pydantic.Field()
    """
    Layout engine version
    """

    version_major: str = pydantic.Field()
    """
    Layout engine version major
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
