# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .bulk_geolocation_lookup_response_item_network_asn import BulkGeolocationLookupResponseItemNetworkAsn
from .bulk_geolocation_lookup_response_item_network_company import BulkGeolocationLookupResponseItemNetworkCompany


class BulkGeolocationLookupResponseItemNetwork(UniversalBaseModel):
    asn: typing.Optional[BulkGeolocationLookupResponseItemNetworkAsn] = None
    connection_type: typing.Optional[str] = pydantic.Field(default=None)
    """
    The type of the connection
    """

    company: typing.Optional[BulkGeolocationLookupResponseItemNetworkCompany] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
