# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class BulkGeolocationLookupV2ResponseItemAbuseUserAgentOperatingSystem(UniversalBaseModel):
    """
    Operating system details.
    """

    name: typing.Optional[str] = pydantic.Field(default=None)
    """
    Operating system name.
    """

    type: typing.Optional[str] = pydantic.Field(default=None)
    """
    OS category (Desktop, Mobile, Server).
    """

    version: typing.Optional[str] = pydantic.Field(default=None)
    """
    OS version string.
    """

    version_major: typing.Optional[str] = pydantic.Field(default=None)
    """
    Major OS version.
    """

    build: typing.Optional[str] = pydantic.Field(default=None)
    """
    OS build identifier.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
