# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class BulkUserAgentLookupResponseItemDevice(UniversalBaseModel):
    name: str = pydantic.Field()
    """
    Device name or the hardware that was used
    """

    type: str = pydantic.Field()
    """
    Device type or the hardware type. Possible values:
    1. Desktop
    2. Mobile
    3. Tablet
    4. Phone
    5. Watch
    6. Virtual Reality
    7. eReader
    8. Set-top box
    9. TV
    10. Game Console
    11. Handheld Game Console
    12. Voice
    13. Robot
    14. Robot Mobile
    15. Robot Imitator
    16. Hacker
    17. Anonymized
    18. Unknown
    """

    brand: str = pydantic.Field()
    """
    Device brand or the hardware brand name
    """

    cpu: str = pydantic.Field()
    """
    Device's CPU model or machine CPU
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
