# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .bulk_domain_dns_lookup_response_bulk_dns_info_item_dns_records_item_admin_dns_type import (
    BulkDomainDnsLookupResponseBulkDnsInfoItemDnsRecordsItemAdminDnsType,
)


class BulkDomainDnsLookupResponseBulkDnsInfoItemDnsRecordsItemAdmin(UniversalBaseModel):
    name: str
    type: int
    dns_type: typing_extensions.Annotated[
        BulkDomainDnsLookupResponseBulkDnsInfoItemDnsRecordsItemAdminDnsType,
        FieldMetadata(alias="dnsType"),
        pydantic.Field(alias="dnsType"),
    ]
    ttl: int
    raw_text: typing_extensions.Annotated[str, FieldMetadata(alias="rawText"), pydantic.Field(alias="rawText")]
    r_rset_type: typing_extensions.Annotated[int, FieldMetadata(alias="rRsetType"), pydantic.Field(alias="rRsetType")]
    admin: str
    host: str
    expire: int
    minimum: int
    refresh: int
    retry: int
    serial: int

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
