# This file was auto-generated by Fern from our API Definition.

import typing

BulkDomainWhoisLookupResponseBulkWhoisResponseItemDomainRegistered = typing.Union[
    typing.Literal["yes", "no", "restricted"], typing.Any
]
