# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .bulk_geolocation_lookup_response_item_user_agent_device import BulkGeolocationLookupResponseItemUserAgentDevice
from .bulk_geolocation_lookup_response_item_user_agent_engine import BulkGeolocationLookupResponseItemUserAgentEngine
from .bulk_geolocation_lookup_response_item_user_agent_operating_system import (
    BulkGeolocationLookupResponseItemUserAgentOperatingSystem,
)


class BulkGeolocationLookupResponseItemUserAgent(UniversalBaseModel):
    user_agent_string: typing.Optional[str] = None
    name: typing.Optional[str] = None
    type: typing.Optional[str] = None
    version: typing.Optional[str] = None
    version_major: typing.Optional[str] = None
    device: typing.Optional[BulkGeolocationLookupResponseItemUserAgentDevice] = None
    engine: typing.Optional[BulkGeolocationLookupResponseItemUserAgentEngine] = None
    operating_system: typing.Optional[BulkGeolocationLookupResponseItemUserAgentOperatingSystem] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
