# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .bulk_domain_whois_lookup_response_bulk_whois_response_item_administrative_contact import (
    BulkDomainWhoisLookupResponseBulkWhoisResponseItemAdministrativeContact,
)
from .bulk_domain_whois_lookup_response_bulk_whois_response_item_billing_contact import (
    BulkDomainWhoisLookupResponseBulkWhoisResponseItemBillingContact,
)
from .bulk_domain_whois_lookup_response_bulk_whois_response_item_domain_registered import (
    BulkDomainWhoisLookupResponseBulkWhoisResponseItemDomainRegistered,
)
from .bulk_domain_whois_lookup_response_bulk_whois_response_item_domain_registrar import (
    BulkDomainWhoisLookupResponseBulkWhoisResponseItemDomainRegistrar,
)
from .bulk_domain_whois_lookup_response_bulk_whois_response_item_registrant_contact import (
    BulkDomainWhoisLookupResponseBulkWhoisResponseItemRegistrantContact,
)
from .bulk_domain_whois_lookup_response_bulk_whois_response_item_registry_data import (
    BulkDomainWhoisLookupResponseBulkWhoisResponseItemRegistryData,
)
from .bulk_domain_whois_lookup_response_bulk_whois_response_item_reseller_contact import (
    BulkDomainWhoisLookupResponseBulkWhoisResponseItemResellerContact,
)
from .bulk_domain_whois_lookup_response_bulk_whois_response_item_technical_contact import (
    BulkDomainWhoisLookupResponseBulkWhoisResponseItemTechnicalContact,
)


class BulkDomainWhoisLookupResponseBulkWhoisResponseItem(UniversalBaseModel):
    status: typing.Optional[bool] = None
    domain_name: typing.Optional[str] = None
    query_time: typing.Optional[dt.datetime] = None
    whois_server: typing.Optional[str] = None
    domain_registered: typing.Optional[BulkDomainWhoisLookupResponseBulkWhoisResponseItemDomainRegistered] = None
    create_date: typing.Optional[dt.date] = None
    update_date: typing.Optional[dt.date] = None
    expiry_date: typing.Optional[dt.date] = None
    domain_registrar: typing.Optional[BulkDomainWhoisLookupResponseBulkWhoisResponseItemDomainRegistrar] = None
    reseller_contact: typing.Optional[BulkDomainWhoisLookupResponseBulkWhoisResponseItemResellerContact] = None
    registrant_contact: typing.Optional[BulkDomainWhoisLookupResponseBulkWhoisResponseItemRegistrantContact] = None
    administrative_contact: typing.Optional[BulkDomainWhoisLookupResponseBulkWhoisResponseItemAdministrativeContact] = (
        None
    )
    technical_contact: typing.Optional[BulkDomainWhoisLookupResponseBulkWhoisResponseItemTechnicalContact] = None
    billing_contact: typing.Optional[BulkDomainWhoisLookupResponseBulkWhoisResponseItemBillingContact] = None
    name_servers: typing.Optional[typing.List[str]] = None
    domain_status: typing.Optional[typing.List[str]] = None
    whois_raw_domain: typing.Optional[str] = None
    registry_data: typing.Optional[BulkDomainWhoisLookupResponseBulkWhoisResponseItemRegistryData] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
