# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class BulkEmailValidateRequestEmailDataItem(UniversalBaseModel):
    email: str = pydantic.Field()
    """
    Email address to validate
    """

    name: typing.Optional[str] = pydantic.Field(default=None)
    """
    Name associated with the email address
    """

    ip: typing.Optional[str] = pydantic.Field(default=None)
    """
    IP address associated with the email address
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
