# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .bulk_domain_dns_lookup_response_bulk_dns_info_item_dns_records_item import (
    BulkDomainDnsLookupResponseBulkDnsInfoItemDnsRecordsItem,
)
from .bulk_domain_dns_lookup_response_bulk_dns_info_item_dns_types import (
    BulkDomainDnsLookupResponseBulkDnsInfoItemDnsTypes,
)


class BulkDomainDnsLookupResponseBulkDnsInfoItem(UniversalBaseModel):
    status: bool = pydantic.Field()
    """
    Indicates whether the query was processed successfully.
    """

    query_time: typing_extensions.Annotated[
        dt.datetime,
        FieldMetadata(alias="queryTime"),
        pydantic.Field(alias="queryTime", description="Time at which the query was made (Format:YYYY-MM-DD HH:mm:ss)."),
    ]
    domain_name: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="domainName"),
        pydantic.Field(alias="domainName", description="Queried domain (present for domain lookups)."),
    ] = None
    domain_registered: typing_extensions.Annotated[
        typing.Optional[bool],
        FieldMetadata(alias="domainRegistered"),
        pydantic.Field(
            alias="domainRegistered",
            description="Indicates whether the domain is registered (present for domain lookups).",
        ),
    ] = None
    ip_address: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="ipAddress"),
        pydantic.Field(alias="ipAddress", description="IP address queried (present for IP lookups)."),
    ] = None
    dns_types: typing_extensions.Annotated[
        BulkDomainDnsLookupResponseBulkDnsInfoItemDnsTypes,
        FieldMetadata(alias="dnsTypes"),
        pydantic.Field(alias="dnsTypes"),
    ]
    dns_records: typing_extensions.Annotated[
        typing.List[BulkDomainDnsLookupResponseBulkDnsInfoItemDnsRecordsItem],
        FieldMetadata(alias="dnsRecords"),
        pydantic.Field(alias="dnsRecords", description="List of DNS records, each based on its type."),
    ]

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
