# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class BulkEmailValidateResponseEmailValidationResponsesItemAddressLocation(UniversalBaseModel):
    city: typing.Optional[str] = None
    district: typing.Optional[str] = None
    confidence: typing.Optional[str] = None
    zipcode: typing.Optional[str] = None
    state_prov: typing.Optional[str] = None
    country_name: typing.Optional[str] = None
    continent_name: typing.Optional[str] = None
    continent_code: typing.Optional[str] = None
    country_code2: typing.Optional[str] = None
    country_code3: typing.Optional[str] = None
    country_name_official: typing.Optional[str] = None
    accuracy_radius: typing.Optional[str] = None
    is_eu: typing.Optional[bool] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
