# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .bulk_geolocation_lookup_v2_response_item_abuse_user_agent_device import (
    BulkGeolocationLookupV2ResponseItemAbuseUserAgentDevice,
)
from .bulk_geolocation_lookup_v2_response_item_abuse_user_agent_engine import (
    BulkGeolocationLookupV2ResponseItemAbuseUserAgentEngine,
)
from .bulk_geolocation_lookup_v2_response_item_abuse_user_agent_operating_system import (
    BulkGeolocationLookupV2ResponseItemAbuseUserAgentOperatingSystem,
)


class BulkGeolocationLookupV2ResponseItemAbuseUserAgent(UniversalBaseModel):
    """
    Parsed User-Agent details from the request.
    """

    user_agent_string: typing.Optional[str] = pydantic.Field(default=None)
    """
    Raw User-Agent string used for parsing.
    """

    name: typing.Optional[str] = pydantic.Field(default=None)
    """
    Detected user agent product name.
    """

    type: typing.Optional[str] = pydantic.Field(default=None)
    """
    User agent category (e.g., Browser, Mobile App, Bot).
    """

    version: typing.Optional[str] = pydantic.Field(default=None)
    """
    Full product version string.
    """

    version_major: typing.Optional[str] = pydantic.Field(default=None)
    """
    Major version extracted from version.
    """

    device: typing.Optional[BulkGeolocationLookupV2ResponseItemAbuseUserAgentDevice] = pydantic.Field(default=None)
    """
    Device details.
    """

    engine: typing.Optional[BulkGeolocationLookupV2ResponseItemAbuseUserAgentEngine] = pydantic.Field(default=None)
    """
    Rendering engine details.
    """

    operating_system: typing.Optional[BulkGeolocationLookupV2ResponseItemAbuseUserAgentOperatingSystem] = (
        pydantic.Field(default=None)
    )
    """
    Operating system details.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
