# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class BulkVatRateByCountryResponseCountriesItem(UniversalBaseModel):
    country: str = pydantic.Field()
    """
    Country identifier in Alpha-2 (US), Alpha-3 (USA), or full name (United_States). Case-insensitive and may use underscores.
    """

    state: typing.Optional[str] = pydantic.Field(default=None)
    """
    Optional state identifier in Alpha-2 (NY) or full name (New_York). Required only for state-level taxation. Case-insensitive and may use underscores.
    """

    type: typing.Optional[str] = pydantic.Field(default=None)
    """
    Tax type applied for the country or state. Possible values include vat or none.
    """

    currency: typing.Optional[str] = pydantic.Field(default=None)
    """
    ISO 4217 currency code.
    """

    standard_rate: typing.Optional[float] = pydantic.Field(default=None)
    """
    Standard VAT or sales tax rate. Zero indicates no tax.
    """

    reduced_rate: typing.Optional[typing.List[float]] = pydantic.Field(default=None)
    """
    Optional reduced VAT rates applicable in the country.
    """

    super_reduced_rate: typing.Optional[typing.List[float]] = pydantic.Field(default=None)
    """
    Optional super-reduced VAT rates applicable in specific categories.
    """

    parking_rate: typing.Optional[float] = None
    categories: typing.Optional[typing.Dict[str, float]] = pydantic.Field(default=None)
    """
    Optional category-wise VAT rates.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
