# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .bulk_ip_security_lookup_response_item_security import BulkIpSecurityLookupResponseItemSecurity


class BulkIpSecurityLookupResponseItem(UniversalBaseModel):
    ip: typing.Optional[str] = None
    security: typing.Optional[BulkIpSecurityLookupResponseItemSecurity] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
