# This file was auto-generated by Fern from our API Definition.

import typing

from .bulk_domain_whois_lookup_v2_response_bulk_whois_response_item_abuse_contact import (
    BulkDomainWhoisLookupV2ResponseBulkWhoisResponseItemAbuseContact,
)
from .bulk_domain_whois_lookup_v2_response_bulk_whois_response_item_error import (
    BulkDomainWhoisLookupV2ResponseBulkWhoisResponseItemError,
)

BulkDomainWhoisLookupV2ResponseBulkWhoisResponseItem = typing.Union[
    BulkDomainWhoisLookupV2ResponseBulkWhoisResponseItemAbuseContact,
    BulkDomainWhoisLookupV2ResponseBulkWhoisResponseItemError,
]
