# This file was auto-generated by Fern from our API Definition.

import typing

from .bulk_geolocation_lookup_v2_response_item_abuse import BulkGeolocationLookupV2ResponseItemAbuse
from .bulk_geolocation_lookup_v2_response_item_message import BulkGeolocationLookupV2ResponseItemMessage

BulkGeolocationLookupV2ResponseItem = typing.Union[
    BulkGeolocationLookupV2ResponseItemAbuse, BulkGeolocationLookupV2ResponseItemMessage
]
