# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .bulk_email_validate_response_email_response_item_account import BulkEmailValidateResponseEmailResponseItemAccount
from .bulk_email_validate_response_email_response_item_address import BulkEmailValidateResponseEmailResponseItemAddress
from .bulk_email_validate_response_email_response_item_dns import BulkEmailValidateResponseEmailResponseItemDns
from .bulk_email_validate_response_email_response_item_domain import BulkEmailValidateResponseEmailResponseItemDomain
from .bulk_email_validate_response_email_response_item_valid_email import (
    BulkEmailValidateResponseEmailResponseItemValidEmail,
)


class BulkEmailValidateResponseEmailResponseItem(UniversalBaseModel):
    success: bool
    email: str
    name: typing.Optional[str] = None
    reason: typing.Optional[str] = None
    valid_email: typing_extensions.Annotated[
        BulkEmailValidateResponseEmailResponseItemValidEmail,
        FieldMetadata(alias="validEmail"),
        pydantic.Field(alias="validEmail"),
    ]
    valid_syntax: typing_extensions.Annotated[
        bool, FieldMetadata(alias="validSyntax"), pydantic.Field(alias="validSyntax")
    ]
    domain: BulkEmailValidateResponseEmailResponseItemDomain
    account: BulkEmailValidateResponseEmailResponseItemAccount
    dns: BulkEmailValidateResponseEmailResponseItemDns
    ip: typing.Optional[str] = None
    address: typing.Optional[BulkEmailValidateResponseEmailResponseItemAddress] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
