# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .bulk_vat_rate_by_country_response_countries_item import BulkVatRateByCountryResponseCountriesItem


class BulkVatRateByCountryResponse(UniversalBaseModel):
    countries: typing.List[BulkVatRateByCountryResponseCountriesItem]

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
