# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class BulkIpSecurityLookupResponseItemSecurity(UniversalBaseModel):
    threat_score: typing.Optional[float] = None
    is_tor: typing.Optional[bool] = None
    is_proxy: typing.Optional[bool] = None
    proxy_provider_names: typing.Optional[typing.List[str]] = None
    proxy_confidence_score: typing.Optional[float] = None
    proxy_last_seen: typing.Optional[str] = None
    is_residential_proxy: typing.Optional[bool] = None
    is_vpn: typing.Optional[bool] = None
    vpn_provider_names: typing.Optional[typing.List[str]] = None
    vpn_confidence_score: typing.Optional[float] = None
    vpn_last_seen: typing.Optional[str] = None
    is_relay: typing.Optional[bool] = None
    relay_provider_name: typing.Optional[str] = None
    is_anonymous: typing.Optional[bool] = None
    is_known_attacker: typing.Optional[bool] = None
    is_bot: typing.Optional[bool] = None
    is_spam: typing.Optional[bool] = None
    is_cloud_provider: typing.Optional[bool] = None
    cloud_provider_name: typing.Optional[str] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
