# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .bulk_user_agent_lookup_response_item_device import BulkUserAgentLookupResponseItemDevice
from .bulk_user_agent_lookup_response_item_engine import BulkUserAgentLookupResponseItemEngine
from .bulk_user_agent_lookup_response_item_operating_system import BulkUserAgentLookupResponseItemOperatingSystem


class BulkUserAgentLookupResponseItem(UniversalBaseModel):
    user_agent_string: str = pydantic.Field()
    """
    User-agent string that is parsed for browser, device and operating system details.
    """

    name: str = pydantic.Field()
    """
    Agent name or the actual browser name that was used.
    """

    type: str = pydantic.Field()
    """
    Agent type or the browser type that was used. Possible values:
    1. Browser
    2. Browser Webview
    3. Mobile App
    4. Robot Mobile
    5. Cloud Application
    6. Email Client
    7. Voice
    8. Special
    9. Testclient
    10. Hacker
    11. Unknown
    """

    version: str = pydantic.Field()
    """
    Agent version or the browser version
    """

    version_major: str = pydantic.Field()
    """
    Agent version major or the browser version major
    """

    device: BulkUserAgentLookupResponseItemDevice
    engine: BulkUserAgentLookupResponseItemEngine
    operating_system: BulkUserAgentLookupResponseItemOperatingSystem
    message: typing.Optional[str] = pydantic.Field(default=None)
    """
    Error message for this user-agent string, present only if parsing of this entry failed.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
