# This file was auto-generated by Fern from our API Definition.

import typing

BulkEmailValidateResponseEmailValidationResponsesItemValidEmail = typing.Union[
    typing.Literal["valid", "Invalid", "Unknown", "Risky"], typing.Any
]
