# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class BulkCurrentWeatherResponseBulkItemCurrentAstronomy(UniversalBaseModel):
    """
    Astronomical information including sunrise, sunset, and moon phases for the current date.
    """

    date: dt.date = pydantic.Field()
    """
    Calendar date in YYYY-MM-DD format for the astronomical data.
    """

    mid_night: str = pydantic.Field()
    """
    Time of true solar midnight in HH:MM format.
    """

    night_end: str = pydantic.Field()
    """
    Time when astronomical twilight ends and dawn begins in HH:MM format.
    """

    sunrise: str = pydantic.Field()
    """
    Time when the Sun becomes visible above the horizon in HH:MM format.
    """

    solar_noon: str = pydantic.Field()
    """
    Time when the Sun reaches its highest point in the sky in HH:MM format.
    """

    sunset: str = pydantic.Field()
    """
    Time when the Sun disappears below the horizon in HH:MM format.
    """

    night_begin: str = pydantic.Field()
    """
    Time when astronomical twilight begins and night starts in HH:MM format.
    """

    day_length: str = pydantic.Field()
    """
    Total duration of daylight in HH:MM format.
    """

    sun_status: str = pydantic.Field()
    """
    Current position of the Sun relative to the horizon (above_horizon, below_horizon, or -).
    """

    moon_phase: str = pydantic.Field()
    """
    Current lunar phase (NEW_MOON, WAXING_CRESCENT, FULL_MOON, WANING_GIBBOUS, etc.).
    """

    moonrise: str = pydantic.Field()
    """
    Time when the Moon becomes visible above the horizon in HH:MM format.
    """

    moonset: str = pydantic.Field()
    """
    Time when the Moon disappears below the horizon in HH:MM format.
    """

    moon_status: str = pydantic.Field()
    """
    Current visibility status of the Moon (visible, not_visible, or -).
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
