# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .bulk_geolocation_lookup_response_item_abuse_item import BulkGeolocationLookupResponseItemAbuseItem
from .bulk_geolocation_lookup_response_item_country_metadata import BulkGeolocationLookupResponseItemCountryMetadata
from .bulk_geolocation_lookup_response_item_currency import BulkGeolocationLookupResponseItemCurrency
from .bulk_geolocation_lookup_response_item_location import BulkGeolocationLookupResponseItemLocation
from .bulk_geolocation_lookup_response_item_network import BulkGeolocationLookupResponseItemNetwork
from .bulk_geolocation_lookup_response_item_security import BulkGeolocationLookupResponseItemSecurity
from .bulk_geolocation_lookup_response_item_time_zone import BulkGeolocationLookupResponseItemTimeZone
from .bulk_geolocation_lookup_response_item_user_agent import BulkGeolocationLookupResponseItemUserAgent


class BulkGeolocationLookupResponseItem(UniversalBaseModel):
    ip: typing.Optional[str] = pydantic.Field(default=None)
    """
    The IP address
    """

    hostname: typing.Optional[str] = pydantic.Field(default=None)
    """
    The hostname (if available)
    """

    location: typing.Optional[BulkGeolocationLookupResponseItemLocation] = None
    country_metadata: typing.Optional[BulkGeolocationLookupResponseItemCountryMetadata] = None
    network: typing.Optional[BulkGeolocationLookupResponseItemNetwork] = None
    currency: typing.Optional[BulkGeolocationLookupResponseItemCurrency] = None
    security: typing.Optional[BulkGeolocationLookupResponseItemSecurity] = None
    abuse: typing.Optional[typing.List[BulkGeolocationLookupResponseItemAbuseItem]] = None
    time_zone: typing.Optional[BulkGeolocationLookupResponseItemTimeZone] = None
    user_agent: typing.Optional[BulkGeolocationLookupResponseItemUserAgent] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
