# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class BulkDomainWhoisLookupV2ResponseBulkWhoisResponseItemAbuseContactRegistryDataDomainRegistrar(UniversalBaseModel):
    """
    Registrar of record for a domain, as published by either the registrar or the registry.
    """

    iana_id: typing.Optional[str] = pydantic.Field(default=None)
    """
    IANA registrar ID.
    """

    id: typing.Optional[str] = pydantic.Field(default=None)
    """
    Registrar identifier.
    """

    id_type: typing.Optional[str] = pydantic.Field(default=None)
    """
    Type of registrar ID (e.g. IANA).
    """

    handle: typing.Optional[str] = pydantic.Field(default=None)
    """
    Registrar handle.
    """

    registry_id: typing.Optional[str] = pydantic.Field(default=None)
    """
    Registry-specific registrar ID.
    """

    authoritative_registry_name: typing.Optional[str] = pydantic.Field(default=None)
    """
    Registry authority name.
    """

    organization_number: typing.Optional[str] = pydantic.Field(default=None)
    """
    Registrar organization number.
    """

    is_sponsor: typing.Optional[bool] = pydantic.Field(default=None)
    """
    Indicates if the registrar is a sponsor.
    """

    status: typing.Optional[str] = pydantic.Field(default=None)
    """
    Registrar's ICANN accreditation status (e.g. accredited), when published at the registrar level.
    """

    registrar_name: typing.Optional[str] = pydantic.Field(default=None)
    """
    Registered name of the registrar.
    """

    normalized_name: typing.Optional[str] = pydantic.Field(default=None)
    """
    Lowercased, normalized form of the registrar name, when published at the registrar level.
    """

    whois_server: typing.Optional[str] = pydantic.Field(default=None)
    """
    WHOIS server operated by the registrar.
    """

    rdap_server: typing.Optional[str] = pydantic.Field(default=None)
    """
    RDAP server URL operated by the registrar, when published at the registrar level.
    """

    website_url: typing.Optional[str] = pydantic.Field(default=None)
    """
    Registrar's website URL.
    """

    email_address: typing.Optional[str] = pydantic.Field(default=None)
    """
    Registrar abuse or contact email address.
    """

    phone_number: typing.Optional[str] = pydantic.Field(default=None)
    """
    Registrar contact phone number.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
