# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class BulkGeolocationLookupResponseItemCountryMetadata(UniversalBaseModel):
    calling_code: typing.Optional[str] = pydantic.Field(default=None)
    """
    The calling code of the country
    """

    tld: typing.Optional[str] = pydantic.Field(default=None)
    """
    The top level domain of the country
    """

    languages: typing.Optional[typing.List[str]] = pydantic.Field(default=None)
    """
    The languages spoken in the country
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
