# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class BulkPhoneValidateRequestNumbersItem(UniversalBaseModel):
    number: str = pydantic.Field()
    """
    Phone number to validate.
    """

    region: typing.Optional[str] = pydantic.Field(default=None)
    """
    Two-letter ISO country code. Required for local format numbers. Cannot be used together with dialer_region.
    """

    dialer_region: typing.Optional[str] = pydantic.Field(default=None)
    """
    Two-letter ISO country code of the dialing origin. Required for IDD format numbers. Cannot be used together with region.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
