# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .bulk_email_validate_response_email_response_item import BulkEmailValidateResponseEmailResponseItem


class BulkEmailValidateResponse(UniversalBaseModel):
    email_response: typing_extensions.Annotated[
        typing.List[BulkEmailValidateResponseEmailResponseItem],
        FieldMetadata(alias="emailResponse"),
        pydantic.Field(
            alias="emailResponse", description="Array of SingleEmailValidationResponse objects for bulk validation"
        ),
    ]
    """
    Array of SingleEmailValidationResponse objects for bulk validation
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
