# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .bulk_email_validate_response_email_validation_responses_item import (
    BulkEmailValidateResponseEmailValidationResponsesItem,
)


class BulkEmailValidateResponse(UniversalBaseModel):
    email_validation_responses: typing_extensions.Annotated[
        typing.Optional[typing.List[BulkEmailValidateResponseEmailValidationResponsesItem]],
        FieldMetadata(alias="emailValidationResponses"),
        pydantic.Field(
            alias="emailValidationResponses",
            description="Array of SingleEmailValidationResponse objects for bulk validation",
        ),
    ] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
