# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class BulkUserAgentLookupResponseItemOperatingSystem(UniversalBaseModel):
    name: str = pydantic.Field()
    """
    Operating system name or the base software name that runs on the hardware.
    """

    type: str = pydantic.Field()
    """
    Operating system type. Possible values:
    1. Desktop
    2. Mobile
    3. Game Console
    4. Embedded
    5. Cloud
    6. Hacker
    7. Anonymized
    8. Unknown
    """

    version: str = pydantic.Field()
    """
    Operating system version
    """

    version_major: str = pydantic.Field()
    """
    Operating system version major
    """

    build: str = pydantic.Field()
    """
    Operating system build
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
