# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class BulkGeolocationLookupV2ResponseItemMessage(UniversalBaseModel):
    """
    Per-item error, returned in place of a location result when an individual IP is invalid, bogon/reserved, or not found in the database.
    """

    message: str = pydantic.Field()
    """
    Human-readable reason this IP could not be resolved.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
