# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .bulk_domain_availability_check_response_bulk_domain_available_response_item import (
    BulkDomainAvailabilityCheckResponseBulkDomainAvailableResponseItem,
)


class BulkDomainAvailabilityCheckResponse(UniversalBaseModel):
    bulk_domain_available_response: typing.List[
        BulkDomainAvailabilityCheckResponseBulkDomainAvailableResponseItem
    ] = pydantic.Field()
    """
    List of domain availability objects.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
