# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata


class BulkEmailValidateResponseEmailValidationResponsesItemDomain(UniversalBaseModel):
    name: str
    disposable: bool
    spam: bool
    free: bool
    catch_all: typing_extensions.Annotated[bool, FieldMetadata(alias="catchAll"), pydantic.Field(alias="catchAll")]
    valid_domain: typing_extensions.Annotated[
        bool, FieldMetadata(alias="validDomain"), pydantic.Field(alias="validDomain")
    ]

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
