# This file was auto-generated by Fern from our API Definition.

import typing

BulkDomainDnsLookupResponseBulkDnsInfoItemDnsRecordsItemSingleNameDnsType = typing.Union[
    typing.Literal["NS"], typing.Any
]
