# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .bulk_phone_validate_response_item_formats import BulkPhoneValidateResponseItemFormats
from .bulk_phone_validate_response_item_line_type import BulkPhoneValidateResponseItemLineType
from .bulk_phone_validate_response_item_raw_input import BulkPhoneValidateResponseItemRawInput


class BulkPhoneValidateResponseItem(UniversalBaseModel):
    raw_input: typing.Optional[BulkPhoneValidateResponseItemRawInput] = pydantic.Field(default=None)
    """
    The original request data provided by the client.
    """

    possible: typing.Optional[bool] = pydantic.Field(default=None)
    """
    Whether the number passes length and format checks.
    """

    valid: typing.Optional[bool] = pydantic.Field(default=None)
    """
    Whether the number is valid according to the numbering plan.
    """

    country_prefix: typing.Optional[int] = pydantic.Field(default=None)
    """
    International dialing prefix for the number's country.
    """

    national_number: typing.Optional[int] = pydantic.Field(default=None)
    """
    National significant number without the country code.
    """

    country_code: typing.Optional[str] = pydantic.Field(default=None)
    """
    ISO-2 country code inferred from the number.
    """

    carrier: typing.Optional[str] = pydantic.Field(default=None)
    """
    Carrier name associated with the number.
    """

    location: typing.Optional[str] = pydantic.Field(default=None)
    """
    Geographic description (city/region) for the number.
    """

    time_zones: typing.Optional[typing.List[str]] = pydantic.Field(default=None)
    """
    Array of possible IANA time zones associated with the number.
    """

    line_type: typing.Optional[BulkPhoneValidateResponseItemLineType] = pydantic.Field(default=None)
    """
    Classification of the phone line.
    """

    formats: typing.Optional[BulkPhoneValidateResponseItemFormats] = pydantic.Field(default=None)
    """
    The number represented in four standardized formats. Only returned for valid numbers.
    """

    area_code_length: typing.Optional[int] = pydantic.Field(default=None)
    """
    Length of the geographic area code. Only for geographically-assigned numbers.
    """

    ndc_length: typing.Optional[int] = pydantic.Field(default=None)
    """
    Length of the National Destination Code.
    """

    can_be_internationally_dialled: typing.Optional[bool] = pydantic.Field(default=None)
    """
    Whether the number can be dialled internationally.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
