# This file was auto-generated by Fern from our API Definition.

import typing

BulkDomainDnsLookupResponseBulkDnsInfoItemDnsRecordsItemPriorityDnsType = typing.Union[typing.Literal["MX"], typing.Any]
