# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class BulkDomainWhoisLookupV2ResponseBulkWhoisResponseItemError(UniversalBaseModel):
    """
    Per-item error, returned in place of a WHOIS result when an individual domain's extension is unsupported or its lookup otherwise fails.
    """

    status: bool = pydantic.Field()
    """
    Always false for a per-item error.
    """

    domain_name: str = pydantic.Field()
    """
    Domain name that this error applies to.
    """

    status_code: int = pydantic.Field()
    """
    HTTP-equivalent status code for this item's failure (e.g. 403 for an unsupported extension).
    """

    error: typing.Optional[str] = pydantic.Field(default=None)
    """
    Short error category or exception type.
    """

    message: str = pydantic.Field()
    """
    Human-readable reason this domain could not be resolved.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
