# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .bulk_current_weather_response_bulk_item import BulkCurrentWeatherResponseBulkItem


class BulkCurrentWeatherResponse(UniversalBaseModel):
    bulk: typing.List[BulkCurrentWeatherResponseBulkItem] = pydantic.Field()
    """
    Array of weather data
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
