# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata


class BulkCurrentWeatherResponseBulkItemCurrentAirQuality(UniversalBaseModel):
    """
    Air quality metrics including pollutant concentrations and AQI values.
    """

    timestamp: dt.datetime = pydantic.Field()
    """
    ISO 8601 formatted timestamp (iso8601).
    """

    european_aqi: int = pydantic.Field()
    """
    Consolidated European Air Quality Index representing the highest value among individual pollutant indices. Ranges: 0-20 (good), 20-40 (fair), 40-60 (moderate), 60-80 (poor), 80-100 (very poor), >100 (extremely poor).
    """

    us_aqi: int = pydantic.Field()
    """
    Consolidated U.S. Air Quality Index representing the highest value among individual pollutant indices. Ranges: 0-50 (good), 51-100 (moderate), 101-150 (unhealthy for sensitive groups), 151-200 (unhealthy), 201-300 (very unhealthy), 301-500 (hazardous).
    """

    pm10: float = pydantic.Field()
    """
    Particulate matter with diameter less than 10 micrometers (μg/m³) measured at 10 meters above ground.
    """

    pm25: typing_extensions.Annotated[
        float,
        FieldMetadata(alias="pm2_5"),
        pydantic.Field(
            alias="pm2_5",
            description="Particulate matter with diameter less than 2.5 micrometers (μg/m³) measured at 10 meters above ground.",
        ),
    ]
    carbon_monoxide: float = pydantic.Field()
    """
    Atmospheric carbon monoxide gas concentration (μg/m³) at 10 meters above ground.
    """

    nitrogen_dioxide: float = pydantic.Field()
    """
    Atmospheric nitrogen dioxide gas concentration (μg/m³) at 10 meters above ground.
    """

    sulphur_dioxide: float = pydantic.Field()
    """
    Atmospheric sulphur dioxide gas concentration (μg/m³) at 10 meters above ground.
    """

    ozone: float = pydantic.Field()
    """
    Atmospheric ozone gas concentration (μg/m³) at 10 meters above ground.
    """

    dust: float = pydantic.Field()
    """
    Saharan dust particle concentration (μg/m³) at 10 meters above ground.
    """

    uv_index: float = pydantic.Field()
    """
    Ultraviolet radiation intensity index accounting for cloud coverage.
    """

    aerosol_optical_depth: float = pydantic.Field()
    """
    Aerosol optical depth at 550 nm wavelength indicating atmospheric haze levels.
    """

    uv_index_clear_sky: float = pydantic.Field()
    """
    Ultraviolet radiation intensity index assuming cloud-free conditions.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
