# This file was auto-generated by Fern from our API Definition.

import typing

from .bulk_current_weather_response_bulk_item_location_city import BulkCurrentWeatherResponseBulkItemLocationCity
from .bulk_current_weather_response_bulk_item_location_continent_code import (
    BulkCurrentWeatherResponseBulkItemLocationContinentCode,
)
from .bulk_current_weather_response_bulk_item_location_zero import BulkCurrentWeatherResponseBulkItemLocationZero

BulkCurrentWeatherResponseBulkItemLocation = typing.Union[
    BulkCurrentWeatherResponseBulkItemLocationZero,
    BulkCurrentWeatherResponseBulkItemLocationContinentCode,
    BulkCurrentWeatherResponseBulkItemLocationCity,
]
