# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .bulk_domain_whois_lookup_v2_response_bulk_whois_response_item_abuse_contact_abuse_contact import (
    BulkDomainWhoisLookupV2ResponseBulkWhoisResponseItemAbuseContactAbuseContact,
)
from .bulk_domain_whois_lookup_v2_response_bulk_whois_response_item_abuse_contact_administrative_contact import (
    BulkDomainWhoisLookupV2ResponseBulkWhoisResponseItemAbuseContactAdministrativeContact,
)
from .bulk_domain_whois_lookup_v2_response_bulk_whois_response_item_abuse_contact_billing_contact import (
    BulkDomainWhoisLookupV2ResponseBulkWhoisResponseItemAbuseContactBillingContact,
)
from .bulk_domain_whois_lookup_v2_response_bulk_whois_response_item_abuse_contact_domain_registered import (
    BulkDomainWhoisLookupV2ResponseBulkWhoisResponseItemAbuseContactDomainRegistered,
)
from .bulk_domain_whois_lookup_v2_response_bulk_whois_response_item_abuse_contact_domain_registrar import (
    BulkDomainWhoisLookupV2ResponseBulkWhoisResponseItemAbuseContactDomainRegistrar,
)
from .bulk_domain_whois_lookup_v2_response_bulk_whois_response_item_abuse_contact_eligibility_info import (
    BulkDomainWhoisLookupV2ResponseBulkWhoisResponseItemAbuseContactEligibilityInfo,
)
from .bulk_domain_whois_lookup_v2_response_bulk_whois_response_item_abuse_contact_registrant_contact import (
    BulkDomainWhoisLookupV2ResponseBulkWhoisResponseItemAbuseContactRegistrantContact,
)
from .bulk_domain_whois_lookup_v2_response_bulk_whois_response_item_abuse_contact_registry_data import (
    BulkDomainWhoisLookupV2ResponseBulkWhoisResponseItemAbuseContactRegistryData,
)
from .bulk_domain_whois_lookup_v2_response_bulk_whois_response_item_abuse_contact_reseller_contact import (
    BulkDomainWhoisLookupV2ResponseBulkWhoisResponseItemAbuseContactResellerContact,
)
from .bulk_domain_whois_lookup_v2_response_bulk_whois_response_item_abuse_contact_technical_contact import (
    BulkDomainWhoisLookupV2ResponseBulkWhoisResponseItemAbuseContactTechnicalContact,
)


class BulkDomainWhoisLookupV2ResponseBulkWhoisResponseItemAbuseContact(UniversalBaseModel):
    """
    Current WHOIS registration record for one successfully resolved domain.
    """

    status: bool = pydantic.Field()
    """
    true if this item was successfully processed.
    """

    domain_name: str = pydantic.Field()
    """
    Domain name that was queried.
    """

    query_time: str = pydantic.Field()
    """
    Timestamp when the WHOIS query was executed.
    """

    whois_server: typing.Optional[str] = pydantic.Field(default=None)
    """
    WHOIS or RDAP server that provided this record.
    """

    domain_registered: BulkDomainWhoisLookupV2ResponseBulkWhoisResponseItemAbuseContactDomainRegistered = (
        pydantic.Field()
    )
    """
    Domain registration status; 'restricted' means the registry withholds registration details.
    """

    secure_dns: typing.Optional[bool] = pydantic.Field(default=None)
    """
    Indicates if DNSSEC or secure DNS is enabled for the domain.
    """

    domain_handle: typing.Optional[str] = pydantic.Field(default=None)
    """
    Internal domain registry handle/ID.
    """

    create_date: typing.Optional[dt.date] = pydantic.Field(default=None)
    """
    Date the domain was originally registered, when the domain is registered.
    """

    update_date: typing.Optional[dt.date] = pydantic.Field(default=None)
    """
    Date the domain registration was last updated, when the domain is registered.
    """

    expiry_date: typing.Optional[dt.date] = pydantic.Field(default=None)
    """
    Date the domain registration is set to expire, when the domain is registered.
    """

    domain_registrar: typing.Optional[
        BulkDomainWhoisLookupV2ResponseBulkWhoisResponseItemAbuseContactDomainRegistrar
    ] = pydantic.Field(default=None)
    """
    Registrar of record for a domain, as published by either the registrar or the registry.
    """

    reseller_contact: typing.Optional[
        BulkDomainWhoisLookupV2ResponseBulkWhoisResponseItemAbuseContactResellerContact
    ] = pydantic.Field(default=None)
    """
    A contact record (registrant, administrative, technical, billing, or reseller) published in the domain's WHOIS record.
    """

    registrant_contact: typing.Optional[
        BulkDomainWhoisLookupV2ResponseBulkWhoisResponseItemAbuseContactRegistrantContact
    ] = pydantic.Field(default=None)
    """
    A contact record (registrant, administrative, technical, billing, or reseller) published in the domain's WHOIS record.
    """

    administrative_contact: typing.Optional[
        BulkDomainWhoisLookupV2ResponseBulkWhoisResponseItemAbuseContactAdministrativeContact
    ] = pydantic.Field(default=None)
    """
    A contact record (registrant, administrative, technical, billing, or reseller) published in the domain's WHOIS record.
    """

    technical_contact: typing.Optional[
        BulkDomainWhoisLookupV2ResponseBulkWhoisResponseItemAbuseContactTechnicalContact
    ] = pydantic.Field(default=None)
    """
    A contact record (registrant, administrative, technical, billing, or reseller) published in the domain's WHOIS record.
    """

    billing_contact: typing.Optional[BulkDomainWhoisLookupV2ResponseBulkWhoisResponseItemAbuseContactBillingContact] = (
        pydantic.Field(default=None)
    )
    """
    A contact record (registrant, administrative, technical, billing, or reseller) published in the domain's WHOIS record.
    """

    abuse_contact: typing.Optional[BulkDomainWhoisLookupV2ResponseBulkWhoisResponseItemAbuseContactAbuseContact] = (
        pydantic.Field(default=None)
    )
    """
    Registrar's abuse-reporting contact.
    """

    eligibility_info: typing.Optional[
        BulkDomainWhoisLookupV2ResponseBulkWhoisResponseItemAbuseContactEligibilityInfo
    ] = pydantic.Field(default=None)
    """
    Domain eligibility information (populated for TLDs with registrant eligibility requirements, e.g. .eu).
    """

    name_servers: typing.Optional[typing.List[str]] = pydantic.Field(default=None)
    """
    Name servers currently recorded for the domain.
    """

    domain_status: typing.Optional[typing.List[str]] = pydantic.Field(default=None)
    """
    EPP domain status codes currently recorded for the domain.
    """

    whois_raw_domain: typing.Optional[str] = pydantic.Field(default=None)
    """
    Raw WHOIS text as returned by the registrar's WHOIS server.
    """

    registry_data: typing.Optional[BulkDomainWhoisLookupV2ResponseBulkWhoisResponseItemAbuseContactRegistryData] = (
        pydantic.Field(default=None)
    )
    """
    Registry-level (as opposed to registrar-level) WHOIS data, sourced directly from the TLD registry.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
