# This file was auto-generated by Fern from our API Definition.

import typing

BulkDomainDnsLookupResponseBulkDnsInfoItemDnsRecordsItemAddressDnsType = typing.Union[
    typing.Literal["A", "AAAA"], typing.Any
]
