# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .bulk_geolocation_lookup_v2_response_item_abuse_abuse import BulkGeolocationLookupV2ResponseItemAbuseAbuse
from .bulk_geolocation_lookup_v2_response_item_abuse_asn import BulkGeolocationLookupV2ResponseItemAbuseAsn
from .bulk_geolocation_lookup_v2_response_item_abuse_company import BulkGeolocationLookupV2ResponseItemAbuseCompany
from .bulk_geolocation_lookup_v2_response_item_abuse_country_metadata import (
    BulkGeolocationLookupV2ResponseItemAbuseCountryMetadata,
)
from .bulk_geolocation_lookup_v2_response_item_abuse_currency import BulkGeolocationLookupV2ResponseItemAbuseCurrency
from .bulk_geolocation_lookup_v2_response_item_abuse_location import BulkGeolocationLookupV2ResponseItemAbuseLocation
from .bulk_geolocation_lookup_v2_response_item_abuse_network import BulkGeolocationLookupV2ResponseItemAbuseNetwork
from .bulk_geolocation_lookup_v2_response_item_abuse_security import BulkGeolocationLookupV2ResponseItemAbuseSecurity
from .bulk_geolocation_lookup_v2_response_item_abuse_time_zone import BulkGeolocationLookupV2ResponseItemAbuseTimeZone
from .bulk_geolocation_lookup_v2_response_item_abuse_user_agent import BulkGeolocationLookupV2ResponseItemAbuseUserAgent


class BulkGeolocationLookupV2ResponseItemAbuse(UniversalBaseModel):
    """
    Geolocation and threat intelligence result for one successfully resolved IP address.
    """

    ip: str = pydantic.Field()
    """
    The IP address used for the lookup (IPv4 or IPv6).
    """

    domain: typing.Optional[str] = pydantic.Field(default=None)
    """
    The input domain, returned only for domain-based lookups.
    """

    hostname: typing.Optional[str] = pydantic.Field(default=None)
    """
    Reverse DNS hostname (PTR) for the input IP; returns the input IP if not resolvable.
    """

    location: typing.Optional[BulkGeolocationLookupV2ResponseItemAbuseLocation] = pydantic.Field(default=None)
    """
    Geographic location information for the IP.
    """

    country_metadata: typing.Optional[BulkGeolocationLookupV2ResponseItemAbuseCountryMetadata] = pydantic.Field(
        default=None
    )
    """
    Country-specific metadata.
    """

    network: typing.Optional[BulkGeolocationLookupV2ResponseItemAbuseNetwork] = pydantic.Field(default=None)
    """
    Network information for the IP.
    """

    asn: typing.Optional[BulkGeolocationLookupV2ResponseItemAbuseAsn] = pydantic.Field(default=None)
    """
    Autonomous System details for the IP.
    """

    company: typing.Optional[BulkGeolocationLookupV2ResponseItemAbuseCompany] = pydantic.Field(default=None)
    """
    Company or ISP information mapped to the IP address.
    """

    currency: typing.Optional[BulkGeolocationLookupV2ResponseItemAbuseCurrency] = pydantic.Field(default=None)
    """
    Currency information for the IP's country.
    """

    security: typing.Optional[BulkGeolocationLookupV2ResponseItemAbuseSecurity] = pydantic.Field(default=None)
    """
    Threat intelligence and security information for the IP.
    """

    abuse: typing.Optional[BulkGeolocationLookupV2ResponseItemAbuseAbuse] = pydantic.Field(default=None)
    """
    Abuse contact information for the IP.
    """

    time_zone: typing.Optional[BulkGeolocationLookupV2ResponseItemAbuseTimeZone] = pydantic.Field(default=None)
    """
    Time zone information for the IP's location.
    """

    user_agent: typing.Optional[BulkGeolocationLookupV2ResponseItemAbuseUserAgent] = pydantic.Field(default=None)
    """
    Parsed User-Agent details from the request.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
