# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class BulkGeolocationLookupV2ResponseItemAbuseNetwork(UniversalBaseModel):
    """
    Network information for the IP.
    """

    connection_type: typing.Optional[str] = pydantic.Field(default=None)
    """
    Network access type classification (e.g., DSL, Cable, Mobile, 5G) when available.
    """

    route: typing.Optional[str] = pydantic.Field(default=None)
    """
    Network prefix in CIDR notation that contains the IP.
    """

    is_anycast: typing.Optional[bool] = pydantic.Field(default=None)
    """
    true if the IP is anycast (same IP announced from multiple locations).
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
