# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class BulkGeolocationLookupResponseItemNetworkAsn(UniversalBaseModel):
    as_number: typing.Optional[str] = pydantic.Field(default=None)
    """
    The AS number
    """

    organization: typing.Optional[str] = pydantic.Field(default=None)
    """
    The organization name
    """

    country: typing.Optional[str] = pydantic.Field(default=None)
    """
    The country code
    """

    asn_name: typing.Optional[str] = pydantic.Field(default=None)
    """
    The ASN name
    """

    type: typing.Optional[str] = pydantic.Field(default=None)
    """
    The type of the ASN
    """

    domain: typing.Optional[str] = pydantic.Field(default=None)
    """
    The domain associated with the ASN
    """

    date_allocated: typing.Optional[str] = pydantic.Field(default=None)
    """
    The date when the ASN was allocated
    """

    allocation_status: typing.Optional[str] = pydantic.Field(default=None)
    """
    The allocation status of the ASN
    """

    num_of_ipv4_routes: typing.Optional[str] = pydantic.Field(default=None)
    """
    The number of IPv4 routes associated with the ASN
    """

    num_of_ipv6_routes: typing.Optional[str] = pydantic.Field(default=None)
    """
    The number of IPv6 routes associated with the ASN
    """

    rir: typing.Optional[str] = pydantic.Field(default=None)
    """
    The Regional Internet Registry (RIR) of the ASN
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
