# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class BulkGeolocationLookupV2ResponseItemAbuseAbuse(UniversalBaseModel):
    """
    Abuse contact information for the IP.
    """

    route: typing.Optional[str] = pydantic.Field(default=None)
    """
    Abuse-handling IP range in CIDR notation.
    """

    country: typing.Optional[str] = pydantic.Field(default=None)
    """
    ISO 3166-1 alpha-2 country code of the abuse contact.
    """

    name: typing.Optional[str] = pydantic.Field(default=None)
    """
    Display name for the abuse contact.
    """

    organization: typing.Optional[str] = pydantic.Field(default=None)
    """
    Organization name for the abuse contact.
    """

    kind: typing.Optional[str] = pydantic.Field(default=None)
    """
    Contact type: group or individual.
    """

    address: typing.Optional[str] = pydantic.Field(default=None)
    """
    Registered address of the organization owning the IP.
    """

    emails: typing.Optional[typing.List[str]] = pydantic.Field(default=None)
    """
    Abuse contact email addresses.
    """

    phone_numbers: typing.Optional[typing.List[str]] = pydantic.Field(default=None)
    """
    Abuse contact phone numbers.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
