# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .bulk_geolocation_lookup_v2_response_item_abuse_time_zone_dst_end import (
    BulkGeolocationLookupV2ResponseItemAbuseTimeZoneDstEnd,
)
from .bulk_geolocation_lookup_v2_response_item_abuse_time_zone_dst_start import (
    BulkGeolocationLookupV2ResponseItemAbuseTimeZoneDstStart,
)


class BulkGeolocationLookupV2ResponseItemAbuseTimeZone(UniversalBaseModel):
    """
    Time zone information for the IP's location.
    """

    name: str = pydantic.Field()
    """
    Time zone in IANA TZDB format.
    """

    offset: float = pydantic.Field()
    """
    Standard time UTC offset in hours.
    """

    offset_with_dst: float = pydantic.Field()
    """
    Current effective UTC offset in hours, including DST.
    """

    current_time: str = pydantic.Field()
    """
    Local date/time in YYYY-MM-DD HH:mm:ss.SSS±ZZZZ format.
    """

    current_time_unix: float = pydantic.Field()
    """
    Local time as Unix epoch seconds.
    """

    current_tz_abbreviation: typing.Optional[str] = pydantic.Field(default=None)
    """
    Current time zone abbreviation.
    """

    current_tz_full_name: typing.Optional[str] = pydantic.Field(default=None)
    """
    Current time zone full name.
    """

    standard_tz_abbreviation: typing.Optional[str] = pydantic.Field(default=None)
    """
    Standard (non-DST) abbreviation.
    """

    standard_tz_full_name: typing.Optional[str] = pydantic.Field(default=None)
    """
    Standard (non-DST) full name.
    """

    is_dst: bool = pydantic.Field()
    """
    true if DST is active.
    """

    dst_savings: float = pydantic.Field()
    """
    DST shift amount in hours.
    """

    dst_exists: bool = pydantic.Field()
    """
    true if the time zone observes DST.
    """

    dst_tz_abbreviation: typing.Optional[str] = pydantic.Field(default=None)
    """
    DST abbreviation when DST is active.
    """

    dst_tz_full_name: typing.Optional[str] = pydantic.Field(default=None)
    """
    DST full name when DST is active.
    """

    dst_start: typing.Optional[BulkGeolocationLookupV2ResponseItemAbuseTimeZoneDstStart] = pydantic.Field(default=None)
    """
    DST transition details (used for both the DST start and DST end transitions).
    """

    dst_end: typing.Optional[BulkGeolocationLookupV2ResponseItemAbuseTimeZoneDstEnd] = pydantic.Field(default=None)
    """
    DST transition details (used for both the DST start and DST end transitions).
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
