# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .bulk_email_validate_response_email_validation_responses_item_account import (
    BulkEmailValidateResponseEmailValidationResponsesItemAccount,
)
from .bulk_email_validate_response_email_validation_responses_item_address import (
    BulkEmailValidateResponseEmailValidationResponsesItemAddress,
)
from .bulk_email_validate_response_email_validation_responses_item_dns import (
    BulkEmailValidateResponseEmailValidationResponsesItemDns,
)
from .bulk_email_validate_response_email_validation_responses_item_domain import (
    BulkEmailValidateResponseEmailValidationResponsesItemDomain,
)
from .bulk_email_validate_response_email_validation_responses_item_valid_email import (
    BulkEmailValidateResponseEmailValidationResponsesItemValidEmail,
)


class BulkEmailValidateResponseEmailValidationResponsesItem(UniversalBaseModel):
    success: bool
    email: str
    name: typing.Optional[str] = None
    reason: typing.Optional[str] = None
    valid_email: typing_extensions.Annotated[
        BulkEmailValidateResponseEmailValidationResponsesItemValidEmail,
        FieldMetadata(alias="validEmail"),
        pydantic.Field(alias="validEmail"),
    ]
    valid_syntax: typing_extensions.Annotated[
        bool, FieldMetadata(alias="validSyntax"), pydantic.Field(alias="validSyntax")
    ]
    domain: BulkEmailValidateResponseEmailValidationResponsesItemDomain
    account: BulkEmailValidateResponseEmailValidationResponsesItemAccount
    dns: BulkEmailValidateResponseEmailValidationResponsesItemDns
    ip: typing.Optional[str] = None
    address: typing.Optional[BulkEmailValidateResponseEmailValidationResponsesItemAddress] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
