# This file was auto-generated by Fern from our API Definition.

import typing

CommoditySymbolsV2ResponseSymbolsItemUpdateInterval = typing.Union[
    typing.Literal["PER_SECOND", "PER_MINUTE", "PER_10_MINUTES", "PER_HOUR", "PER_DAY", "PER_WEEK", "PER_MONTH"],
    typing.Any,
]
