# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class CommoditySymbolsResponseSymbolsItemUnit(UniversalBaseModel):
    symbol: str = pydantic.Field()
    """
    The abbreviated unit symbol (e.g., "T.oz", "MMBtu").
    """

    name: str = pydantic.Field()
    """
    The full name of the unit of measurement.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
