# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .commodity_symbols_response_symbols_item_currency import CommoditySymbolsResponseSymbolsItemCurrency
from .commodity_symbols_response_symbols_item_unit import CommoditySymbolsResponseSymbolsItemUnit
from .commodity_symbols_response_symbols_item_update_interval import CommoditySymbolsResponseSymbolsItemUpdateInterval


class CommoditySymbolsResponseSymbolsItem(UniversalBaseModel):
    symbol: str = pydantic.Field()
    """
    The unique ticker symbol for the commodity (e.g., "XAU", "NG-FUT").
    """

    name: str = pydantic.Field()
    """
    The full name of the commodity (e.g., "Gold", "Natural Gas Futures").
    """

    category: str = pydantic.Field()
    """
    The category the commodity belongs to (e.g., "Metals", "Energy").
    """

    status: str = pydantic.Field()
    """
    The current status of the commodity. Possible value: "active".
    """

    update_interval: typing_extensions.Annotated[
        CommoditySymbolsResponseSymbolsItemUpdateInterval,
        FieldMetadata(alias="updateInterval"),
        pydantic.Field(alias="updateInterval", description="The rate at which this commodity's price is updated."),
    ]
    currency: CommoditySymbolsResponseSymbolsItemCurrency
    unit: CommoditySymbolsResponseSymbolsItemUnit

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
