# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .commodity_symbols_v2_response_symbols_item import CommoditySymbolsV2ResponseSymbolsItem


class CommoditySymbolsV2Response(UniversalBaseModel):
    success: bool = pydantic.Field()
    """
    API request success indicator. "true" for successful requests.
    """

    symbols: typing.List[CommoditySymbolsV2ResponseSymbolsItem] = pydantic.Field()
    """
    An array of commodity symbol objects.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
