# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata


class CommodityFluctuationResponseRatesValue(UniversalBaseModel):
    start_rate: typing_extensions.Annotated[
        float,
        FieldMetadata(alias="startRate"),
        pydantic.Field(alias="startRate", description="The price of the commodity on the start date of the interval."),
    ]
    end_rate: typing_extensions.Annotated[
        float,
        FieldMetadata(alias="endRate"),
        pydantic.Field(alias="endRate", description="The price of the commodity on the end date of the interval."),
    ]
    change: float = pydantic.Field()
    """
    The absolute price difference between the end and start date. May be positive or negative.
    """

    change_percent: typing_extensions.Annotated[
        float,
        FieldMetadata(alias="changePercent"),
        pydantic.Field(
            alias="changePercent",
            description="The percentage change in price from start to end date. May be positive or negative.",
        ),
    ]

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
