# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class CommodityHistoricalRatesV2ResponseRatesValue(UniversalBaseModel):
    date: str = pydantic.Field()
    """
    Date for which prices were fetched (YYYY-MM-DD). May differ from the requested date when the API falls back to the last available rate before it, or snaps to the first day of the month for monthly-updated commodities.
    """

    open: float = pydantic.Field()
    """
    Opening price on the given date. 0 for monthly-updated commodities.
    """

    high: float = pydantic.Field()
    """
    Highest price recorded on the given date. 0 for monthly-updated commodities.
    """

    low: float = pydantic.Field()
    """
    Lowest price recorded on the given date. 0 for monthly-updated commodities.
    """

    close: float = pydantic.Field()
    """
    Closing price on the given date.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
