# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .commodity_time_series_response_metadata_value import CommodityTimeSeriesResponseMetadataValue
from .commodity_time_series_response_rates_value_value import CommodityTimeSeriesResponseRatesValueValue


class CommodityTimeSeriesResponse(UniversalBaseModel):
    success: bool = pydantic.Field()
    """
    API request success indicator. "true" for successful requests.
    """

    timestamp: typing.Optional[float] = pydantic.Field(default=None)
    """
    Unix timestamp indicating when the response was generated.
    """

    metadata: typing.Optional[typing.Dict[str, CommodityTimeSeriesResponseMetadataValue]] = pydantic.Field(default=None)
    """
    Map containing detailed information for all the requested commodities keyed by commodity symbol.
    """

    start_date: typing_extensions.Annotated[
        str,
        FieldMetadata(alias="startDate"),
        pydantic.Field(alias="startDate", description="The start date of the time series data in YYYY-MM-DD format."),
    ]
    end_date: typing_extensions.Annotated[
        str,
        FieldMetadata(alias="endDate"),
        pydantic.Field(alias="endDate", description="The end date of the time series data in YYYY-MM-DD format."),
    ]
    rates: typing.Dict[str, typing.Dict[str, CommodityTimeSeriesResponseRatesValueValue]] = pydantic.Field()
    """
    Date-indexed map; each key is a date (YYYY-MM-DD) whose value maps commodity symbols to OHLC data.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
