# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class CommodityHistoricalRatesResponseRatesValue(UniversalBaseModel):
    date: str = pydantic.Field()
    """
    Date for which commodity prices were fetched. Format: YYYY-MM-DD.
    """

    open: float = pydantic.Field()
    """
    The opening price of the commodity on the given date.
    """

    high: float = pydantic.Field()
    """
    The highest price of the commodity recorded on the given date.
    """

    low: float = pydantic.Field()
    """
    The lowest price of the commodity recorded on the given date.
    """

    close: float = pydantic.Field()
    """
    The closing price of the commodity on the given date.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
