# This file was auto-generated by Fern from our API Definition.

import typing

CommoditySymbolsResponseSymbolsItemUpdateInterval = typing.Union[typing.Literal["PER_SECOND", "PER_MINUTE"], typing.Any]
