# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .commodity_symbols_v2_response_symbols_item_currency import CommoditySymbolsV2ResponseSymbolsItemCurrency
from .commodity_symbols_v2_response_symbols_item_status import CommoditySymbolsV2ResponseSymbolsItemStatus
from .commodity_symbols_v2_response_symbols_item_unit import CommoditySymbolsV2ResponseSymbolsItemUnit
from .commodity_symbols_v2_response_symbols_item_update_interval import (
    CommoditySymbolsV2ResponseSymbolsItemUpdateInterval,
)


class CommoditySymbolsV2ResponseSymbolsItem(UniversalBaseModel):
    symbol: str = pydantic.Field()
    """
    Unique identifier/ticker symbol for the commodity (e.g., XAU, NG-FUT). Use this value in the symbols parameter of the rate endpoints.
    """

    name: str = pydantic.Field()
    """
    Full name of the commodity (e.g., Gold, Natural Gas Futures).
    """

    description: typing.Optional[str] = pydantic.Field(default=None)
    """
    Short description of the commodity. May be an empty string for some symbols.
    """

    category: str = pydantic.Field()
    """
    Category the commodity belongs to (e.g., Metals, Energy, Agriculture, Industrial, Raw Materials, Oils and Meals, Textiles, Meats, Poultry, Livestock).
    """

    status: CommoditySymbolsV2ResponseSymbolsItemStatus = pydantic.Field()
    """
    Current status of the commodity. "inactive" means the symbol is deprecated - latest rates are unavailable, but historical rates remain available up to its deprecationDate.
    """

    update_interval: typing_extensions.Annotated[
        CommoditySymbolsV2ResponseSymbolsItemUpdateInterval,
        FieldMetadata(alias="updateInterval"),
        pydantic.Field(alias="updateInterval", description="The rate at which this commodity's price is updated."),
    ]
    """
    The rate at which this commodity's price is updated.
    """

    exchange: typing.Optional[str] = pydantic.Field(default=None)
    """
    Data source for the symbol (e.g., World Bank). Present only for some symbols.
    """

    deprecation_date: typing_extensions.Annotated[
        typing.Optional[dt.date],
        FieldMetadata(alias="deprecationDate"),
        pydantic.Field(
            alias="deprecationDate",
            description='Present only when status is "inactive". Date the symbol was deprecated (YYYY-MM-DD).',
        ),
    ] = None
    """
    Present only when status is "inactive". Date the symbol was deprecated (YYYY-MM-DD).
    """

    currency: CommoditySymbolsV2ResponseSymbolsItemCurrency
    unit: CommoditySymbolsV2ResponseSymbolsItemUnit

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
