# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .commodity_time_series_v2_response_rates_value_value import CommodityTimeSeriesV2ResponseRatesValueValue


class CommodityTimeSeriesV2Response(UniversalBaseModel):
    success: bool = pydantic.Field()
    """
    API request success indicator. "true" for successful requests.
    """

    start_date: typing_extensions.Annotated[
        str,
        FieldMetadata(alias="startDate"),
        pydantic.Field(alias="startDate", description="The start date of the time series data in YYYY-MM-DD format."),
    ]
    """
    The start date of the time series data in YYYY-MM-DD format.
    """

    end_date: typing_extensions.Annotated[
        str,
        FieldMetadata(alias="endDate"),
        pydantic.Field(alias="endDate", description="The end date of the time series data in YYYY-MM-DD format."),
    ]
    """
    The end date of the time series data in YYYY-MM-DD format.
    """

    rates: typing.Dict[str, typing.Dict[str, CommodityTimeSeriesV2ResponseRatesValueValue]] = pydantic.Field()
    """
    Map of trading dates (YYYY-MM-DD) to per-symbol OHLC data. Non-trading days are excluded.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
