# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .commodity_time_series_response_metadata_value import CommodityTimeSeriesResponseMetadataValue


class CommodityTimeSeriesResponse(UniversalBaseModel):
    success: bool = pydantic.Field()
    """
    API request success indicator. 'true' for successful requests.
    """

    timestamp: float = pydantic.Field()
    """
    Unix timestamp indicating when the response was generated.
    """

    rates: typing.Dict[str, float] = pydantic.Field()
    """
    Map containing rate data for all the requested commodities.
    """

    metadata: typing.Dict[str, CommodityTimeSeriesResponseMetadataValue] = pydantic.Field()
    """
    Map containing detailed information for all the requested commodities keyed by commodity symbol.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
