# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .commodity_symbols_response_symbols_item import CommoditySymbolsResponseSymbolsItem


class CommoditySymbolsResponse(UniversalBaseModel):
    success: bool = pydantic.Field()
    """
    Indicates whether the API request was successful.
    """

    symbols: typing.List[CommoditySymbolsResponseSymbolsItem] = pydantic.Field()
    """
    An array of commodity symbol objects.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
