# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .commodity_latest_rates_v2_response_metadata_value import CommodityLatestRatesV2ResponseMetadataValue


class CommodityLatestRatesV2Response(UniversalBaseModel):
    success: bool = pydantic.Field()
    """
    API request success indicator. "true" for successful requests.
    """

    timestamp: int = pydantic.Field()
    """
    Unix timestamp (seconds) indicating when the response was generated.
    """

    rates: typing.Dict[str, float] = pydantic.Field()
    """
    Map of requested commodity symbols to their current live price.
    """

    metadata: typing.Dict[str, CommodityLatestRatesV2ResponseMetadataValue] = pydantic.Field()
    """
    Map containing unit and quote currency metadata for all requested commodities, keyed by commodity symbol.
    """

    warning: typing.Optional[str] = pydantic.Field(default=None)
    """
    Present only when currency conversion for the requested `quote` is temporarily unavailable; rates are returned in each commodity's default currency instead.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
