# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata


class CommodityFluctuationV2ResponseRatesValue(UniversalBaseModel):
    start_rate: typing_extensions.Annotated[
        float,
        FieldMetadata(alias="startRate"),
        pydantic.Field(alias="startRate", description="Price of the commodity on the start date."),
    ]
    """
    Price of the commodity on the start date.
    """

    end_rate: typing_extensions.Annotated[
        float,
        FieldMetadata(alias="endRate"),
        pydantic.Field(alias="endRate", description="Price of the commodity on the end date."),
    ]
    """
    Price of the commodity on the end date.
    """

    change: float = pydantic.Field()
    """
    Absolute price difference between end and start dates. May be negative.
    """

    change_percent: typing_extensions.Annotated[
        float,
        FieldMetadata(alias="changePercent"),
        pydantic.Field(
            alias="changePercent", description="Percentage price change from start to end date. May be negative."
        ),
    ]
    """
    Percentage price change from start to end date. May be negative.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
