# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .commodity_historical_rates_response_metadata_value import CommodityHistoricalRatesResponseMetadataValue
from .commodity_historical_rates_response_rates_value import CommodityHistoricalRatesResponseRatesValue


class CommodityHistoricalRatesResponse(UniversalBaseModel):
    success: bool = pydantic.Field()
    """
    API request success indicator. "true" for successful requests.
    """

    timestamp: typing.Optional[float] = pydantic.Field(default=None)
    """
    Unix timestamp indicating when the response was generated.
    """

    metadata: typing.Optional[typing.Dict[str, CommodityHistoricalRatesResponseMetadataValue]] = pydantic.Field(
        default=None
    )
    """
    Map containing detailed information for all the requested commodities keyed by commodity symbol.
    """

    date: str = pydantic.Field()
    """
    Date for which the user requested the commodity price. Format: YYYY-MM-DD.
    """

    rates: typing.Dict[str, CommodityHistoricalRatesResponseRatesValue] = pydantic.Field()
    """
    Map containing rate data for each available requested commodity symbol, keyed by symbol.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
