# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class CurrencyHistoricalRatesResponse(UniversalBaseModel):
    date: str = pydantic.Field()
    """
    For the latest currencies exchange rates endpoint, it is the date and time with timezone (UTC) at which these rates were recorded. For historical currencies exchange rates endpoint, it is the specific date in YYYY-MM-DD format.
    """

    base: str = pydantic.Field()
    """
    Base currency used for calculating exchange rates.
    """

    rates: typing.Dict[str, str] = pydantic.Field()
    """
    A map of currency codes to their exchange rate against the base currency.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
