# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata


class CurrencyFluctuationResponseRateFluctuationsValue(UniversalBaseModel):
    start_rate: typing_extensions.Annotated[
        str,
        FieldMetadata(alias="startRate"),
        pydantic.Field(alias="startRate", description="Starting rate of the currency during the interval."),
    ]
    end_rate: typing_extensions.Annotated[
        str,
        FieldMetadata(alias="endRate"),
        pydantic.Field(alias="endRate", description="Ending rate of the currency during the interval."),
    ]
    change: str = pydantic.Field()
    """
    Absolute change in currency rate over the interval.
    """

    percent_change: typing_extensions.Annotated[
        str,
        FieldMetadata(alias="percentChange"),
        pydantic.Field(alias="percentChange", description="Percentage change in currency rate over the interval."),
    ]

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
