# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .current_weather_response_current import CurrentWeatherResponseCurrent
from .current_weather_response_location import CurrentWeatherResponseLocation


class CurrentWeatherResponse(UniversalBaseModel):
    location: CurrentWeatherResponseLocation = pydantic.Field()
    """
    Location information
    """

    current: CurrentWeatherResponseCurrent = pydantic.Field()
    """
    Current weather data
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
