# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata


class CurrencyConvertHistoricalResponse(UniversalBaseModel):
    date: str = pydantic.Field()
    """
    For the latest rates converter, it is the date and time with timezone (UTC) when the rate was recorded. For historical converter, it is the date provided in the input (format: YYYY-MM-DD).
    """

    from_: typing_extensions.Annotated[
        str,
        FieldMetadata(alias="from"),
        pydantic.Field(alias="from", description="Base currency code (the currency being converted from)."),
    ]
    to: str = pydantic.Field()
    """
    Desired currency code (the currency to convert to).
    """

    rate: str = pydantic.Field()
    """
    Conversion rate from base currency to desired currency.
    """

    given_amount: typing_extensions.Annotated[
        str,
        FieldMetadata(alias="givenAmount"),
        pydantic.Field(alias="givenAmount", description="The amount in base currency to be converted."),
    ]
    converted_amount: typing_extensions.Annotated[
        str,
        FieldMetadata(alias="convertedAmount"),
        pydantic.Field(alias="convertedAmount", description="The result of the conversion in the desired currency."),
    ]

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
