# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .currency_time_series_response_historical_rates_list_item import CurrencyTimeSeriesResponseHistoricalRatesListItem


class CurrencyTimeSeriesResponse(UniversalBaseModel):
    start_date: typing_extensions.Annotated[
        str,
        FieldMetadata(alias="startDate"),
        pydantic.Field(alias="startDate", description="Starting date of the interval (provided via input)."),
    ]
    end_date: typing_extensions.Annotated[
        str,
        FieldMetadata(alias="endDate"),
        pydantic.Field(alias="endDate", description="Ending date of the interval (provided via input)."),
    ]
    base: str = pydantic.Field()
    """
    Base currency with respect to which all rates are calculated.
    """

    historical_rates_list: typing_extensions.Annotated[
        typing.List[CurrencyTimeSeriesResponseHistoricalRatesListItem],
        FieldMetadata(alias="historicalRatesList"),
        pydantic.Field(
            alias="historicalRatesList", description="List of historical exchange rates within the specified interval."
        ),
    ]

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
