# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata


class CurrencyConvertByIpResponse(UniversalBaseModel):
    date: str = pydantic.Field()
    """
    Date and time with timezone (UTC) representing the exact time at which the conversion rate was recorded.
    """

    from_: typing_extensions.Annotated[
        str,
        FieldMetadata(alias="from"),
        pydantic.Field(alias="from", description="Base currency code whose amount will be converted."),
    ]
    to: str = pydantic.Field()
    """
    Desired currency code for the converted amount.
    """

    rate: str = pydantic.Field()
    """
    Current conversion rate with the base currency as the desired converted currency and the quote currency as the 'from' currency code.
    """

    ip_address: typing_extensions.Annotated[
        str,
        FieldMetadata(alias="ipAddress"),
        pydantic.Field(
            alias="ipAddress",
            description="IP Address whose country's currency will be extracted and used as 'to'. Defaults to the request IP if not provided.",
        ),
    ]
    given_amount: typing_extensions.Annotated[
        str,
        FieldMetadata(alias="givenAmount"),
        pydantic.Field(alias="givenAmount", description="The amount to be converted."),
    ]
    converted_amount: typing_extensions.Annotated[
        str,
        FieldMetadata(alias="convertedAmount"),
        pydantic.Field(alias="convertedAmount", description="Converted amount in the desired currency."),
    ]

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
