# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .current_weather_response_current_air_quality import CurrentWeatherResponseCurrentAirQuality
from .current_weather_response_current_astronomy import CurrentWeatherResponseCurrentAstronomy


class CurrentWeatherResponseCurrent(UniversalBaseModel):
    """
    Current weather data
    """

    timestamp: dt.datetime = pydantic.Field()
    """
    ISO 8601 formatted timestamp of the current weather observation.
    """

    temperature2m: typing_extensions.Annotated[
        float,
        FieldMetadata(alias="temperature_2m"),
        pydantic.Field(
            alias="temperature_2m", description="Current air temperature (°C) measured at 2 meters above ground."
        ),
    ]
    relative_humidity2m: typing_extensions.Annotated[
        float,
        FieldMetadata(alias="relative_humidity_2m"),
        pydantic.Field(
            alias="relative_humidity_2m", description="Current relative humidity percentage at 2 meters above ground."
        ),
    ]
    apparent_temperature: float = pydantic.Field()
    """
    Current apparent temperature (°C) accounting for wind chill and humidity.
    """

    snowfall: float = pydantic.Field()
    """
    Current snowfall accumulation in centimeters.
    """

    rain: float = pydantic.Field()
    """
    Current rainfall accumulation in millimeters.
    """

    showers: float = pydantic.Field()
    """
    Current shower precipitation in millimeters.
    """

    precipitation: float = pydantic.Field()
    """
    Total precipitation (mm) including rain, showers, and snowfall.
    """

    weather_code: int = pydantic.Field()
    """
    WMO weather condition code representing current conditions. Supported codes: 0 clear sky; 1, 2, 3 varying cloud cover; 45, 48 fog; 51, 53, 55 drizzle; 56, 57 freezing drizzle; 61, 63, 65 rain; 66, 67 freezing rain; 71, 73, 75 snowfall; 77 snow grains; 80, 81, 82 rain showers; 85, 86 snow showers; 95 thunderstorm; 96, 99 thunderstorm with hail.
    """

    cloud_cover: float = pydantic.Field()
    """
    Current percentage of sky covered by clouds.
    """

    pressure_msl: float = pydantic.Field()
    """
    Current atmospheric pressure (hPa) adjusted to mean sea level.
    """

    surface_pressure: float = pydantic.Field()
    """
    Current atmospheric pressure (hPa) at surface level.
    """

    wind_speed10m: typing_extensions.Annotated[
        float,
        FieldMetadata(alias="wind_speed_10m"),
        pydantic.Field(alias="wind_speed_10m", description="Current wind speed (km/h) at 10 meters above ground."),
    ]
    wind_direction10m: typing_extensions.Annotated[
        int,
        FieldMetadata(alias="wind_direction_10m"),
        pydantic.Field(
            alias="wind_direction_10m", description="Current wind direction in degrees at 10 meters above ground."
        ),
    ]
    wind_gusts10m: typing_extensions.Annotated[
        float,
        FieldMetadata(alias="wind_gusts_10m"),
        pydantic.Field(alias="wind_gusts_10m", description="Current wind gust speed (km/h) at 10 meters above ground."),
    ]
    astronomy: CurrentWeatherResponseCurrentAstronomy = pydantic.Field()
    """
    Astronomical information including sunrise, sunset, and moon phases for the current date.
    """

    air_quality: CurrentWeatherResponseCurrentAirQuality = pydantic.Field()
    """
    Air quality metrics including pollutant concentrations and AQI values.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
