# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .domain_ssl_lookup_response_ssl_certificates_item_extensions import (
    DomainSslLookupResponseSslCertificatesItemExtensions,
)
from .domain_ssl_lookup_response_ssl_certificates_item_issuer import DomainSslLookupResponseSslCertificatesItemIssuer
from .domain_ssl_lookup_response_ssl_certificates_item_public_key import (
    DomainSslLookupResponseSslCertificatesItemPublicKey,
)
from .domain_ssl_lookup_response_ssl_certificates_item_subject import DomainSslLookupResponseSslCertificatesItemSubject


class DomainSslLookupResponseSslCertificatesItem(UniversalBaseModel):
    chain_order: typing_extensions.Annotated[str, FieldMetadata(alias="chainOrder"), pydantic.Field(alias="chainOrder")]
    authentication_type: typing_extensions.Annotated[
        str, FieldMetadata(alias="authenticationType"), pydantic.Field(alias="authenticationType")
    ]
    validity_start_date: typing_extensions.Annotated[
        str, FieldMetadata(alias="validityStartDate"), pydantic.Field(alias="validityStartDate")
    ]
    validity_end_date: typing_extensions.Annotated[
        str, FieldMetadata(alias="validityEndDate"), pydantic.Field(alias="validityEndDate")
    ]
    serial_number: typing_extensions.Annotated[
        str, FieldMetadata(alias="serialNumber"), pydantic.Field(alias="serialNumber")
    ]
    signature_algorithm: typing_extensions.Annotated[
        str, FieldMetadata(alias="signatureAlgorithm"), pydantic.Field(alias="signatureAlgorithm")
    ]
    subject: DomainSslLookupResponseSslCertificatesItemSubject
    issuer: DomainSslLookupResponseSslCertificatesItemIssuer
    public_key: typing_extensions.Annotated[
        DomainSslLookupResponseSslCertificatesItemPublicKey,
        FieldMetadata(alias="publicKey"),
        pydantic.Field(alias="publicKey"),
    ]
    extensions: DomainSslLookupResponseSslCertificatesItemExtensions
    pem_raw: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="pemRaw"),
        pydantic.Field(alias="pemRaw", description="Raw certificate in PEM format"),
    ] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
