# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class DomainReputationResponseEvidenceSummary(UniversalBaseModel):
    """
    Summary of reasons behind the risk assessment.
    """

    why_flagged: typing.List[str] = pydantic.Field()
    """
    List of reasons why the domain was flagged. Empty for a clean domain.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
