# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .domain_whois_lookup_v2_response_registry_data_domain_registered import (
    DomainWhoisLookupV2ResponseRegistryDataDomainRegistered,
)
from .domain_whois_lookup_v2_response_registry_data_domain_registrar import (
    DomainWhoisLookupV2ResponseRegistryDataDomainRegistrar,
)


class DomainWhoisLookupV2ResponseRegistryData(UniversalBaseModel):
    """
    Registry-level (as opposed to registrar-level) WHOIS data, sourced directly from the TLD registry.
    """

    domain_name: typing.Optional[str] = pydantic.Field(default=None)
    """
    Domain name as recorded by the registry.
    """

    query_time: typing.Optional[str] = pydantic.Field(default=None)
    """
    Timestamp when the registry-level record was queried (format YYYY-MM-DD HH:mm:ss, not ISO 8601).
    """

    whois_server: typing.Optional[str] = pydantic.Field(default=None)
    """
    Registry WHOIS server that returned this data.
    """

    domain_registered: typing.Optional[DomainWhoisLookupV2ResponseRegistryDataDomainRegistered] = pydantic.Field(
        default=None
    )
    """
    Domain registration status as recorded by the registry.
    """

    create_date: typing.Optional[dt.date] = pydantic.Field(default=None)
    """
    Domain creation date as recorded by the registry.
    """

    update_date: typing.Optional[dt.date] = pydantic.Field(default=None)
    """
    Domain last-updated date as recorded by the registry.
    """

    expiry_date: typing.Optional[dt.date] = pydantic.Field(default=None)
    """
    Domain expiry date as recorded by the registry.
    """

    name_servers: typing.Optional[typing.List[str]] = pydantic.Field(default=None)
    """
    Name servers as recorded by the registry.
    """

    domain_status: typing.Optional[typing.List[str]] = pydantic.Field(default=None)
    """
    EPP domain status codes as recorded by the registry.
    """

    whois_raw_registery: typing.Optional[str] = pydantic.Field(default=None)
    """
    Raw WHOIS text as returned directly by the registry server.
    """

    domain_registrar: typing.Optional[DomainWhoisLookupV2ResponseRegistryDataDomainRegistrar] = pydantic.Field(
        default=None
    )
    """
    Registrar of record for a domain, as published by either the registrar or the registry.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
