# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class DomainWhoisLookupV2ResponseEligibilityInfo(UniversalBaseModel):
    """
    Domain eligibility information (populated for TLDs with registrant eligibility requirements, e.g. .eu).
    """

    id: typing.Optional[str] = pydantic.Field(default=None)
    """
    Eligibility ID.
    """

    name: typing.Optional[str] = pydantic.Field(default=None)
    """
    Eligibility name.
    """

    type: typing.Optional[str] = pydantic.Field(default=None)
    """
    Eligibility type.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
