# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class DomainReputationResponseEmailDeliverabilityIssuesItem(UniversalBaseModel):
    """
    A detected email deliverability issue or misconfiguration.
    """

    code: typing.Optional[str] = pydantic.Field(default=None)
    """
    Machine-readable code identifying the specific deliverability issue.
    """

    severity: typing.Optional[str] = pydantic.Field(default=None)
    """
    Severity level assigned to the detected issue.
    """

    message: typing.Optional[str] = pydantic.Field(default=None)
    """
    Human-readable explanation of the issue.
    """

    recommendation: typing.Optional[str] = pydantic.Field(default=None)
    """
    Plain-language description of the exact fix to apply.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
