# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .domain_ssl_lookup_response_ssl_certificates_item_extensions_authority_info_access import (
    DomainSslLookupResponseSslCertificatesItemExtensionsAuthorityInfoAccess,
)
from .domain_ssl_lookup_response_ssl_certificates_item_extensions_certificate_policies import (
    DomainSslLookupResponseSslCertificatesItemExtensionsCertificatePolicies,
)
from .domain_ssl_lookup_response_ssl_certificates_item_extensions_subject_alternative_names import (
    DomainSslLookupResponseSslCertificatesItemExtensionsSubjectAlternativeNames,
)


class DomainSslLookupResponseSslCertificatesItemExtensions(UniversalBaseModel):
    authority_key_identifier: typing_extensions.Annotated[
        str, FieldMetadata(alias="authorityKeyIdentifier"), pydantic.Field(alias="authorityKeyIdentifier")
    ]
    subject_key_identifier: typing_extensions.Annotated[
        str, FieldMetadata(alias="subjectKeyIdentifier"), pydantic.Field(alias="subjectKeyIdentifier")
    ]
    key_usages: typing_extensions.Annotated[
        typing.List[str], FieldMetadata(alias="keyUsages"), pydantic.Field(alias="keyUsages")
    ]
    extended_key_usages: typing_extensions.Annotated[
        typing.List[str], FieldMetadata(alias="extendedKeyUsages"), pydantic.Field(alias="extendedKeyUsages")
    ]
    crl_distribution_points: typing_extensions.Annotated[
        typing.Optional[typing.List[str]],
        FieldMetadata(alias="crlDistributionPoints"),
        pydantic.Field(alias="crlDistributionPoints"),
    ] = None
    authority_info_access: typing_extensions.Annotated[
        DomainSslLookupResponseSslCertificatesItemExtensionsAuthorityInfoAccess,
        FieldMetadata(alias="authorityInfoAccess"),
        pydantic.Field(alias="authorityInfoAccess"),
    ]
    subject_alternative_names: typing_extensions.Annotated[
        typing.Optional[DomainSslLookupResponseSslCertificatesItemExtensionsSubjectAlternativeNames],
        FieldMetadata(alias="subjectAlternativeNames"),
        pydantic.Field(alias="subjectAlternativeNames"),
    ] = None
    certificate_policies: typing_extensions.Annotated[
        DomainSslLookupResponseSslCertificatesItemExtensionsCertificatePolicies,
        FieldMetadata(alias="certificatePolicies"),
        pydantic.Field(alias="certificatePolicies"),
    ]

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
