# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata


class DomainAvailabilityCheckResponse(UniversalBaseModel):
    domain: str = pydantic.Field()
    """
    Name of the queried domain
    """

    domain_availability: typing_extensions.Annotated[
        bool,
        FieldMetadata(alias="domainAvailability"),
        pydantic.Field(alias="domainAvailability", description="True if available, false if not available"),
    ]

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
