# This file was auto-generated by Fern from our API Definition.

import typing

DomainDnsHistoryResponseHistoricalDnsRecordsItemDnsRecordsItemOneDnsType = typing.Union[
    typing.Literal["CNAME"], typing.Any
]
