# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .domain_availability_suggestions_response_domain_available_response_item import (
    DomainAvailabilitySuggestionsResponseDomainAvailableResponseItem,
)


class DomainAvailabilitySuggestionsResponse(UniversalBaseModel):
    domain_available_response: typing.List[DomainAvailabilitySuggestionsResponseDomainAvailableResponseItem] = (
        pydantic.Field()
    )
    """
    List of domain availability objects.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
