# This file was auto-generated by Fern from our API Definition.

import typing

from .domain_availability_suggestions_response_domain import DomainAvailabilitySuggestionsResponseDomain
from .domain_availability_suggestions_response_domain_available_response import (
    DomainAvailabilitySuggestionsResponseDomainAvailableResponse,
)

DomainAvailabilitySuggestionsResponse = typing.Union[
    DomainAvailabilitySuggestionsResponseDomain, DomainAvailabilitySuggestionsResponseDomainAvailableResponse
]
