# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .domain_reputation_response_email_deliverability_authentication_dkim import (
    DomainReputationResponseEmailDeliverabilityAuthenticationDkim,
)
from .domain_reputation_response_email_deliverability_authentication_dmarc import (
    DomainReputationResponseEmailDeliverabilityAuthenticationDmarc,
)
from .domain_reputation_response_email_deliverability_authentication_spf import (
    DomainReputationResponseEmailDeliverabilityAuthenticationSpf,
)


class DomainReputationResponseEmailDeliverabilityAuthentication(UniversalBaseModel):
    """
    Email authentication mechanisms configured for the domain.
    """

    spf: DomainReputationResponseEmailDeliverabilityAuthenticationSpf = pydantic.Field()
    """
    Sender Policy Framework configuration.
    """

    dkim: DomainReputationResponseEmailDeliverabilityAuthenticationDkim = pydantic.Field()
    """
    DomainKeys Identified Mail configuration.
    """

    dmarc: DomainReputationResponseEmailDeliverabilityAuthenticationDmarc = pydantic.Field()
    """
    Domain-based Message Authentication, Reporting and Conformance configuration.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
