# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .domain_reputation_response_intelligence_recommended_action import (
    DomainReputationResponseIntelligenceRecommendedAction,
)
from .domain_reputation_response_intelligence_related_iocs_item import (
    DomainReputationResponseIntelligenceRelatedIocsItem,
)


class DomainReputationResponseIntelligence(UniversalBaseModel):
    """
    Threat intelligence details for the indicator of compromise (IOC).
    """

    ioc_type: str = pydantic.Field()
    """
    Type of the indicator of compromise (e.g. domain).
    """

    ioc_value: str = pydantic.Field()
    """
    Value of the indicator of compromise.
    """

    related_iocs: typing.List[DomainReputationResponseIntelligenceRelatedIocsItem] = pydantic.Field()
    """
    Other IOCs related to this domain.
    """

    feed_tags: typing.List[str] = pydantic.Field()
    """
    Tags associated with this IOC from threat feeds.
    """

    stix_pattern: str = pydantic.Field()
    """
    STIX 2.1 pattern representation of the IOC, ready to wrap into an Indicator object.
    """

    recommended_action: DomainReputationResponseIntelligenceRecommendedAction = pydantic.Field()
    """
    Recommended action based on the assessment.
    """

    first_seen: typing.Optional[str] = pydantic.Field(default=None)
    """
    First time this IOC was observed (YYYY-MM-DDTHH:mm:ssZ). null when never observed on a feed.
    """

    last_seen: typing.Optional[str] = pydantic.Field(default=None)
    """
    Last time this IOC was observed (YYYY-MM-DDTHH:mm:ssZ). null when never observed on a feed.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
