# This file was auto-generated by Fern from our API Definition.

import typing

DomainDnsHistoryResponseHistoricalDnsRecordsItemDnsRecordsItemPriorityDnsType = typing.Union[
    typing.Literal["MX"], typing.Any
]
