# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata


class DomainSslLookupResponseSslCertificatesItemPublicKey(UniversalBaseModel):
    key_size: typing_extensions.Annotated[str, FieldMetadata(alias="keySize"), pydantic.Field(alias="keySize")]
    key_algorithm: typing_extensions.Annotated[
        str, FieldMetadata(alias="keyAlgorithm"), pydantic.Field(alias="keyAlgorithm")
    ]
    pem_raw: typing_extensions.Annotated[str, FieldMetadata(alias="pemRaw"), pydantic.Field(alias="pemRaw")]

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
