# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .domain_reputation_response_trust_signals_signals_negative_item import (
    DomainReputationResponseTrustSignalsSignalsNegativeItem,
)
from .domain_reputation_response_trust_signals_signals_neutral_item import (
    DomainReputationResponseTrustSignalsSignalsNeutralItem,
)
from .domain_reputation_response_trust_signals_signals_positive_item import (
    DomainReputationResponseTrustSignalsSignalsPositiveItem,
)


class DomainReputationResponseTrustSignalsSignals(UniversalBaseModel):
    """
    Signals contributing to the trust score.
    """

    positive: typing.List[DomainReputationResponseTrustSignalsSignalsPositiveItem] = pydantic.Field()
    """
    Signals that positively affect the trust score.
    """

    negative: typing.List[DomainReputationResponseTrustSignalsSignalsNegativeItem] = pydantic.Field()
    """
    Signals that negatively affect the trust score.
    """

    neutral: typing.List[DomainReputationResponseTrustSignalsSignalsNeutralItem] = pydantic.Field()
    """
    Signals that are neutral to the trust score.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
