# This file was auto-generated by Fern from our API Definition.

import typing

DomainDnsReverseRequestType = typing.Union[
    typing.Literal["A", "AAAA", "MX", "NS", "SOA", "SPF", "TXT", "CNAME"], typing.Any
]
