# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .domain_reputation_response_trust_signals_indicators import DomainReputationResponseTrustSignalsIndicators
from .domain_reputation_response_trust_signals_signals import DomainReputationResponseTrustSignalsSignals


class DomainReputationResponseTrustSignals(UniversalBaseModel):
    """
    Trust scoring and supporting signals for the domain.
    """

    trust_score: int = pydantic.Field()
    """
    Overall trust score (0-100).
    """

    trust_band: str = pydantic.Field()
    """
    Trust score band / category (e.g. low, medium, high).
    """

    signals: DomainReputationResponseTrustSignalsSignals = pydantic.Field()
    """
    Signals contributing to the trust score.
    """

    indicators: DomainReputationResponseTrustSignalsIndicators = pydantic.Field()
    """
    Individual trust / risk indicators for the domain.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
