# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class DomainWhoisLookupV2ResponseBillingContact(UniversalBaseModel):
    """
    A contact record (registrant, administrative, technical, billing, or reseller) published in the domain's WHOIS record.
    """

    name: typing.Optional[str] = pydantic.Field(default=None)
    """
    Contact's full name.
    """

    company: typing.Optional[str] = pydantic.Field(default=None)
    """
    Contact's organization or company name.
    """

    street: typing.Optional[str] = pydantic.Field(default=None)
    """
    Street address.
    """

    city: typing.Optional[str] = pydantic.Field(default=None)
    """
    City.
    """

    state: typing.Optional[str] = pydantic.Field(default=None)
    """
    State or province.
    """

    zip_code: typing.Optional[str] = pydantic.Field(default=None)
    """
    Postal/ZIP code.
    """

    country_name: typing.Optional[str] = pydantic.Field(default=None)
    """
    Full country name.
    """

    country_code: typing.Optional[str] = pydantic.Field(default=None)
    """
    ISO 3166-1 alpha-2 country code.
    """

    email_address: typing.Optional[str] = pydantic.Field(default=None)
    """
    Contact email address, or a privacy-service redirect instruction.
    """

    phone: typing.Optional[str] = pydantic.Field(default=None)
    """
    Contact phone number.
    """

    fax: typing.Optional[str] = pydantic.Field(default=None)
    """
    Contact fax number.
    """

    mailing_address: typing.Optional[str] = pydantic.Field(default=None)
    """
    Full combined mailing address, when published as a single string.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
