# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class DomainReputationResponseRiskCategoryPivotMatchesItem(UniversalBaseModel):
    """
    A related pivot linked to known threats.
    """

    pivot: str = pydantic.Field()
    """
    Pivot value (e.g. a nameserver or email address).
    """

    pivot_type: str = pydantic.Field()
    """
    Type of pivot.
    """

    total_related_threats: int = pydantic.Field()
    """
    Total number of threats related to this pivot.
    """

    confidence: float = pydantic.Field()
    """
    Confidence score for the pivot match (0-1).
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
