# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata


class DomainAvailabilitySuggestionsResponseDomainAvailableResponseItem(UniversalBaseModel):
    domain: typing.Optional[str] = None
    domain_availability: typing_extensions.Annotated[
        typing.Optional[bool], FieldMetadata(alias="domainAvailability"), pydantic.Field(alias="domainAvailability")
    ] = None
    message: typing.Optional[str] = pydantic.Field(default=None)
    """
    Extra details if the domain is not registered.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
