# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .domain_ssl_lookup_response_ssl_certificates_item_extensions_certificate_policies_policy_qualifier_user_notice_notice_ref import (
    DomainSslLookupResponseSslCertificatesItemExtensionsCertificatePoliciesPolicyQualifierUserNoticeNoticeRef,
)


class DomainSslLookupResponseSslCertificatesItemExtensionsCertificatePoliciesPolicyQualifierUserNotice(
    UniversalBaseModel
):
    explicit_text: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="explicitText"), pydantic.Field(alias="explicitText")
    ] = None
    notice_ref: typing_extensions.Annotated[
        typing.Optional[
            DomainSslLookupResponseSslCertificatesItemExtensionsCertificatePoliciesPolicyQualifierUserNoticeNoticeRef
        ],
        FieldMetadata(alias="noticeRef"),
        pydantic.Field(alias="noticeRef"),
    ] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
