# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class DomainReputationResponseRiskCategorySourcesItem(UniversalBaseModel):
    """
    A threat intelligence source that flagged the domain.
    """

    source: str = pydantic.Field()
    """
    Name of the threat intelligence source (e.g. Spamhaus).
    """

    indicator: str = pydantic.Field()
    """
    Indicator matched by this source.
    """

    threat_type: str = pydantic.Field()
    """
    Threat type reported by this source.
    """

    confidence: float = pydantic.Field()
    """
    Confidence score from this source (0-1).
    """

    first_seen: str = pydantic.Field()
    """
    First time this indicator was seen by the source (YYYY-MM-DDTHH:mm:ssZ).
    """

    last_seen: str = pydantic.Field()
    """
    Last time this indicator was seen by the source (YYYY-MM-DDTHH:mm:ssZ).
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
