# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class DomainReputationResponseTrustSignalsIndicators(UniversalBaseModel):
    """
    Individual trust / risk indicators for the domain.
    """

    is_newly_registered: typing.Optional[bool] = pydantic.Field(default=None)
    """
    Indicates whether the domain was recently registered. null when WHOIS data is unavailable.
    """

    uses_free_extension: typing.Optional[bool] = pydantic.Field(default=None)
    """
    Indicates whether the domain uses a free TLD extension.
    """

    uses_free_ssl: typing.Optional[bool] = pydantic.Field(default=None)
    """
    Indicates whether the domain uses a free SSL certificate.
    """

    has_privacy_whois: typing.Optional[bool] = pydantic.Field(default=None)
    """
    Indicates whether WHOIS privacy protection is enabled. null when WHOIS data is unavailable.
    """

    ssl_age_days: typing.Optional[int] = pydantic.Field(default=None)
    """
    Age of the SSL certificate in days.
    """

    has_dmarc: typing.Optional[bool] = pydantic.Field(default=None)
    """
    Indicates whether a DMARC record exists.
    """

    has_spf: typing.Optional[bool] = pydantic.Field(default=None)
    """
    Indicates whether an SPF record exists.
    """

    redirects_externally: typing.Optional[bool] = pydantic.Field(default=None)
    """
    Indicates whether the domain redirects to an external site.
    """

    javascript_obfuscated: typing.Optional[bool] = pydantic.Field(default=None)
    """
    Indicates whether obfuscated JavaScript was detected.
    """

    domain_age_days: typing.Optional[int] = pydantic.Field(default=None)
    """
    Age of the domain in days. null when WHOIS data is unavailable.
    """

    registrar: typing.Optional[str] = pydantic.Field(default=None)
    """
    Domain registrar name. null when WHOIS data is unavailable.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
