# This file was auto-generated by Fern from our API Definition.

import typing

DomainDnsReverseResponseReverseDnsRecordsItemDnsRecordsItemAdminDnsType = typing.Union[
    typing.Literal["SOA"], typing.Any
]
