# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata


class DomainSslChainLookupResponseSslCertificatesItemIssuer(UniversalBaseModel):
    common_name: typing_extensions.Annotated[str, FieldMetadata(alias="commonName"), pydantic.Field(alias="commonName")]
    organization: typing.Optional[str] = None
    organizational_unit: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="organizationalUnit"), pydantic.Field(alias="organizationalUnit")
    ] = None
    locality: typing.Optional[str] = None
    state: typing.Optional[str] = None
    country: typing.Optional[str] = None
    inc_country: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="incCountry"), pydantic.Field(alias="incCountry")
    ] = None
    inc_state: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="incState"), pydantic.Field(alias="incState")
    ] = None
    business_category: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="businessCategory"), pydantic.Field(alias="businessCategory")
    ] = None
    street: typing.Optional[str] = None
    postal_code: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="postalCode"), pydantic.Field(alias="postalCode")
    ] = None
    serial_number: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="serialNumber"), pydantic.Field(alias="serialNumber")
    ] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
