# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class DomainWhoisLookupV2ResponseDomainRegistrar(UniversalBaseModel):
    id: typing.Optional[str] = None
    id_type: typing.Optional[str] = None
    iana_id: typing.Optional[str] = None
    registry_id: typing.Optional[str] = None
    handle: typing.Optional[str] = None
    status: typing.Optional[str] = None
    registrar_name: typing.Optional[str] = None
    normalized_name: typing.Optional[str] = None
    whois_server: typing.Optional[str] = None
    rdap_server: typing.Optional[str] = None
    website_url: typing.Optional[str] = None
    email_address: typing.Optional[str] = None
    phone_number: typing.Optional[str] = None
    authoritative_registry_name: typing.Optional[str] = None
    organization_number: typing.Optional[str] = None
    is_sponsor: typing.Optional[bool] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class DomainWhoisLookupV2ResponseResellerContact(UniversalBaseModel):
    name: typing.Optional[str] = None
    email_address: typing.Optional[str] = None
    phone: typing.Optional[str] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class DomainWhoisLookupV2ResponseRegistrantContact(UniversalBaseModel):
    id: typing.Optional[str] = None
    name: typing.Optional[str] = None
    company: typing.Optional[str] = None
    street: typing.Optional[str] = None
    city: typing.Optional[str] = None
    state: typing.Optional[str] = None
    zip_code: typing.Optional[str] = None
    country_name: typing.Optional[str] = None
    country_code: typing.Optional[str] = None
    email_address: typing.Optional[str] = None
    phone: typing.Optional[str] = None
    fax: typing.Optional[str] = None
    mailing_address: typing.Optional[str] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class DomainWhoisLookupV2ResponseAdministrativeContact(UniversalBaseModel):
    id: typing.Optional[str] = None
    name: typing.Optional[str] = None
    company: typing.Optional[str] = None
    street: typing.Optional[str] = None
    city: typing.Optional[str] = None
    state: typing.Optional[str] = None
    zip_code: typing.Optional[str] = None
    country_name: typing.Optional[str] = None
    country_code: typing.Optional[str] = None
    email_address: typing.Optional[str] = None
    phone: typing.Optional[str] = None
    fax: typing.Optional[str] = None
    mailing_address: typing.Optional[str] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class DomainWhoisLookupV2ResponseTechnicalContact(UniversalBaseModel):
    id: typing.Optional[str] = None
    name: typing.Optional[str] = None
    company: typing.Optional[str] = None
    street: typing.Optional[str] = None
    city: typing.Optional[str] = None
    state: typing.Optional[str] = None
    zip_code: typing.Optional[str] = None
    country_name: typing.Optional[str] = None
    country_code: typing.Optional[str] = None
    email_address: typing.Optional[str] = None
    phone: typing.Optional[str] = None
    fax: typing.Optional[str] = None
    mailing_address: typing.Optional[str] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class DomainWhoisLookupV2ResponseBillingContact(UniversalBaseModel):
    id: typing.Optional[str] = None
    name: typing.Optional[str] = None
    company: typing.Optional[str] = None
    street: typing.Optional[str] = None
    city: typing.Optional[str] = None
    state: typing.Optional[str] = None
    zip_code: typing.Optional[str] = None
    country_name: typing.Optional[str] = None
    country_code: typing.Optional[str] = None
    email_address: typing.Optional[str] = None
    phone: typing.Optional[str] = None
    fax: typing.Optional[str] = None
    mailing_address: typing.Optional[str] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class DomainWhoisLookupV2ResponseEligibilityInfo(UniversalBaseModel):
    id: typing.Optional[str] = None
    name: typing.Optional[str] = None
    type: typing.Optional[str] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class DomainWhoisLookupV2ResponseAbuseContact(UniversalBaseModel):
    email_address: typing.Optional[str] = None
    phone_number: typing.Optional[str] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class DomainWhoisLookupV2ResponseRegistryDataDomainRegistrar(UniversalBaseModel):
    id: typing.Optional[str] = None
    id_type: typing.Optional[str] = None
    iana_id: typing.Optional[str] = None
    registry_id: typing.Optional[str] = None
    handle: typing.Optional[str] = None
    status: typing.Optional[str] = None
    registrar_name: typing.Optional[str] = None
    normalized_name: typing.Optional[str] = None
    whois_server: typing.Optional[str] = None
    rdap_server: typing.Optional[str] = None
    website_url: typing.Optional[str] = None
    email_address: typing.Optional[str] = None
    phone_number: typing.Optional[str] = None
    authoritative_registry_name: typing.Optional[str] = None
    organization_number: typing.Optional[str] = None
    is_sponsor: typing.Optional[bool] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class DomainWhoisLookupV2ResponseRegistryData(UniversalBaseModel):
    domain_name: typing.Optional[str] = None
    query_time: typing.Optional[dt.datetime] = None
    whois_server: typing.Optional[str] = None
    create_date: typing.Optional[dt.date] = None
    update_date: typing.Optional[dt.date] = None
    expiry_date: typing.Optional[dt.date] = None
    domain_registrar: typing.Optional[DomainWhoisLookupV2ResponseRegistryDataDomainRegistrar] = None
    name_servers: typing.Optional[typing.List[str]] = None
    domain_status: typing.Optional[typing.List[str]] = None
    whois_raw_registry: typing.Optional[str] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class DomainWhoisLookupV2Response(UniversalBaseModel):
    status: typing.Optional[bool] = None
    domain_name: typing.Optional[str] = None
    query_time: typing.Optional[dt.datetime] = None
    whois_server: typing.Optional[str] = None
    domain_registered: typing.Optional[str] = None
    secure_dns: typing.Optional[bool] = None
    domain_handle: typing.Optional[str] = None
    create_date: typing.Optional[dt.date] = None
    update_date: typing.Optional[dt.date] = None
    expiry_date: typing.Optional[dt.date] = None
    domain_registrar: typing.Optional[DomainWhoisLookupV2ResponseDomainRegistrar] = None
    reseller_contact: typing.Optional[DomainWhoisLookupV2ResponseResellerContact] = None
    registrant_contact: typing.Optional[DomainWhoisLookupV2ResponseRegistrantContact] = None
    administrative_contact: typing.Optional[DomainWhoisLookupV2ResponseAdministrativeContact] = None
    technical_contact: typing.Optional[DomainWhoisLookupV2ResponseTechnicalContact] = None
    billing_contact: typing.Optional[DomainWhoisLookupV2ResponseBillingContact] = None
    eligibility_info: typing.Optional[DomainWhoisLookupV2ResponseEligibilityInfo] = None
    abuse_contact: typing.Optional[DomainWhoisLookupV2ResponseAbuseContact] = None
    name_servers: typing.Optional[typing.List[str]] = None
    domain_status: typing.Optional[typing.List[str]] = None
    whois_raw_domain: typing.Optional[str] = None
    registry_data: typing.Optional[DomainWhoisLookupV2ResponseRegistryData] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
