# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .domain_reputation_response_email_deliverability_authentication import (
    DomainReputationResponseEmailDeliverabilityAuthentication,
)
from .domain_reputation_response_email_deliverability_infrastructure import (
    DomainReputationResponseEmailDeliverabilityInfrastructure,
)
from .domain_reputation_response_email_deliverability_issues_item import (
    DomainReputationResponseEmailDeliverabilityIssuesItem,
)
from .domain_reputation_response_email_deliverability_reputation import (
    DomainReputationResponseEmailDeliverabilityReputation,
)


class DomainReputationResponseEmailDeliverability(UniversalBaseModel):
    """
    Assessment of the domain's ability to send and receive email reliably.
    """

    score: int = pydantic.Field()
    """
    Overall email deliverability score out of 100.
    """

    grade: str = pydantic.Field()
    """
    Letter / word grade summarizing the deliverability score.
    """

    can_receive_email: bool = pydantic.Field()
    """
    Indicates whether the domain is configured to receive email.
    """

    authentication: DomainReputationResponseEmailDeliverabilityAuthentication = pydantic.Field()
    """
    Email authentication mechanisms configured for the domain.
    """

    infrastructure: DomainReputationResponseEmailDeliverabilityInfrastructure = pydantic.Field()
    """
    Mail server infrastructure backing the domain.
    """

    reputation: DomainReputationResponseEmailDeliverabilityReputation = pydantic.Field()
    """
    Reputation and trust signals related to the domain's email sending history.
    """

    issues: typing.List[DomainReputationResponseEmailDeliverabilityIssuesItem] = pydantic.Field()
    """
    List of detected email deliverability issues or misconfigurations.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
