# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .domain_typosquatting_response_domains_item import DomainTyposquattingResponseDomainsItem


class DomainTyposquattingResponse(UniversalBaseModel):
    status: bool
    total_records: typing_extensions.Annotated[
        int, FieldMetadata(alias="totalRecords"), pydantic.Field(alias="totalRecords")
    ]
    current_page: typing_extensions.Annotated[
        int, FieldMetadata(alias="currentPage"), pydantic.Field(alias="currentPage")
    ]
    has_next_page: typing_extensions.Annotated[
        bool, FieldMetadata(alias="hasNextPage"), pydantic.Field(alias="hasNextPage")
    ]
    total_pages: typing_extensions.Annotated[int, FieldMetadata(alias="totalPages"), pydantic.Field(alias="totalPages")]
    next_page_token: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="nextPageToken"),
        pydantic.Field(
            alias="nextPageToken",
            description="Opaque token to pass as pageToken on the next request. Present only when hasNextPage is true.",
        ),
    ] = None
    """
    Opaque token to pass as pageToken on the next request. Present only when hasNextPage is true.
    """

    domains: typing.List[DomainTyposquattingResponseDomainsItem]

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
