# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .domain_whois_lookup_response_administrative_contact import DomainWhoisLookupResponseAdministrativeContact
from .domain_whois_lookup_response_billing_contact import DomainWhoisLookupResponseBillingContact
from .domain_whois_lookup_response_domain_registered import DomainWhoisLookupResponseDomainRegistered
from .domain_whois_lookup_response_domain_registrar import DomainWhoisLookupResponseDomainRegistrar
from .domain_whois_lookup_response_registrant_contact import DomainWhoisLookupResponseRegistrantContact
from .domain_whois_lookup_response_registry_data import DomainWhoisLookupResponseRegistryData
from .domain_whois_lookup_response_reseller_contact import DomainWhoisLookupResponseResellerContact
from .domain_whois_lookup_response_technical_contact import DomainWhoisLookupResponseTechnicalContact


class DomainWhoisLookupResponse(UniversalBaseModel):
    status: typing.Optional[bool] = None
    domain_name: typing.Optional[str] = None
    query_time: typing.Optional[dt.datetime] = None
    whois_server: typing.Optional[str] = None
    domain_registered: typing.Optional[DomainWhoisLookupResponseDomainRegistered] = None
    create_date: typing.Optional[dt.date] = None
    update_date: typing.Optional[dt.date] = None
    expiry_date: typing.Optional[dt.date] = None
    domain_registrar: typing.Optional[DomainWhoisLookupResponseDomainRegistrar] = None
    reseller_contact: typing.Optional[DomainWhoisLookupResponseResellerContact] = None
    registrant_contact: typing.Optional[DomainWhoisLookupResponseRegistrantContact] = None
    administrative_contact: typing.Optional[DomainWhoisLookupResponseAdministrativeContact] = None
    technical_contact: typing.Optional[DomainWhoisLookupResponseTechnicalContact] = None
    billing_contact: typing.Optional[DomainWhoisLookupResponseBillingContact] = None
    name_servers: typing.Optional[typing.List[str]] = None
    domain_status: typing.Optional[typing.List[str]] = None
    whois_raw_domain: typing.Optional[str] = None
    registry_data: typing.Optional[DomainWhoisLookupResponseRegistryData] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
