# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .domain_dns_reverse_response_reverse_dns_records_item_dns_records_item import (
    DomainDnsReverseResponseReverseDnsRecordsItemDnsRecordsItem,
)
from .domain_dns_reverse_response_reverse_dns_records_item_dns_types import (
    DomainDnsReverseResponseReverseDnsRecordsItemDnsTypes,
)


class DomainDnsReverseResponseReverseDnsRecordsItem(UniversalBaseModel):
    query_time: typing_extensions.Annotated[
        dt.datetime, FieldMetadata(alias="queryTime"), pydantic.Field(alias="queryTime")
    ]
    domain_name: typing_extensions.Annotated[str, FieldMetadata(alias="domainName"), pydantic.Field(alias="domainName")]
    domain_registered: typing_extensions.Annotated[
        bool, FieldMetadata(alias="domainRegistered"), pydantic.Field(alias="domainRegistered")
    ]
    dns_types: typing_extensions.Annotated[
        DomainDnsReverseResponseReverseDnsRecordsItemDnsTypes,
        FieldMetadata(alias="dnsTypes"),
        pydantic.Field(alias="dnsTypes"),
    ]
    dns_records: typing_extensions.Annotated[
        typing.List[DomainDnsReverseResponseReverseDnsRecordsItemDnsRecordsItem],
        FieldMetadata(alias="dnsRecords"),
        pydantic.Field(alias="dnsRecords"),
    ]

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
