# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .domain_dns_reverse_response_reverse_dns_records_item import DomainDnsReverseResponseReverseDnsRecordsItem


class DomainDnsReverseResponse(UniversalBaseModel):
    total_records: typing_extensions.Annotated[
        int, FieldMetadata(alias="totalRecords"), pydantic.Field(alias="totalRecords")
    ]
    total_pages: typing_extensions.Annotated[int, FieldMetadata(alias="totalPages"), pydantic.Field(alias="totalPages")]
    current_page: typing_extensions.Annotated[
        int, FieldMetadata(alias="currentPage"), pydantic.Field(alias="currentPage")
    ]
    reverse_dns_records: typing_extensions.Annotated[
        typing.List[DomainDnsReverseResponseReverseDnsRecordsItem],
        FieldMetadata(alias="reverseDnsRecords"),
        pydantic.Field(alias="reverseDnsRecords"),
    ]

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
