# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .domain_ssl_lookup_response_ssl_certificates_item import DomainSslLookupResponseSslCertificatesItem


class DomainSslLookupResponse(UniversalBaseModel):
    domain_name: typing_extensions.Annotated[str, FieldMetadata(alias="domainName"), pydantic.Field(alias="domainName")]
    query_time: typing_extensions.Annotated[
        str,
        FieldMetadata(alias="queryTime"),
        pydantic.Field(
            alias="queryTime",
            description="Timestamp when the query was executed (format YYYY-MM-DD HH:mm:ss, not ISO 8601).",
        ),
    ]
    """
    Timestamp when the query was executed (format YYYY-MM-DD HH:mm:ss, not ISO 8601).
    """

    ssl_certificates: typing_extensions.Annotated[
        typing.List[DomainSslLookupResponseSslCertificatesItem],
        FieldMetadata(alias="sslCertificates"),
        pydantic.Field(alias="sslCertificates"),
    ]
    ssl_raw: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="sslRaw"), pydantic.Field(alias="sslRaw")
    ] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
