# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class DomainReputationResponseEmailDeliverabilityReputation(UniversalBaseModel):
    """
    Reputation and trust signals related to the domain's email sending history.
    """

    spam_blacklisted: bool = pydantic.Field()
    """
    Indicates whether the domain appears on known spam blacklists.
    """

    newly_registered: bool = pydantic.Field()
    """
    Indicates whether the domain was registered recently.
    """

    domain_age_days: typing.Optional[int] = pydantic.Field(default=None)
    """
    Age of the domain in days since registration.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
