# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .domain_reputation_response_trust_signals_signals_negative_item_polarity import (
    DomainReputationResponseTrustSignalsSignalsNegativeItemPolarity,
)


class DomainReputationResponseTrustSignalsSignalsNegativeItem(UniversalBaseModel):
    """
    A single trust signal contributing to the trust score.
    """

    code: str = pydantic.Field()
    """
    Signal code identifier (e.g. valid_ssl, dmarc_missing).
    """

    weight: int = pydantic.Field()
    """
    Weight assigned to the signal.
    """

    polarity: DomainReputationResponseTrustSignalsSignalsNegativeItemPolarity = pydantic.Field()
    """
    Polarity of the signal.
    """

    category: str = pydantic.Field()
    """
    Category the signal belongs to (e.g. ssl_certificate).
    """

    evidence: str = pydantic.Field()
    """
    Evidence supporting the signal.
    """

    confidence: float = pydantic.Field()
    """
    Confidence score for the signal (0-1).
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
