# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class DomainReputationResponseEmailDeliverabilityInfrastructure(UniversalBaseModel):
    """
    Mail server infrastructure backing the domain.
    """

    mx_count: int = pydantic.Field()
    """
    Number of MX records found for the domain.
    """

    mx_records: typing.List[str] = pydantic.Field()
    """
    List of mail exchange server hostnames for the domain.
    """

    mx_provider: str = pydantic.Field()
    """
    Email hosting provider inferred from the MX records.
    """

    null_mx: bool = pydantic.Field()
    """
    Indicates whether the domain explicitly declines email via a null MX record.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
