# This file was auto-generated by Fern from our API Definition.

import typing

DomainReputationResponseRiskCategorySeverity = typing.Union[typing.Literal["none", "low", "medium", "high"], typing.Any]
