# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .domain_whois_lookup_v2_response_abuse_contact import DomainWhoisLookupV2ResponseAbuseContact
from .domain_whois_lookup_v2_response_administrative_contact import DomainWhoisLookupV2ResponseAdministrativeContact
from .domain_whois_lookup_v2_response_billing_contact import DomainWhoisLookupV2ResponseBillingContact
from .domain_whois_lookup_v2_response_domain_registered import DomainWhoisLookupV2ResponseDomainRegistered
from .domain_whois_lookup_v2_response_domain_registrar import DomainWhoisLookupV2ResponseDomainRegistrar
from .domain_whois_lookup_v2_response_eligibility_info import DomainWhoisLookupV2ResponseEligibilityInfo
from .domain_whois_lookup_v2_response_registrant_contact import DomainWhoisLookupV2ResponseRegistrantContact
from .domain_whois_lookup_v2_response_registry_data import DomainWhoisLookupV2ResponseRegistryData
from .domain_whois_lookup_v2_response_reseller_contact import DomainWhoisLookupV2ResponseResellerContact
from .domain_whois_lookup_v2_response_technical_contact import DomainWhoisLookupV2ResponseTechnicalContact


class DomainWhoisLookupV2Response(UniversalBaseModel):
    """
    Current WHOIS registration record for the requested domain.
    """

    status: bool = pydantic.Field()
    """
    true if the request was successfully processed.
    """

    domain_name: str = pydantic.Field()
    """
    Domain name that was queried.
    """

    query_time: str = pydantic.Field()
    """
    Timestamp when the WHOIS query was executed.
    """

    whois_server: str = pydantic.Field()
    """
    WHOIS or RDAP server that provided this record.
    """

    domain_registered: DomainWhoisLookupV2ResponseDomainRegistered = pydantic.Field()
    """
    Domain registration status; 'restricted' means the registry withholds registration details.
    """

    secure_dns: typing.Optional[bool] = pydantic.Field(default=None)
    """
    Indicates if DNSSEC or secure DNS is enabled for the domain.
    """

    domain_handle: typing.Optional[str] = pydantic.Field(default=None)
    """
    Internal domain registry handle/ID.
    """

    create_date: typing.Optional[dt.date] = pydantic.Field(default=None)
    """
    Date the domain was originally registered, when the domain is registered.
    """

    update_date: typing.Optional[dt.date] = pydantic.Field(default=None)
    """
    Date the domain registration was last updated, when the domain is registered.
    """

    expiry_date: typing.Optional[dt.date] = pydantic.Field(default=None)
    """
    Date the domain registration is set to expire, when the domain is registered.
    """

    domain_registrar: typing.Optional[DomainWhoisLookupV2ResponseDomainRegistrar] = pydantic.Field(default=None)
    """
    Registrar of record for a domain, as published by either the registrar or the registry.
    """

    reseller_contact: typing.Optional[DomainWhoisLookupV2ResponseResellerContact] = pydantic.Field(default=None)
    """
    A contact record (registrant, administrative, technical, billing, or reseller) published in the domain's WHOIS record.
    """

    registrant_contact: typing.Optional[DomainWhoisLookupV2ResponseRegistrantContact] = pydantic.Field(default=None)
    """
    A contact record (registrant, administrative, technical, billing, or reseller) published in the domain's WHOIS record.
    """

    administrative_contact: typing.Optional[DomainWhoisLookupV2ResponseAdministrativeContact] = pydantic.Field(
        default=None
    )
    """
    A contact record (registrant, administrative, technical, billing, or reseller) published in the domain's WHOIS record.
    """

    technical_contact: typing.Optional[DomainWhoisLookupV2ResponseTechnicalContact] = pydantic.Field(default=None)
    """
    A contact record (registrant, administrative, technical, billing, or reseller) published in the domain's WHOIS record.
    """

    billing_contact: typing.Optional[DomainWhoisLookupV2ResponseBillingContact] = pydantic.Field(default=None)
    """
    A contact record (registrant, administrative, technical, billing, or reseller) published in the domain's WHOIS record.
    """

    abuse_contact: typing.Optional[DomainWhoisLookupV2ResponseAbuseContact] = pydantic.Field(default=None)
    """
    Registrar's abuse-reporting contact.
    """

    eligibility_info: typing.Optional[DomainWhoisLookupV2ResponseEligibilityInfo] = pydantic.Field(default=None)
    """
    Domain eligibility information (populated for TLDs with registrant eligibility requirements, e.g. .eu).
    """

    name_servers: typing.Optional[typing.List[str]] = pydantic.Field(default=None)
    """
    Name servers currently recorded for the domain.
    """

    domain_status: typing.Optional[typing.List[str]] = pydantic.Field(default=None)
    """
    EPP domain status codes currently recorded for the domain.
    """

    whois_raw_domain: typing.Optional[str] = pydantic.Field(default=None)
    """
    Raw WHOIS text as returned by the registrar's WHOIS server.
    """

    registry_data: typing.Optional[DomainWhoisLookupV2ResponseRegistryData] = pydantic.Field(default=None)
    """
    Registry-level (as opposed to registrar-level) WHOIS data, sourced directly from the TLD registry.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
