# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class DomainReputationResponseIntelligenceRelatedIocsItem(UniversalBaseModel):
    """
    A related indicator of compromise.
    """

    type: str = pydantic.Field()
    """
    Type of the related IOC (e.g. ipv4, ipv6).
    """

    value: str = pydantic.Field()
    """
    Value of the related IOC.
    """

    confidence: float = pydantic.Field()
    """
    Confidence score for the related IOC (0-1).
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
