# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .domain_whois_reverse_response_whois_domains_historical_item import (
    DomainWhoisReverseResponseWhoisDomainsHistoricalItem,
)


class DomainWhoisReverseResponse(UniversalBaseModel):
    total_result: typing_extensions.Annotated[
        typing.Optional[int], FieldMetadata(alias="totalResult"), pydantic.Field(alias="totalResult")
    ] = None
    total_pages: typing_extensions.Annotated[
        typing.Optional[int], FieldMetadata(alias="totalPages"), pydantic.Field(alias="totalPages")
    ] = None
    current_page: typing_extensions.Annotated[
        typing.Optional[int], FieldMetadata(alias="currentPage"), pydantic.Field(alias="currentPage")
    ] = None
    whois_domains_historical: typing.Optional[typing.List[DomainWhoisReverseResponseWhoisDomainsHistoricalItem]] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
