# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .domain_whois_history_response_whois_domains_historical_item_administrative_contact import (
    DomainWhoisHistoryResponseWhoisDomainsHistoricalItemAdministrativeContact,
)
from .domain_whois_history_response_whois_domains_historical_item_billing_contact import (
    DomainWhoisHistoryResponseWhoisDomainsHistoricalItemBillingContact,
)
from .domain_whois_history_response_whois_domains_historical_item_domain_registered import (
    DomainWhoisHistoryResponseWhoisDomainsHistoricalItemDomainRegistered,
)
from .domain_whois_history_response_whois_domains_historical_item_domain_registrar import (
    DomainWhoisHistoryResponseWhoisDomainsHistoricalItemDomainRegistrar,
)
from .domain_whois_history_response_whois_domains_historical_item_registrant_contact import (
    DomainWhoisHistoryResponseWhoisDomainsHistoricalItemRegistrantContact,
)
from .domain_whois_history_response_whois_domains_historical_item_registry_data import (
    DomainWhoisHistoryResponseWhoisDomainsHistoricalItemRegistryData,
)
from .domain_whois_history_response_whois_domains_historical_item_reseller_contact import (
    DomainWhoisHistoryResponseWhoisDomainsHistoricalItemResellerContact,
)
from .domain_whois_history_response_whois_domains_historical_item_technical_contact import (
    DomainWhoisHistoryResponseWhoisDomainsHistoricalItemTechnicalContact,
)


class DomainWhoisHistoryResponseWhoisDomainsHistoricalItem(UniversalBaseModel):
    num: int = pydantic.Field()
    """
    Shows the number of the record in the array.
    """

    status: bool = pydantic.Field()
    """
    Always true.
    """

    domain_name: str = pydantic.Field()
    """
    Domain name which was queried.
    """

    query_time: dt.datetime = pydantic.Field()
    """
    The timestamp when the query was made.
    """

    whois_server: str = pydantic.Field()
    """
    The WHOIS server that provided the domain information.
    """

    domain_registered: DomainWhoisHistoryResponseWhoisDomainsHistoricalItemDomainRegistered = pydantic.Field()
    """
    Domain registration status.
    """

    create_date: typing.Optional[dt.date] = pydantic.Field(default=None)
    """
    Date when the domain was initially registered.
    """

    update_date: typing.Optional[dt.date] = pydantic.Field(default=None)
    """
    The date of the most recent update to the domain registration.
    """

    expiry_date: typing.Optional[dt.date] = pydantic.Field(default=None)
    """
    The date when the domain registration will expire if not renewed.
    """

    domain_registrar: typing.Optional[DomainWhoisHistoryResponseWhoisDomainsHistoricalItemDomainRegistrar] = None
    reseller_contact: typing.Optional[DomainWhoisHistoryResponseWhoisDomainsHistoricalItemResellerContact] = None
    registrant_contact: typing.Optional[DomainWhoisHistoryResponseWhoisDomainsHistoricalItemRegistrantContact] = None
    administrative_contact: typing.Optional[
        DomainWhoisHistoryResponseWhoisDomainsHistoricalItemAdministrativeContact
    ] = None
    technical_contact: typing.Optional[DomainWhoisHistoryResponseWhoisDomainsHistoricalItemTechnicalContact] = None
    billing_contact: typing.Optional[DomainWhoisHistoryResponseWhoisDomainsHistoricalItemBillingContact] = None
    name_servers: typing.Optional[typing.List[str]] = None
    domain_status: typing.Optional[typing.List[str]] = None
    whois_raw_domain: typing.Optional[str] = None
    registry_data: typing.Optional[DomainWhoisHistoryResponseWhoisDomainsHistoricalItemRegistryData] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
