# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class DomainReputationResponseEmailDeliverabilityAuthenticationDmarc(UniversalBaseModel):
    """
    Domain-based Message Authentication, Reporting and Conformance configuration.
    """

    present: bool = pydantic.Field()
    """
    Indicates whether a DMARC record was found.
    """

    policy: str = pydantic.Field()
    """
    DMARC enforcement policy applied to failing messages (e.g. none, quarantine, reject).
    """

    reporting_configured: bool = pydantic.Field()
    """
    Indicates whether DMARC aggregate / forensic reporting addresses are configured.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
