# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .domain_ssl_chain_lookup_response_ssl_certificates_item_extensions_certificate_policies_policy_qualifier import (
    DomainSslChainLookupResponseSslCertificatesItemExtensionsCertificatePoliciesPolicyQualifier,
)


class DomainSslChainLookupResponseSslCertificatesItemExtensionsCertificatePolicies(UniversalBaseModel):
    policy_id: typing_extensions.Annotated[str, FieldMetadata(alias="policyId"), pydantic.Field(alias="policyId")]
    policy_qualifier: typing_extensions.Annotated[
        typing.Optional[DomainSslChainLookupResponseSslCertificatesItemExtensionsCertificatePoliciesPolicyQualifier],
        FieldMetadata(alias="policyQualifier"),
        pydantic.Field(alias="policyQualifier"),
    ] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
