# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class DomainWhoisLookupV2ResponseAbuseContact(UniversalBaseModel):
    """
    Registrar's abuse-reporting contact.
    """

    registrar_name: typing.Optional[str] = pydantic.Field(default=None)
    """
    Name of the abuse contact at the registrar.
    """

    email_address: typing.Optional[str] = pydantic.Field(default=None)
    """
    Abuse contact email.
    """

    phone_number: typing.Optional[str] = pydantic.Field(default=None)
    """
    Abuse contact phone.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
