# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class DomainReputationResponseDgaScoreFeatures(UniversalBaseModel):
    """
    Underlying lexical / statistical features used in DGA detection.
    """

    domain_length: int = pydantic.Field()
    """
    Length of the domain name.
    """

    vowel_consonant_ratio: float = pydantic.Field()
    """
    Ratio of vowels to consonants in the domain.
    """

    ngram_perplexity: float = pydantic.Field()
    """
    N-gram perplexity score of the domain string.
    """

    shannon_entropy: float = pydantic.Field()
    """
    Shannon entropy of the domain string.
    """

    digit_letter_ratio: float = pydantic.Field()
    """
    Ratio of digits to letters in the domain.
    """

    consonant_streak_max: int = pydantic.Field()
    """
    Maximum consecutive consonant streak in the domain.
    """

    tld_in_known_dga_set: bool = pydantic.Field()
    """
    Indicates if the TLD belongs to a known DGA set.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
