# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class DomainReputationResponseEmailDeliverabilityAuthenticationDkim(UniversalBaseModel):
    """
    DomainKeys Identified Mail configuration.
    """

    found: bool = pydantic.Field()
    """
    Indicates whether a DKIM record was found for any probed selector.
    """

    selectors_found: typing.List[str] = pydantic.Field()
    """
    List of DKIM selectors for which a record was found.
    """

    providers_detected: typing.List[str] = pydantic.Field()
    """
    Email service providers inferred from the matched DKIM selectors.
    """

    note: str = pydantic.Field()
    """
    Clarifying note about the limitations of DKIM selector probing.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
