# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .domain_dns_lookup_response_dns_records_item_single_name_dns_type import (
    DomainDnsLookupResponseDnsRecordsItemSingleNameDnsType,
)


class DomainDnsLookupResponseDnsRecordsItemSingleName(UniversalBaseModel):
    name: str
    type: int
    dns_type: typing_extensions.Annotated[
        DomainDnsLookupResponseDnsRecordsItemSingleNameDnsType,
        FieldMetadata(alias="dnsType"),
        pydantic.Field(alias="dnsType"),
    ]
    ttl: int
    raw_text: typing_extensions.Annotated[str, FieldMetadata(alias="rawText"), pydantic.Field(alias="rawText")]
    r_rset_type: typing_extensions.Annotated[int, FieldMetadata(alias="rRsetType"), pydantic.Field(alias="rRsetType")]
    single_name: typing_extensions.Annotated[
        str,
        FieldMetadata(alias="singleName"),
        pydantic.Field(alias="singleName", description="Name server for the domain"),
    ]

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
