# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .domain_reputation_response_dga_score_features import DomainReputationResponseDgaScoreFeatures


class DomainReputationResponseDgaScore(UniversalBaseModel):
    """
    Domain Generation Algorithm (DGA) detection results.
    """

    score: float = pydantic.Field()
    """
    DGA likelihood score (0-1).
    """

    is_dga: bool = pydantic.Field()
    """
    Indicates whether the domain is likely DGA-generated.
    """

    model: str = pydantic.Field()
    """
    Model used to compute the DGA score.
    """

    features: DomainReputationResponseDgaScoreFeatures = pydantic.Field()
    """
    Underlying lexical / statistical features used in DGA detection.
    """

    interpretation: str = pydantic.Field()
    """
    Human-readable interpretation of the DGA score.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
