# This file was auto-generated by Fern from our API Definition.

import typing

DomainReputationResponseIntelligenceRecommendedAction = typing.Union[
    typing.Literal["allow", "monitor", "block"], typing.Any
]
