# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata


class DomainDnsLookupResponseDnsTypes(UniversalBaseModel):
    a: typing_extensions.Annotated[typing.Optional[float], FieldMetadata(alias="A"), pydantic.Field(alias="A")] = None
    aaaa: typing_extensions.Annotated[
        typing.Optional[float], FieldMetadata(alias="AAAA"), pydantic.Field(alias="AAAA")
    ] = None
    cname: typing_extensions.Annotated[
        typing.Optional[float], FieldMetadata(alias="CNAME"), pydantic.Field(alias="CNAME")
    ] = None
    mx: typing_extensions.Annotated[typing.Optional[float], FieldMetadata(alias="MX"), pydantic.Field(alias="MX")] = (
        None
    )
    ns: typing_extensions.Annotated[typing.Optional[float], FieldMetadata(alias="NS"), pydantic.Field(alias="NS")] = (
        None
    )
    soa: typing_extensions.Annotated[
        typing.Optional[float], FieldMetadata(alias="SOA"), pydantic.Field(alias="SOA")
    ] = None
    txt: typing_extensions.Annotated[
        typing.Optional[float], FieldMetadata(alias="TXT"), pydantic.Field(alias="TXT")
    ] = None
    spf: typing_extensions.Annotated[
        typing.Optional[float], FieldMetadata(alias="SPF"), pydantic.Field(alias="SPF")
    ] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
