# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .domain_availability_suggestions_response_domain_available_response_domain_available_response_item import (
    DomainAvailabilitySuggestionsResponseDomainAvailableResponseDomainAvailableResponseItem,
)


class DomainAvailabilitySuggestionsResponseDomainAvailableResponse(UniversalBaseModel):
    """
    Returned when `sug` is omitted or `true` — the queried domain plus suggested alternatives.
    """

    domain_available_response: typing.Optional[
        typing.List[DomainAvailabilitySuggestionsResponseDomainAvailableResponseDomainAvailableResponseItem]
    ] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
