# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .domain_reputation_response_risk_category_pivot_matches_item import (
    DomainReputationResponseRiskCategoryPivotMatchesItem,
)
from .domain_reputation_response_risk_category_severity import DomainReputationResponseRiskCategorySeverity
from .domain_reputation_response_risk_category_sources_item import DomainReputationResponseRiskCategorySourcesItem
from .domain_reputation_response_risk_category_verdict import DomainReputationResponseRiskCategoryVerdict


class DomainReputationResponseRiskCategory(UniversalBaseModel):
    """
    Overall risk assessment for the domain.
    """

    verdict: DomainReputationResponseRiskCategoryVerdict = pydantic.Field()
    """
    Final verdict of the risk assessment.
    """

    confidence: float = pydantic.Field()
    """
    Confidence score for the verdict (0-1).
    """

    primary_threat: typing.Optional[str] = pydantic.Field(default=None)
    """
    Main threat type identified (e.g. phishing). null when no threat was identified.
    """

    severity: DomainReputationResponseRiskCategorySeverity = pydantic.Field()
    """
    Severity level of the risk.
    """

    threat_types: typing.List[str] = pydantic.Field()
    """
    List of threat types associated with the domain.
    """

    sources: typing.List[DomainReputationResponseRiskCategorySourcesItem] = pydantic.Field()
    """
    Threat intelligence sources that flagged the domain. Empty when nothing flagged it.
    """

    pivot_matches: typing.List[DomainReputationResponseRiskCategoryPivotMatchesItem] = pydantic.Field()
    """
    Related pivots (nameserver, email, etc.) linked to known threats.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
