# This file was auto-generated by Fern from our API Definition.

import typing

from .domain_whois_reverse_response_whois_domains_historical_item_administrative_contact import (
    DomainWhoisReverseResponseWhoisDomainsHistoricalItemAdministrativeContact,
)
from .domain_whois_reverse_response_whois_domains_historical_item_companyname import (
    DomainWhoisReverseResponseWhoisDomainsHistoricalItemCompanyname,
)

DomainWhoisReverseResponseWhoisDomainsHistoricalItem = typing.Union[
    DomainWhoisReverseResponseWhoisDomainsHistoricalItemAdministrativeContact,
    DomainWhoisReverseResponseWhoisDomainsHistoricalItemCompanyname,
]
