# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class EmailValidateResponseAddressSecurity(UniversalBaseModel):
    threat_score: int
    is_tor: bool
    is_proxy: bool
    proxy_type: str
    proxy_provider: str
    is_anonymous: bool
    is_known_attacker: bool
    is_spam: bool
    is_bot: bool
    is_cloud_provider: bool
    cloud_provider: str

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
