# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class FloodForecastResponseLocationContinentCode(UniversalBaseModel):
    continent_code: str = pydantic.Field()
    """
    Two-letter continent code (e.g., NA for North America, EU for Europe, AS for Asia).
    """

    continent_name: str = pydantic.Field()
    """
    Full name of the continent where the IP address is registered.
    """

    country_code2: str = pydantic.Field()
    """
    ISO 3166-1 alpha-2 two-letter country code (e.g., US, GB, FR).
    """

    country_code3: str = pydantic.Field()
    """
    ISO 3166-1 alpha-3 three-letter country code (e.g., USA, GBR, FRA).
    """

    country_name: str = pydantic.Field()
    """
    Common name of the country associated with the IP address.
    """

    country_name_official: str = pydantic.Field()
    """
    Official long-form country name as recognized internationally (e.g., United States of America).
    """

    is_eu: typing.Optional[bool] = pydantic.Field(default=None)
    """
    Boolean flag indicating whether the country is a member state of the European Union.
    """

    state_prov: str = pydantic.Field()
    """
    State, province, or primary administrative division associated with the IP location.
    """

    state_code: typing.Optional[str] = pydantic.Field(default=None)
    """
    ISO 3166-2 subdivision code for the state or province (e.g., CA for California).
    """

    district: typing.Optional[str] = pydantic.Field(default=None)
    """
    District, county, or secondary administrative division within the region.
    """

    city: str = pydantic.Field()
    """
    City or urban area name where the IP address is geographically registered.
    """

    zipcode: typing.Optional[str] = pydantic.Field(default=None)
    """
    Postal code or ZIP code for the approximate location of the IP address.
    """

    latitude: float = pydantic.Field()
    """
    Geographic latitude in decimal degrees for the IP geolocation, ranging from -90 to +90.
    """

    longitude: float = pydantic.Field()
    """
    Geographic longitude in decimal degrees for the IP geolocation, ranging from -180 to +180.
    """

    locality: typing.Optional[str] = pydantic.Field(default=None)
    """
    Specific locality, neighborhood, or small area designation within the city.
    """

    elevation: typing.Optional[float] = pydantic.Field(default=None)
    """
    Elevation above mean sea level in meters for the IP geolocation.
    """

    timezone: str = pydantic.Field()
    """
    IANA timezone database identifier for the IP location (e.g., America/Chicago, Asia/Tokyo).
    """

    timezone_abbreviation: str = pydantic.Field()
    """
    Current timezone abbreviation based on local offset (e.g., CST, JST, UTC).
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
