# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class FloodForecastResponseLocationCity(UniversalBaseModel):
    location_string: str = pydantic.Field()
    """
    Original location query string as submitted, including full address or place name.
    """

    country_name: str = pydantic.Field()
    """
    Resolved country name derived from the geocoded location query.
    """

    state_prov: str = pydantic.Field()
    """
    State, province, or primary administrative division identified from the location.
    """

    city: str = pydantic.Field()
    """
    City or municipal area name extracted from the geocoded location.
    """

    locality: typing.Optional[str] = pydantic.Field(default=None)
    """
    Specific locality, neighborhood, suburb, or village within the geocoded area.
    """

    latitude: float = pydantic.Field()
    """
    Geocoded latitude coordinate in decimal degrees, ranging from -90 to +90.
    """

    longitude: float = pydantic.Field()
    """
    Geocoded longitude coordinate in decimal degrees, ranging from -180 to +180.
    """

    elevation: typing.Optional[float] = pydantic.Field(default=None)
    """
    Elevation above mean sea level in meters at the geocoded coordinates.
    """

    timezone: str = pydantic.Field()
    """
    IANA timezone database identifier for the geocoded location (e.g., America/Los_Angeles).
    """

    timezone_abbreviation: str = pydantic.Field()
    """
    Current timezone abbreviation for the location based on local offset (e.g., PDT, CET).
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
