# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .flood_forecast_response_forecast_value import FloodForecastResponseForecastValue
from .flood_forecast_response_location import FloodForecastResponseLocation


class FloodForecastResponse(UniversalBaseModel):
    location: typing.Optional[FloodForecastResponseLocation] = pydantic.Field(default=None)
    """
    Location information
    """

    forecast: typing.Optional[typing.Dict[str, FloodForecastResponseForecastValue]] = pydantic.Field(default=None)
    """
    Flood forecast data object
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
