# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class FloodForecastResponseForecastValueDaily(UniversalBaseModel):
    """
    Daily flood forecast data for the date.
    """

    timestamp: typing.Optional[dt.datetime] = pydantic.Field(default=None)
    """
    ISO 8601 formatted timestamp
    """

    river_discharge: typing.Optional[float] = pydantic.Field(default=None)
    """
    The observed river discharge value (m³/s)
    """

    river_discharge_mean: typing.Optional[float] = pydantic.Field(default=None)
    """
    The mean river discharge (m³/s)
    """

    river_discharge_median: typing.Optional[float] = pydantic.Field(default=None)
    """
    The median river discharge (m³/s)
    """

    river_discharge_max: typing.Optional[float] = pydantic.Field(default=None)
    """
    The maximum river discharge (m³/s)
    """

    river_discharge_min: typing.Optional[float] = pydantic.Field(default=None)
    """
    The minimum river discharge (m³/s)
    """

    river_discharge_p25: typing.Optional[float] = pydantic.Field(default=None)
    """
    The 25th percentile of river discharge (m³/s)
    """

    river_discharge_p75: typing.Optional[float] = pydantic.Field(default=None)
    """
    The 75th percentile of river discharge (m³/s)
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
