# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .geocoder_search_response_item_poi_item import GeocoderSearchResponseItemPoiItem


class GeocoderSearchResponseItem(UniversalBaseModel):
    lat: float = pydantic.Field()
    """
    WGS84 latitude value for the location.
    """

    lon: float = pydantic.Field()
    """
    WGS84 longitude value for the location.
    """

    name: typing.Optional[str] = pydantic.Field(default=None)
    """
    Name for the primary place searched.
    """

    category: typing.Optional[str] = pydantic.Field(default=None)
    """
    High-level category of the place, e.g., amenity, place, natural, building, highway.
    """

    type: typing.Optional[str] = pydantic.Field(default=None)
    """
    Specific kind within the category, e.g., fast_food, city, park, residential, house_number.
    """

    poi: typing.Optional[typing.List[GeocoderSearchResponseItemPoiItem]] = pydantic.Field(default=None)
    """
    Array describing the main POI and closely related elements at this location.
    """

    street: typing.Optional[str] = pydantic.Field(default=None)
    """
    Street or road name.
    """

    area: typing.Optional[str] = pydantic.Field(default=None)
    """
    Intra-city area below city level, e.g., suburb, borough, ward, district, tehsil, neighbourhood.
    """

    postcode: typing.Optional[str] = pydantic.Field(default=None)
    """
    Postal code of the area.
    """

    city: typing.Optional[str] = pydantic.Field(default=None)
    """
    Settlement label appropriate to the country, e.g., city, town, municipality.
    """

    county: typing.Optional[str] = pydantic.Field(default=None)
    """
    Second-tier administrative area, e.g., county, district, prefecture.
    """

    state_code: typing.Optional[str] = pydantic.Field(default=None)
    """
    Subdivision code, typically ISO-3166-2 (e.g., US-TX, PK-PB).
    """

    state: typing.Optional[str] = pydantic.Field(default=None)
    """
    First-tier administrative area, e.g., state, region, province, division.
    """

    country_code: str = pydantic.Field()
    """
    Two-letter country code in upper case, ISO-3166-1 alpha-2.
    """

    country: str = pydantic.Field()
    """
    Country name of the searched place.
    """

    full_address: str = pydantic.Field()
    """
    Single-line, human-readable address of the location.
    """

    bounding_box: typing.List[str] = pydantic.Field()
    """
    Extent of the feature as [lat_min, lat_max, lon_min, lon_max] in WGS84 decimal degrees.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
