# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class GeocoderSearchResponseItemPoiItem(UniversalBaseModel):
    name: typing.Optional[str] = pydantic.Field(default=None)
    """
    Name of the poi (point of interest) of the searched place.
    """

    category: typing.Optional[str] = pydantic.Field(default=None)
    """
    Category of the poi, e.g., amenity, place, natural, building, highway.
    """

    type: typing.Optional[str] = pydantic.Field(default=None)
    """
    Specific type of the category for the poi, e.g., fast_food, city, park, residential, house_number.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
