# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class GeolocationLookupV2ResponseLocation(UniversalBaseModel):
    """
    Geographic location information for the IP.
    """

    continent_code: str = pydantic.Field()
    """
    2-letter code of the continent.
    """

    continent_name: str = pydantic.Field()
    """
    Name of the continent.
    """

    country_code2: str = pydantic.Field()
    """
    Country code (ISO 3166-1 alpha-2) of the country.
    """

    country_code3: str = pydantic.Field()
    """
    Country code (ISO 3166-1 alpha-3) of the country.
    """

    country_name: str = pydantic.Field()
    """
    Name of the country.
    """

    country_name_official: str = pydantic.Field()
    """
    Official name (ISO 3166) of the country.
    """

    country_capital: str = pydantic.Field()
    """
    Name of the country's capital.
    """

    state_prov: typing.Optional[str] = pydantic.Field(default=None)
    """
    Name of the state/province/region.
    """

    state_code: typing.Optional[str] = pydantic.Field(default=None)
    """
    Code of the state/province/region.
    """

    district: typing.Optional[str] = pydantic.Field(default=None)
    """
    Name of the district or county.
    """

    city: typing.Optional[str] = pydantic.Field(default=None)
    """
    Name of the city.
    """

    locality: typing.Optional[str] = pydantic.Field(default=None)
    """
    A more specific area in city or it can be same as city.
    """

    accuracy_radius: typing.Optional[str] = pydantic.Field(default=None)
    """
    Circular radius in Km, where the IP address location can be found.
    """

    confidence: typing.Optional[str] = pydantic.Field(default=None)
    """
    Confidence level of the location match (e.g., low, medium, high).
    """

    dma_code: typing.Optional[str] = pydantic.Field(default=None)
    """
    Designated Market Area (DMA) code used in the United States for media marketing.
    """

    zipcode: typing.Optional[str] = pydantic.Field(default=None)
    """
    ZIP/Postal code of the place.
    """

    latitude: str = pydantic.Field()
    """
    Latitude of the place.
    """

    longitude: str = pydantic.Field()
    """
    Longitude of the place.
    """

    is_eu: bool = pydantic.Field()
    """
    Is the country belong to European Union?
    """

    country_flag: str = pydantic.Field()
    """
    URL to get the country flag.
    """

    geoname_id: typing.Optional[str] = pydantic.Field(default=None)
    """
    Geoname ID of the place from geonames.org.
    """

    country_emoji: typing.Optional[str] = pydantic.Field(default=None)
    """
    Emoji of the Country flag.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
