# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class GeolocationLookupResponseAbuseItem(UniversalBaseModel):
    route: typing.Optional[str] = pydantic.Field(default=None)
    """
    The IP range of the abuse contact
    """

    country: typing.Optional[str] = pydantic.Field(default=None)
    """
    The country code of the abuse contact
    """

    handle: typing.Optional[str] = pydantic.Field(default=None)
    """
    The handle of the abuse contact
    """

    name: typing.Optional[str] = pydantic.Field(default=None)
    """
    The name of the abuse contact
    """

    organization: typing.Optional[str] = pydantic.Field(default=None)
    """
    The organization of the abuse contact
    """

    role: typing.Optional[str] = pydantic.Field(default=None)
    """
    The role of the abuse contact
    """

    kind: typing.Optional[str] = pydantic.Field(default=None)
    """
    The kind of the abuse contact
    """

    address: typing.Optional[str] = pydantic.Field(default=None)
    """
    The address of the abuse contact
    """

    emails: typing.Optional[typing.List[str]] = pydantic.Field(default=None)
    """
    The list of email addresses of the abuse contact
    """

    phone_numbers: typing.Optional[typing.List[str]] = pydantic.Field(default=None)
    """
    The list of phone numbers of the abuse contact
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
