# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .geolocation_lookup_v2_response_user_agent_device import GeolocationLookupV2ResponseUserAgentDevice
from .geolocation_lookup_v2_response_user_agent_engine import GeolocationLookupV2ResponseUserAgentEngine
from .geolocation_lookup_v2_response_user_agent_operating_system import (
    GeolocationLookupV2ResponseUserAgentOperatingSystem,
)


class GeolocationLookupV2ResponseUserAgent(UniversalBaseModel):
    """
    Parsed User-Agent details from the request.
    """

    user_agent_string: typing.Optional[str] = pydantic.Field(default=None)
    """
    Raw User-Agent string used for parsing.
    """

    name: typing.Optional[str] = pydantic.Field(default=None)
    """
    Detected user agent product name.
    """

    type: typing.Optional[str] = pydantic.Field(default=None)
    """
    User agent category (e.g., Browser, Mobile App, Bot).
    """

    version: typing.Optional[str] = pydantic.Field(default=None)
    """
    Full product version string.
    """

    version_major: typing.Optional[str] = pydantic.Field(default=None)
    """
    Major version extracted from version.
    """

    device: typing.Optional[GeolocationLookupV2ResponseUserAgentDevice] = pydantic.Field(default=None)
    """
    Device details.
    """

    engine: typing.Optional[GeolocationLookupV2ResponseUserAgentEngine] = pydantic.Field(default=None)
    """
    Rendering engine details.
    """

    operating_system: typing.Optional[GeolocationLookupV2ResponseUserAgentOperatingSystem] = pydantic.Field(
        default=None
    )
    """
    Operating system details.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
