# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .geolocation_lookup_v2_response_abuse import GeolocationLookupV2ResponseAbuse
from .geolocation_lookup_v2_response_asn import GeolocationLookupV2ResponseAsn
from .geolocation_lookup_v2_response_company import GeolocationLookupV2ResponseCompany
from .geolocation_lookup_v2_response_country_metadata import GeolocationLookupV2ResponseCountryMetadata
from .geolocation_lookup_v2_response_currency import GeolocationLookupV2ResponseCurrency
from .geolocation_lookup_v2_response_location import GeolocationLookupV2ResponseLocation
from .geolocation_lookup_v2_response_network import GeolocationLookupV2ResponseNetwork
from .geolocation_lookup_v2_response_security import GeolocationLookupV2ResponseSecurity
from .geolocation_lookup_v2_response_time_zone import GeolocationLookupV2ResponseTimeZone
from .geolocation_lookup_v2_response_user_agent import GeolocationLookupV2ResponseUserAgent


class GeolocationLookupV2Response(UniversalBaseModel):
    ip: str = pydantic.Field()
    """
    The IP address used for the lookup (IPv4 or IPv6).
    """

    domain: typing.Optional[str] = pydantic.Field(default=None)
    """
    The input domain, returned only for domain-based lookups.
    """

    hostname: typing.Optional[str] = pydantic.Field(default=None)
    """
    Reverse DNS hostname (PTR) for the input IP; returns the input IP if not resolvable.
    """

    location: typing.Optional[GeolocationLookupV2ResponseLocation] = pydantic.Field(default=None)
    """
    Geographic location information for the IP.
    """

    country_metadata: typing.Optional[GeolocationLookupV2ResponseCountryMetadata] = pydantic.Field(default=None)
    """
    Country-specific metadata.
    """

    network: typing.Optional[GeolocationLookupV2ResponseNetwork] = pydantic.Field(default=None)
    """
    Network information for the IP.
    """

    asn: typing.Optional[GeolocationLookupV2ResponseAsn] = pydantic.Field(default=None)
    """
    Autonomous System details for the IP.
    """

    company: typing.Optional[GeolocationLookupV2ResponseCompany] = pydantic.Field(default=None)
    """
    Company or ISP information mapped to the IP address.
    """

    currency: typing.Optional[GeolocationLookupV2ResponseCurrency] = pydantic.Field(default=None)
    """
    Currency information for the IP's country.
    """

    security: typing.Optional[GeolocationLookupV2ResponseSecurity] = pydantic.Field(default=None)
    """
    Threat intelligence and security information for the IP.
    """

    abuse: typing.Optional[GeolocationLookupV2ResponseAbuse] = pydantic.Field(default=None)
    """
    Abuse contact information for the IP.
    """

    time_zone: typing.Optional[GeolocationLookupV2ResponseTimeZone] = pydantic.Field(default=None)
    """
    Time zone information for the IP's location.
    """

    user_agent: typing.Optional[GeolocationLookupV2ResponseUserAgent] = pydantic.Field(default=None)
    """
    Parsed User-Agent details from the request.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
