# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata


class GeolocationLookupResponseNetworkAsn(UniversalBaseModel):
    as_number: typing.Optional[str] = pydantic.Field(default=None)
    """
    The AS number
    """

    organization: typing.Optional[str] = pydantic.Field(default=None)
    """
    The organization name
    """

    country: typing.Optional[str] = pydantic.Field(default=None)
    """
    The country code
    """

    asn_name: typing.Optional[str] = pydantic.Field(default=None)
    """
    The ASN name
    """

    type: typing.Optional[str] = pydantic.Field(default=None)
    """
    The type of the ASN
    """

    domain: typing.Optional[str] = pydantic.Field(default=None)
    """
    The domain associated with the ASN
    """

    date_allocated: typing.Optional[str] = pydantic.Field(default=None)
    """
    The date when the ASN was allocated
    """

    allocation_status: typing.Optional[str] = pydantic.Field(default=None)
    """
    The allocation status of the ASN
    """

    num_of_ipv4routes: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="num_of_ipv4_routes"),
        pydantic.Field(alias="num_of_ipv4_routes", description="The number of IPv4 routes associated with the ASN"),
    ] = None
    num_of_ipv6routes: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="num_of_ipv6_routes"),
        pydantic.Field(alias="num_of_ipv6_routes", description="The number of IPv6 routes associated with the ASN"),
    ] = None
    rir: typing.Optional[str] = pydantic.Field(default=None)
    """
    The Regional Internet Registry (RIR) of the ASN
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
