# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class GeolocationLookupV2ResponseSecurity(UniversalBaseModel):
    """
    Threat intelligence and security information for the IP.
    """

    threat_score: float = pydantic.Field()
    """
    Aggregate risk score from 0 to 100.
    """

    is_tor: bool = pydantic.Field()
    """
    true if the IP matches a Tor exit node.
    """

    is_proxy: bool = pydantic.Field()
    """
    true if the IP is associated with a proxy service.
    """

    proxy_provider_names: typing.Optional[typing.List[str]] = pydantic.Field(default=None)
    """
    Detected proxy provider names.
    """

    proxy_confidence_score: float = pydantic.Field()
    """
    Proxy detection confidence from 0 to 100.
    """

    proxy_last_seen: typing.Optional[str] = pydantic.Field(default=None)
    """
    Last observed proxy activity date in YYYY-MM-DD.
    """

    is_residential_proxy: bool = pydantic.Field()
    """
    true if the IP is linked to a residential proxy network.
    """

    is_vpn: bool = pydantic.Field()
    """
    true if the IP is associated with a VPN service.
    """

    vpn_provider_names: typing.Optional[typing.List[str]] = pydantic.Field(default=None)
    """
    Detected VPN provider names.
    """

    vpn_confidence_score: float = pydantic.Field()
    """
    VPN detection confidence from 0 to 100.
    """

    vpn_last_seen: typing.Optional[str] = pydantic.Field(default=None)
    """
    Last observed VPN activity date in YYYY-MM-DD.
    """

    is_relay: bool = pydantic.Field()
    """
    true if the IP is associated with a relay network.
    """

    relay_provider_name: typing.Optional[str] = pydantic.Field(default=None)
    """
    Relay provider name.
    """

    is_anonymous: bool = pydantic.Field()
    """
    true if any anonymity signal is present.
    """

    is_known_attacker: bool = pydantic.Field()
    """
    true if the IP is flagged for known attacker behavior.
    """

    is_bot: bool = pydantic.Field()
    """
    true if the IP is associated with bot activity.
    """

    is_spam: bool = pydantic.Field()
    """
    true if the IP is associated with spam activity.
    """

    is_cloud_provider: bool = pydantic.Field()
    """
    true if the IP belongs to a cloud provider range.
    """

    cloud_provider_name: typing.Optional[str] = pydantic.Field(default=None)
    """
    Cloud provider name.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
