# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class GeolocationLookupV2ResponseUserAgentDevice(UniversalBaseModel):
    name: typing.Optional[str] = None
    type: typing.Optional[str] = None
    brand: typing.Optional[str] = None
    cpu: typing.Optional[str] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class GeolocationLookupV2ResponseUserAgentEngine(UniversalBaseModel):
    name: typing.Optional[str] = None
    type: typing.Optional[str] = None
    version: typing.Optional[str] = None
    version_major: typing.Optional[str] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class GeolocationLookupV2ResponseUserAgentOperatingSystem(UniversalBaseModel):
    name: typing.Optional[str] = None
    type: typing.Optional[str] = None
    version: typing.Optional[str] = None
    version_major: typing.Optional[str] = None
    build: typing.Optional[str] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class GeolocationLookupV2ResponseUserAgent(UniversalBaseModel):
    user_agent_string: typing.Optional[str] = None
    name: typing.Optional[str] = None
    type: typing.Optional[str] = None
    version: typing.Optional[str] = None
    version_major: typing.Optional[str] = None
    device: typing.Optional[GeolocationLookupV2ResponseUserAgentDevice] = None
    engine: typing.Optional[GeolocationLookupV2ResponseUserAgentEngine] = None
    operating_system: typing.Optional[GeolocationLookupV2ResponseUserAgentOperatingSystem] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class GeolocationLookupV2ResponseLocation(UniversalBaseModel):
    continent_code: typing.Optional[str] = None
    continent_name: typing.Optional[str] = None
    country_code2: typing.Optional[str] = None
    country_code3: typing.Optional[str] = None
    country_name: typing.Optional[str] = None
    country_name_official: typing.Optional[str] = None
    country_capital: typing.Optional[str] = None
    state_prov: typing.Optional[str] = None
    state_code: typing.Optional[str] = None
    district: typing.Optional[str] = None
    city: typing.Optional[str] = None
    locality: typing.Optional[str] = None
    accuracy_radius: typing.Optional[str] = None
    confidence: typing.Optional[str] = None
    dma_code: typing.Optional[str] = None
    zipcode: typing.Optional[str] = None
    latitude: typing.Optional[str] = None
    longitude: typing.Optional[str] = None
    is_eu: typing.Optional[bool] = None
    country_flag: typing.Optional[str] = None
    geoname_id: typing.Optional[str] = None
    country_emoji: typing.Optional[str] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class GeolocationLookupV2ResponseCountryMetadata(UniversalBaseModel):
    calling_code: typing.Optional[str] = None
    tld: typing.Optional[str] = None
    languages: typing.Optional[typing.List[str]] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class GeolocationLookupV2ResponseNetwork(UniversalBaseModel):
    connection_type: typing.Optional[str] = None
    route: typing.Optional[str] = None
    is_anycast: typing.Optional[bool] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class GeolocationLookupV2ResponseCurrency(UniversalBaseModel):
    code: typing.Optional[str] = None
    name: typing.Optional[str] = None
    symbol: typing.Optional[str] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class GeolocationLookupV2ResponseAsn(UniversalBaseModel):
    as_number: typing.Optional[str] = None
    organization: typing.Optional[str] = None
    country: typing.Optional[str] = None
    type: typing.Optional[str] = None
    domain: typing.Optional[str] = None
    date_allocated: typing.Optional[str] = None
    rir: typing.Optional[str] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class GeolocationLookupV2ResponseCompany(UniversalBaseModel):
    name: typing.Optional[str] = None
    type: typing.Optional[str] = None
    domain: typing.Optional[str] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class GeolocationLookupV2ResponseSecurity(UniversalBaseModel):
    threat_score: typing.Optional[float] = None
    is_tor: typing.Optional[bool] = None
    is_proxy: typing.Optional[bool] = None
    proxy_provider_names: typing.Optional[typing.List[str]] = None
    proxy_confidence_score: typing.Optional[float] = None
    proxy_last_seen: typing.Optional[str] = None
    is_residential_proxy: typing.Optional[bool] = None
    is_vpn: typing.Optional[bool] = None
    vpn_provider_names: typing.Optional[typing.List[str]] = None
    vpn_confidence_score: typing.Optional[float] = None
    vpn_last_seen: typing.Optional[str] = None
    is_relay: typing.Optional[bool] = None
    relay_provider_name: typing.Optional[str] = None
    is_anonymous: typing.Optional[bool] = None
    is_known_attacker: typing.Optional[bool] = None
    is_bot: typing.Optional[bool] = None
    is_spam: typing.Optional[bool] = None
    is_cloud_provider: typing.Optional[bool] = None
    cloud_provider_name: typing.Optional[str] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class GeolocationLookupV2ResponseAbuse(UniversalBaseModel):
    route: typing.Optional[str] = None
    country: typing.Optional[str] = None
    name: typing.Optional[str] = None
    organization: typing.Optional[str] = None
    kind: typing.Optional[str] = None
    address: typing.Optional[str] = None
    emails: typing.Optional[typing.List[str]] = None
    phone_numbers: typing.Optional[typing.List[str]] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class GeolocationLookupV2ResponseTimeZoneDstStart(UniversalBaseModel):
    utc_time: typing.Optional[str] = None
    duration: typing.Optional[str] = None
    gap: typing.Optional[bool] = None
    date_time_after: typing.Optional[str] = None
    date_time_before: typing.Optional[str] = None
    overlap: typing.Optional[bool] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class GeolocationLookupV2ResponseTimeZoneDstEnd(UniversalBaseModel):
    utc_time: typing.Optional[str] = None
    duration: typing.Optional[str] = None
    gap: typing.Optional[bool] = None
    date_time_after: typing.Optional[str] = None
    date_time_before: typing.Optional[str] = None
    overlap: typing.Optional[bool] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class GeolocationLookupV2ResponseTimeZone(UniversalBaseModel):
    name: typing.Optional[str] = None
    offset: typing.Optional[float] = None
    offset_with_dst: typing.Optional[float] = None
    current_time: typing.Optional[str] = None
    current_time_unix: typing.Optional[float] = None
    current_tz_abbreviation: typing.Optional[str] = None
    current_tz_full_name: typing.Optional[str] = None
    standard_tz_abbreviation: typing.Optional[str] = None
    standard_tz_full_name: typing.Optional[str] = None
    is_dst: typing.Optional[bool] = None
    dst_savings: typing.Optional[float] = None
    dst_exists: typing.Optional[bool] = None
    dst_tz_abbreviation: typing.Optional[str] = None
    dst_tz_full_name: typing.Optional[str] = None
    dst_start: typing.Optional[GeolocationLookupV2ResponseTimeZoneDstStart] = None
    dst_end: typing.Optional[GeolocationLookupV2ResponseTimeZoneDstEnd] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class GeolocationLookupV2Response(UniversalBaseModel):
    ip: typing.Optional[str] = None
    domain: typing.Optional[str] = None
    hostname: typing.Optional[str] = None
    user_agent: typing.Optional[GeolocationLookupV2ResponseUserAgent] = None
    location: typing.Optional[GeolocationLookupV2ResponseLocation] = None
    country_metadata: typing.Optional[GeolocationLookupV2ResponseCountryMetadata] = None
    network: typing.Optional[GeolocationLookupV2ResponseNetwork] = None
    currency: typing.Optional[GeolocationLookupV2ResponseCurrency] = None
    asn: typing.Optional[GeolocationLookupV2ResponseAsn] = None
    company: typing.Optional[GeolocationLookupV2ResponseCompany] = None
    security: typing.Optional[GeolocationLookupV2ResponseSecurity] = None
    abuse: typing.Optional[GeolocationLookupV2ResponseAbuse] = None
    time_zone: typing.Optional[GeolocationLookupV2ResponseTimeZone] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
