# This file was auto-generated by Fern from our API Definition.

import typing

GeolocationLookupRequestLang = typing.Union[
    typing.Literal["en", "de", "ru", "ja", "fr", "cn", "es", "cs", "it"], typing.Any
]
