# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class GeolocationLookupV2ResponseCountryMetadata(UniversalBaseModel):
    """
    Country-specific metadata.
    """

    calling_code: str = pydantic.Field()
    """
    Calling code/Dialing code of the country.
    """

    tld: str = pydantic.Field()
    """
    Top Level Domain Name (TLD) of the country, which is also called ccTLD.
    """

    languages: typing.List[str] = pydantic.Field()
    """
    List of the languages' codes, spoken in the country.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
