# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .geolocation_lookup_response_abuse_item import GeolocationLookupResponseAbuseItem
from .geolocation_lookup_response_country_metadata import GeolocationLookupResponseCountryMetadata
from .geolocation_lookup_response_currency import GeolocationLookupResponseCurrency
from .geolocation_lookup_response_location import GeolocationLookupResponseLocation
from .geolocation_lookup_response_network import GeolocationLookupResponseNetwork
from .geolocation_lookup_response_security import GeolocationLookupResponseSecurity
from .geolocation_lookup_response_time_zone import GeolocationLookupResponseTimeZone
from .geolocation_lookup_response_user_agent import GeolocationLookupResponseUserAgent


class GeolocationLookupResponse(UniversalBaseModel):
    ip: typing.Optional[str] = pydantic.Field(default=None)
    """
    The IP address
    """

    hostname: typing.Optional[str] = pydantic.Field(default=None)
    """
    The hostname (if available)
    """

    location: typing.Optional[GeolocationLookupResponseLocation] = None
    country_metadata: typing.Optional[GeolocationLookupResponseCountryMetadata] = None
    network: typing.Optional[GeolocationLookupResponseNetwork] = None
    currency: typing.Optional[GeolocationLookupResponseCurrency] = None
    security: typing.Optional[GeolocationLookupResponseSecurity] = None
    abuse: typing.Optional[typing.List[GeolocationLookupResponseAbuseItem]] = None
    time_zone: typing.Optional[GeolocationLookupResponseTimeZone] = None
    user_agent: typing.Optional[GeolocationLookupResponseUserAgent] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
