# This file was auto-generated by Fern from our API Definition.

import typing

GeolocationLookupV2RequestLang = typing.Union[
    typing.Literal["en", "de", "ru", "ja", "fr", "cn", "es", "cs", "it", "ko", "fa", "pt"], typing.Any
]
