# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class GeolocationLookupV2ResponseCompany(UniversalBaseModel):
    """
    Company or ISP information mapped to the IP address.
    """

    name: typing.Optional[str] = pydantic.Field(default=None)
    """
    Company name mapped to the IP.
    """

    type: typing.Optional[str] = pydantic.Field(default=None)
    """
    Company category (ISP, HOSTING, BUSINESS, etc.).
    """

    domain: typing.Optional[str] = pydantic.Field(default=None)
    """
    Company domain name.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
