# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata


class GetCountryDetailsResponse(UniversalBaseModel):
    name: str
    iso_alpha2: typing_extensions.Annotated[
        str, FieldMetadata(alias="iso_alpha_2"), pydantic.Field(alias="iso_alpha_2")
    ]
    iso_alpha3: typing_extensions.Annotated[
        str, FieldMetadata(alias="iso_alpha_3"), pydantic.Field(alias="iso_alpha_3")
    ]
    iso_numeric: int
    phone_code: int
    capital: str
    top_level_domain: str
    native_name: str
    region: str
    subregion: str
    nationality: str
    flag_emoji: str
    currency_code: str
    currency_name: str
    currency_symbol: str

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
