# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata


class GetAdminUnitDetailsResponse(UniversalBaseModel):
    name: str
    admin_code: str
    admin_level: str
    iso_alpha2: typing_extensions.Annotated[
        str, FieldMetadata(alias="iso_alpha_2"), pydantic.Field(alias="iso_alpha_2")
    ]
    country_name: str

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
