# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .get_admin_units_response_admin_units_item import GetAdminUnitsResponseAdminUnitsItem


class GetAdminUnitsResponse(UniversalBaseModel):
    admin_units: typing.List[GetAdminUnitsResponseAdminUnitsItem]

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
