# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .grammar_detect_response_grammar_errors_item import GrammarDetectResponseGrammarErrorsItem


class GrammarDetectResponse(UniversalBaseModel):
    grammar_errors: typing.List[GrammarDetectResponseGrammarErrorsItem] = pydantic.Field()
    """
    List of words flagged as grammatically incorrect
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
