# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .historical_weather_response_historical_astronomy import HistoricalWeatherResponseHistoricalAstronomy
from .historical_weather_response_historical_daily import HistoricalWeatherResponseHistoricalDaily
from .historical_weather_response_historical_hourly_item import HistoricalWeatherResponseHistoricalHourlyItem


class HistoricalWeatherResponseHistorical(UniversalBaseModel):
    """
    Historical data object of the provided date
    """

    daily: typing.Optional[HistoricalWeatherResponseHistoricalDaily] = pydantic.Field(default=None)
    """
    Daily historical data
    """

    hourly: typing.Optional[typing.List[HistoricalWeatherResponseHistoricalHourlyItem]] = pydantic.Field(default=None)
    """
    Hourly historical data
    """

    astronomy: typing.Optional[HistoricalWeatherResponseHistoricalAstronomy] = pydantic.Field(default=None)
    """
    Astronomy data
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
