# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class HistoricalWeatherResponseLocationZero(UniversalBaseModel):
    latitude: float = pydantic.Field()
    """
    Geographic latitude coordinate in decimal degrees, ranging from -90 (South Pole) to +90 (North Pole).
    """

    longitude: float = pydantic.Field()
    """
    Geographic longitude coordinate in decimal degrees, ranging from -180 (West) to +180 (East).
    """

    country_name: str = pydantic.Field()
    """
    Full name of the country corresponding to the provided coordinates.
    """

    state_prov: str = pydantic.Field()
    """
    State, province, or primary administrative division name for the location.
    """

    city: str = pydantic.Field()
    """
    City or municipal area name associated with the coordinate location.
    """

    locality: typing.Optional[str] = pydantic.Field(default=None)
    """
    Specific locality, neighborhood, district, or village name within the broader area.
    """

    elevation: typing.Optional[float] = pydantic.Field(default=None)
    """
    Height above mean sea level in meters for the specified coordinates.
    """

    timezone: str = pydantic.Field()
    """
    IANA timezone database identifier for the location (e.g., America/New_York, Europe/London).
    """

    timezone_abbreviation: str = pydantic.Field()
    """
    Abbreviated timezone representation based on current offset (e.g., EST, GMT, PST).
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
