# This file was auto-generated by Fern from our API Definition.

import typing

from .historical_weather_response_location_city import HistoricalWeatherResponseLocationCity
from .historical_weather_response_location_continent_code import HistoricalWeatherResponseLocationContinentCode
from .historical_weather_response_location_zero import HistoricalWeatherResponseLocationZero

HistoricalWeatherResponseLocation = typing.Union[
    HistoricalWeatherResponseLocationZero,
    HistoricalWeatherResponseLocationContinentCode,
    HistoricalWeatherResponseLocationCity,
]
