# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .historical_weather_response_historical import HistoricalWeatherResponseHistorical
from .historical_weather_response_location import HistoricalWeatherResponseLocation


class HistoricalWeatherResponse(UniversalBaseModel):
    location: typing.Optional[HistoricalWeatherResponseLocation] = pydantic.Field(default=None)
    """
    Location information
    """

    historical: typing.Optional[HistoricalWeatherResponseHistorical] = pydantic.Field(default=None)
    """
    Historical data object of the provided date
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
