# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .iban_validate_response_bank_data import IbanValidateResponseBankData
from .iban_validate_response_validation import IbanValidateResponseValidation


class IbanValidateResponse(UniversalBaseModel):
    valid: bool = pydantic.Field()
    """
    Determines whether IBAN passes all validation checks
    """

    iban: str = pydantic.Field()
    """
    The IBAN number provided by the user.
    """

    validation: IbanValidateResponseValidation = pydantic.Field()
    """
    Object contains IBAN validation details.
    """

    bank_data: IbanValidateResponseBankData = pydantic.Field()
    """
    Object contains Bank and BIC details.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
