# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class IbanValidateResponseValidation(UniversalBaseModel):
    """
    Object contains IBAN validation details.
    """

    is_alpha_numeric: bool = pydantic.Field()
    """
    Checks if provided IBAN contains only alpha numeric characters
    """

    is_iban_supported_country: bool = pydantic.Field()
    """
    Checks whether given IBAN country supports IBAN standards
    """

    is_valid_length: bool = pydantic.Field()
    """
    Indicates whether IBAN length is according to respective country standard or not.
    """

    is_valid_structure: bool = pydantic.Field()
    """
    Indicates whether IBAN structure is valid as per structure pattern for respective country.
    """

    is_iban_check_digit_valid: bool = pydantic.Field()
    """
    Indicates whether IBAN check digit is valid.
    """

    bban: typing.Optional[str] = pydantic.Field(default=None)
    """
    Indicates BBAN checksum is valid or invalid or not supported (unknown) for respective IBAN country.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
