# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class IpWhoisLookupResponseOrganization(UniversalBaseModel):
    handle: typing.Optional[str] = None
    name: typing.Optional[str] = None
    type: typing.Optional[str] = None
    description: typing.Optional[typing.List[str]] = None
    address: typing.Optional[typing.List[str]] = None
    street: typing.Optional[str] = None
    city: typing.Optional[str] = None
    district: typing.Optional[str] = None
    state: typing.Optional[str] = None
    zip_code: typing.Optional[str] = None
    country: typing.Optional[typing.List[str]] = None
    latitude: typing.Optional[float] = None
    longitude: typing.Optional[float] = None
    email: typing.Optional[typing.List[str]] = None
    abuse_mailbox: typing.Optional[typing.List[str]] = None
    phone: typing.Optional[typing.List[str]] = None
    fax_no: typing.Optional[typing.List[str]] = None
    organizations: typing.Optional[typing.List[str]] = None
    admin_contacts: typing.Optional[typing.List[str]] = None
    tech_contacts: typing.Optional[typing.List[str]] = None
    abuse_contacts: typing.Optional[typing.List[str]] = None
    languages: typing.Optional[typing.List[str]] = None
    remarks: typing.Optional[typing.List[str]] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
