# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class IpWhoisLookupResponseInetNumsItem(UniversalBaseModel):
    start_ip: typing.Optional[str] = None
    end_ip: typing.Optional[str] = None
    cidr: typing.Optional[typing.List[str]] = None
    net_name: typing.Optional[str] = None
    net_handle: typing.Optional[str] = None
    description: typing.Optional[typing.List[str]] = None
    countries: typing.Optional[typing.List[str]] = None
    geofeed: typing.Optional[str] = None
    latitude: typing.Optional[float] = None
    longitude: typing.Optional[float] = None
    city: typing.Optional[str] = None
    languages: typing.Optional[typing.List[str]] = None
    status: typing.Optional[str] = None
    organization: typing.Optional[str] = None
    sponsoring_organization: typing.Optional[str] = None
    admin_contacts: typing.Optional[typing.List[str]] = None
    tech_contacts: typing.Optional[typing.List[str]] = None
    abuse_contacts: typing.Optional[typing.List[str]] = None
    remarks: typing.Optional[typing.List[str]] = None
    assignment_size: typing.Optional[str] = None
    notify: typing.Optional[typing.List[str]] = None
    mnt_by: typing.Optional[typing.List[str]] = None
    mnt_lower: typing.Optional[typing.List[str]] = None
    mnt_domains: typing.Optional[typing.List[str]] = None
    mnt_routes: typing.Optional[typing.List[str]] = None
    mnt_irt: typing.Optional[typing.List[str]] = None
    date_created: typing.Optional[str] = None
    date_updated: typing.Optional[str] = None
    source: typing.Optional[str] = None
    parents: typing.Optional[typing.List[str]] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
