# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class MarineWeatherResponseForecastValueMinutelyItem(UniversalBaseModel):
    timestamp: typing.Optional[dt.datetime] = pydantic.Field(default=None)
    """
    ISO 8601 formatted timestamp
    """

    ocean_current_velocity: typing.Optional[float] = pydantic.Field(default=None)
    """
    Speed of ocean current (km/h)
    """

    ocean_current_direction: typing.Optional[int] = pydantic.Field(default=None)
    """
    Direction of ocean current (°)
    """

    sea_level_height_msl: typing.Optional[float] = pydantic.Field(default=None)
    """
    Sea level height relative to mean sea level (m)
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
