# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class MarineWeatherResponseForecastValueDaily(UniversalBaseModel):
    """
    Daily marine forecast data
    """

    timestamp: typing.Optional[dt.datetime] = pydantic.Field(default=None)
    """
    ISO 8601 formatted timestamp
    """

    wave_height_max: typing.Optional[float] = pydantic.Field(default=None)
    """
    Maximum significant wave height (m)
    """

    wave_direction_dominant: typing.Optional[int] = pydantic.Field(default=None)
    """
    Dominant direction of waves (°)
    """

    wave_period_max: typing.Optional[float] = pydantic.Field(default=None)
    """
    Maximum wave period (s)
    """

    wind_wave_height_max: typing.Optional[float] = pydantic.Field(default=None)
    """
    Maximum wind-driven wave height (m)
    """

    wind_wave_direction_dominant: typing.Optional[int] = pydantic.Field(default=None)
    """
    Dominant wind-wave direction (°)
    """

    wind_wave_period_max: typing.Optional[float] = pydantic.Field(default=None)
    """
    Maximum wind-wave period (s)
    """

    wind_wave_peak_period_max: typing.Optional[float] = pydantic.Field(default=None)
    """
    Maximum peak period of wind-driven waves (s)
    """

    swell_wave_height_max: typing.Optional[float] = pydantic.Field(default=None)
    """
    Maximum swell wave height (m)
    """

    swell_wave_direction_dominant: typing.Optional[int] = pydantic.Field(default=None)
    """
    Dominant swell wave direction (°)
    """

    swell_wave_period_max: typing.Optional[float] = pydantic.Field(default=None)
    """
    Maximum swell wave period (s)
    """

    swell_wave_peak_period_max: typing.Optional[float] = pydantic.Field(default=None)
    """
    Maximum peak period of swell waves (s)
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
