# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class MarineWeatherResponseCurrent(UniversalBaseModel):
    """
    Current marine data
    """

    timestamp: typing.Optional[dt.datetime] = pydantic.Field(default=None)
    """
    ISO 8601 formatted timestamp
    """

    wave_height: typing.Optional[float] = pydantic.Field(default=None)
    """
    Significant height of combined sea waves (m)
    """

    wave_direction: typing.Optional[float] = pydantic.Field(default=None)
    """
    Direction from which the combined waves are coming (°)
    """

    wave_period: typing.Optional[float] = pydantic.Field(default=None)
    """
    Average period of combined sea waves (s)
    """

    wind_wave_height: typing.Optional[float] = pydantic.Field(default=None)
    """
    Height of locally generated wind waves (m)
    """

    wind_wave_direction: typing.Optional[float] = pydantic.Field(default=None)
    """
    Direction from which the wind waves are coming (°)
    """

    wind_wave_period: typing.Optional[float] = pydantic.Field(default=None)
    """
    Average period of locally generated wind waves (s)
    """

    swell_wave_height: typing.Optional[float] = pydantic.Field(default=None)
    """
    Height of swell waves (m)
    """

    swell_wave_direction: typing.Optional[float] = pydantic.Field(default=None)
    """
    Direction from which the swell waves are coming (°)
    """

    swell_wave_period: typing.Optional[float] = pydantic.Field(default=None)
    """
    Average period of swell waves (s)
    """

    sea_level_height_msl: typing.Optional[float] = pydantic.Field(default=None)
    """
    Sea level height relative to mean sea level (m)
    """

    sea_surface_temperature: typing.Optional[float] = pydantic.Field(default=None)
    """
    Temperature of the ocean surface (°C)
    """

    ocean_current_velocity: typing.Optional[float] = pydantic.Field(default=None)
    """
    Speed of the ocean current (km/h)
    """

    ocean_current_direction: typing.Optional[float] = pydantic.Field(default=None)
    """
    Direction of the ocean current (°)
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
