# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .marine_weather_response_forecast_value_daily import MarineWeatherResponseForecastValueDaily
from .marine_weather_response_forecast_value_hourly_item import MarineWeatherResponseForecastValueHourlyItem
from .marine_weather_response_forecast_value_minutely_item import MarineWeatherResponseForecastValueMinutelyItem


class MarineWeatherResponseForecastValue(UniversalBaseModel):
    daily: typing.Optional[MarineWeatherResponseForecastValueDaily] = pydantic.Field(default=None)
    """
    Daily marine forecast data
    """

    hourly: typing.Optional[typing.List[MarineWeatherResponseForecastValueHourlyItem]] = pydantic.Field(default=None)
    """
    Hourly marine forecast data
    """

    minutely: typing.Optional[typing.List[MarineWeatherResponseForecastValueMinutelyItem]] = pydantic.Field(
        default=None
    )
    """
    Minutely marine forecast data
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
