# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class MarineWeatherResponseForecastValueHourlyItem(UniversalBaseModel):
    timestamp: typing.Optional[dt.datetime] = pydantic.Field(default=None)
    """
    ISO 8601 formatted timestamp
    """

    wave_height: typing.Optional[float] = pydantic.Field(default=None)
    """
    Significant wave height at the given time (m)
    """

    wave_direction: typing.Optional[int] = pydantic.Field(default=None)
    """
    Wave direction (°)
    """

    wave_period: typing.Optional[float] = pydantic.Field(default=None)
    """
    Wave period at the given time (s)
    """

    wind_wave_height: typing.Optional[float] = pydantic.Field(default=None)
    """
    Wind-driven wave height at the given time (m)
    """

    wind_wave_peak_period: typing.Optional[float] = pydantic.Field(default=None)
    """
    Peak period of wind-driven waves (s)
    """

    wind_wave_direction: typing.Optional[int] = pydantic.Field(default=None)
    """
    Wind-wave direction (°)
    """

    wind_wave_period: typing.Optional[float] = pydantic.Field(default=None)
    """
    Wind-wave period (s)
    """

    swell_wave_height: typing.Optional[float] = pydantic.Field(default=None)
    """
    Swell wave height at the given time (m)
    """

    swell_wave_direction: typing.Optional[int] = pydantic.Field(default=None)
    """
    Swell wave direction (°)
    """

    swell_wave_period: typing.Optional[float] = pydantic.Field(default=None)
    """
    Swell wave period (s)
    """

    swell_wave_peak_period: typing.Optional[float] = pydantic.Field(default=None)
    """
    Peak period of swell waves (s)
    """

    sea_surface_temperature: typing.Optional[float] = pydantic.Field(default=None)
    """
    Sea surface temperature (°C)
    """

    sea_level_height_msl: typing.Optional[float] = pydantic.Field(default=None)
    """
    Sea level height relative to mean sea level (m)
    """

    ocean_current_velocity: typing.Optional[float] = pydantic.Field(default=None)
    """
    Speed of ocean current (km/h)
    """

    ocean_current_direction: typing.Optional[int] = pydantic.Field(default=None)
    """
    Direction of ocean current (°)
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
