# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .marine_weather_response_current import MarineWeatherResponseCurrent
from .marine_weather_response_forecast_value import MarineWeatherResponseForecastValue
from .marine_weather_response_location import MarineWeatherResponseLocation


class MarineWeatherResponse(UniversalBaseModel):
    location: typing.Optional[MarineWeatherResponseLocation] = pydantic.Field(default=None)
    """
    Location information
    """

    current: typing.Optional[MarineWeatherResponseCurrent] = pydantic.Field(default=None)
    """
    Current marine data
    """

    forecast: typing.Optional[typing.Dict[str, MarineWeatherResponseForecastValue]] = pydantic.Field(default=None)
    """
    Marine forecast data object keyed by date in YYYY-MM-DD format
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
