# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class NotFoundErrorBodyUnresolvedValue(UniversalBaseModel):
    message: typing.Optional[str] = pydantic.Field(default=None)
    """
    Detail message explaining why this symbol was not resolved.
    """

    suggestions: typing.Optional[typing.List[str]] = pydantic.Field(default=None)
    """
    Optional list of supported symbols that closely match the unresolved symbol.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
