# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .ocr_predict_response_ocr_text import OcrPredictResponseOcrText


class OcrPredictResponse(UniversalBaseModel):
    ocr_text: typing_extensions.Annotated[
        OcrPredictResponseOcrText,
        FieldMetadata(alias="OCRText"),
        pydantic.Field(
            alias="OCRText",
            description="Array containing extracted text. Structure varies based on input type and new_line parameter:\n- Single file, new_line=0: Array with single string element\n- Single file, new_line=1: Array of strings (one per line)\n- Bulk/ZIP file, new_line=0: Array of strings (one per file)\n- Bulk/ZIP file, new_line=1: Array of arrays (each inner array contains lines for respective file)",
        ),
    ]

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
