# This file was auto-generated by Fern from our API Definition.

import typing

PdfRestrictRequestRestrictionsItem = typing.Union[
    typing.Literal[
        "print_high",
        "print_low",
        "edit_document_assembly",
        "fill_form_fields",
        "edit_annotations",
        "modify_content",
        "copy_and_extract_content",
        "use_accessibility",
    ],
    typing.Any,
]
