# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata


class PdfCompressResponse(UniversalBaseModel):
    task_id: typing_extensions.Annotated[
        str,
        FieldMetadata(alias="taskId"),
        pydantic.Field(
            alias="taskId", description="Task id of the requested task which can be used to check the task status"
        ),
    ]
    input_ids: typing_extensions.Annotated[
        typing.Optional[typing.List[str]],
        FieldMetadata(alias="inputIds"),
        pydantic.Field(
            alias="inputIds",
            description="File Ids for the input files provided for the task. Not given with destroy param.",
        ),
    ] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
