# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata


class PdfDeleteFileResponse(UniversalBaseModel):
    file_id: typing_extensions.Annotated[
        str,
        FieldMetadata(alias="fileId"),
        pydantic.Field(alias="fileId", description="The unique identifier of the file."),
    ]
    success: bool = pydantic.Field()
    """
    Indicates whether the file deletion request was successful.
    """

    message: str = pydantic.Field()
    """
    A message indicating the result of the file deletion request.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
