# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata


class PdfGetTaskStatusResponse(UniversalBaseModel):
    task_id: typing_extensions.Annotated[
        str,
        FieldMetadata(alias="taskId"),
        pydantic.Field(alias="taskId", description="The unique identifier of the PDF processing task."),
    ]
    status: str = pydantic.Field()
    """
    The current status of the task (e.g., 'queued', 'processing', 'completed', 'failed').
    """

    created_at: typing_extensions.Annotated[
        dt.datetime,
        FieldMetadata(alias="createdAt"),
        pydantic.Field(
            alias="createdAt",
            description="The timestamp when the task status was created, formatted as 'yyyy-MM-dd HH:mm:ss'.",
        ),
    ]
    zip_output_url: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="zipOutputUrl"),
        pydantic.Field(
            alias="zipOutputUrl",
            description="The URL to download all output files as a single ZIP archive. This is present only when the task status is 'COMPLETED'.",
        ),
    ] = None
    zip_file_id: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="zipFileId"),
        pydantic.Field(
            alias="zipFileId",
            description="The unique identifier for the ZIP file. This is present only when the task status is 'COMPLETED'.",
        ),
    ] = None
    output_urls: typing_extensions.Annotated[
        typing.Optional[typing.List[str]],
        FieldMetadata(alias="outputUrls"),
        pydantic.Field(
            alias="outputUrls",
            description="A list of URLs for each individual output file. This is present only when the task is 'COMPLETED'.",
        ),
    ] = None
    output_ids: typing_extensions.Annotated[
        typing.Optional[typing.List[str]],
        FieldMetadata(alias="outputIds"),
        pydantic.Field(
            alias="outputIds",
            description="A list of unique IDs for the output files. This is present only when the task is 'COMPLETED'.",
        ),
    ] = None
    input_ids: typing_extensions.Annotated[
        typing.Optional[typing.List[str]],
        FieldMetadata(alias="inputIds"),
        pydantic.Field(
            alias="inputIds",
            description="A list of unique IDs for the input files submitted with the task. If the task was initiated with the `destroy` parameter set to `true`, `inputIds` will not be generated.",
        ),
    ] = None
    error: typing.Optional[str] = pydantic.Field(default=None)
    """
    The error code for the PDF Task. This is included only if the task fails.
    """

    message: typing.Optional[str] = pydantic.Field(default=None)
    """
    A descriptive message indicating the reason for task failure. This is included only if the task fails.
    """

    expires_at: typing_extensions.Annotated[
        typing.Optional[dt.datetime],
        FieldMetadata(alias="expiresAt"),
        pydantic.Field(
            alias="expiresAt",
            description="The timestamp when the task status will expire and be removed from the system, formatted as 'yyyy-MM-dd HH:mm:ss'.",
        ),
    ] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
