# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata


class PdfListFilesResponseFilesItem(UniversalBaseModel):
    file_id: typing_extensions.Annotated[str, FieldMetadata(alias="fileId"), pydantic.Field(alias="fileId")]
    file_name: typing_extensions.Annotated[str, FieldMetadata(alias="fileName"), pydantic.Field(alias="fileName")]
    file_type: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="fileType"), pydantic.Field(alias="fileType")
    ] = None
    file_creation_time: typing_extensions.Annotated[
        typing.Optional[dt.datetime], FieldMetadata(alias="fileCreationTime"), pydantic.Field(alias="fileCreationTime")
    ] = None
    file_deletion_time: typing_extensions.Annotated[
        typing.Optional[dt.date], FieldMetadata(alias="fileDeletionTime"), pydantic.Field(alias="fileDeletionTime")
    ] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
