# This file was auto-generated by Fern from our API Definition.

import typing

PdfConvertToPngRequestProfile = typing.Union[typing.Literal["bw", "gray", "rgb", "rgba", "4-bit", "8-bit"], typing.Any]
