# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata


class PhoneValidateResponseFormats(UniversalBaseModel):
    """
    The number represented in four standardized formats. Only returned for valid numbers.
    """

    e164: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="E164"),
        pydantic.Field(alias="E164", description="E.164 format for storage and APIs."),
    ] = None
    international: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="International"),
        pydantic.Field(alias="International", description="Human-readable international format."),
    ] = None
    national: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="National"),
        pydantic.Field(alias="National", description="Local format as dialed within the country."),
    ] = None
    rfc3966: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="RFC3966"),
        pydantic.Field(alias="RFC3966", description="URI format for tel: links."),
    ] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
