# This file was auto-generated by Fern from our API Definition.

import typing

PhoneValidateResponseLineType = typing.Union[
    typing.Literal[
        "MOBILE",
        "FIXED_LINE",
        "FIXED_LINE_OR_MOBILE",
        "VOIP",
        "TOLL_FREE",
        "PREMIUM_RATE",
        "SHARED_COST",
        "PERSONAL_NUMBER",
        "PAGER",
        "UAN",
        "VOICEMAIL",
        "UNKNOWN",
    ],
    typing.Any,
]
