# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class PhoneValidateResponseRawInput(UniversalBaseModel):
    """
    The original request data provided by the client.
    """

    number: typing.Optional[str] = pydantic.Field(default=None)
    """
    The phone number as entered by the user.
    """

    region: typing.Optional[str] = pydantic.Field(default=None)
    """
    ISO-2 country code if provided in the request.
    """

    dialer_region: typing.Optional[str] = pydantic.Field(default=None)
    """
    ISO-2 dialing origin country code if provided.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
