# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .readability_score_response_sentence_readability_item_readability_level import (
    ReadabilityScoreResponseSentenceReadabilityItemReadabilityLevel,
)


class ReadabilityScoreResponseSentenceReadabilityItem(UniversalBaseModel):
    sentence: typing.Optional[str] = pydantic.Field(default=None)
    """
    The sentence text
    """

    readability_grade: typing.Optional[float] = pydantic.Field(default=None)
    """
    Readability grade for the sentence
    """

    readability_level: typing.Optional[ReadabilityScoreResponseSentenceReadabilityItemReadabilityLevel] = (
        pydantic.Field(default=None)
    )
    """
    Difficulty level for the sentence based on the target audience
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
