# This file was auto-generated by Fern from our API Definition.

import typing

ReadabilityScoreRequestTarget = typing.Union[
    typing.Literal["general", "professional", "academic", "technical"], typing.Any
]
