# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .readability_score_response_readability_scores_automated_readability_index import (
    ReadabilityScoreResponseReadabilityScoresAutomatedReadabilityIndex,
)
from .readability_score_response_readability_scores_coleman_liau_index import (
    ReadabilityScoreResponseReadabilityScoresColemanLiauIndex,
)
from .readability_score_response_readability_scores_flesch_kincaid_grade import (
    ReadabilityScoreResponseReadabilityScoresFleschKincaidGrade,
)
from .readability_score_response_readability_scores_flesch_reading_ease import (
    ReadabilityScoreResponseReadabilityScoresFleschReadingEase,
)
from .readability_score_response_readability_scores_gunning_fog import (
    ReadabilityScoreResponseReadabilityScoresGunningFog,
)
from .readability_score_response_readability_scores_smog_index import ReadabilityScoreResponseReadabilityScoresSmogIndex


class ReadabilityScoreResponseReadabilityScores(UniversalBaseModel):
    """
    Standard readability formula scores, keyed by metric name. Metrics that cannot be computed for the supplied text are omitted.
    """

    flesch_reading_ease: typing.Optional[ReadabilityScoreResponseReadabilityScoresFleschReadingEase] = pydantic.Field(
        default=None
    )
    """
    Flesch Reading Ease
    """

    flesch_kincaid_grade: typing.Optional[ReadabilityScoreResponseReadabilityScoresFleschKincaidGrade] = pydantic.Field(
        default=None
    )
    """
    Flesch-Kincaid Grade Level
    """

    gunning_fog: typing.Optional[ReadabilityScoreResponseReadabilityScoresGunningFog] = pydantic.Field(default=None)
    """
    Gunning Fog Index
    """

    smog_index: typing.Optional[ReadabilityScoreResponseReadabilityScoresSmogIndex] = pydantic.Field(default=None)
    """
    SMOG Index
    """

    coleman_liau_index: typing.Optional[ReadabilityScoreResponseReadabilityScoresColemanLiauIndex] = pydantic.Field(
        default=None
    )
    """
    Coleman-Liau Index
    """

    automated_readability_index: typing.Optional[ReadabilityScoreResponseReadabilityScoresAutomatedReadabilityIndex] = (
        pydantic.Field(default=None)
    )
    """
    Automated Readability Index (ARI)
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
