# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .readability_score_response_readability_scores import ReadabilityScoreResponseReadabilityScores
from .readability_score_response_sentence_readability_item import ReadabilityScoreResponseSentenceReadabilityItem


class ReadabilityScoreResponse(UniversalBaseModel):
    readability_scores: typing.Optional[ReadabilityScoreResponseReadabilityScores] = pydantic.Field(default=None)
    """
    Standard readability formula scores, keyed by metric name. Metrics that cannot be computed for the supplied text are omitted.
    """

    sentence_readability: typing.Optional[typing.List[ReadabilityScoreResponseSentenceReadabilityItem]] = (
        pydantic.Field(default=None)
    )
    """
    Per-sentence readability breakdown
    """

    readability_grade: typing.Optional[float] = pydantic.Field(default=None)
    """
    Overall readability grade, calculated as the average of sentence readability scores
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
