# This file was auto-generated by Fern from our API Definition.

import typing

ScreenshotCaptureRequestFileType = typing.Union[
    typing.Literal["PNG", "JPEG", "WEBP", "PDF", "mp4", "gif", "webm"], typing.Any
]
