# This file was auto-generated by Fern from our API Definition.

import typing

ScreenshotCaptureRequestWaitForEvent = typing.Union[
    typing.Literal["load", "domcontentloaded", "networkidle"], typing.Any
]
