# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .subdomains_lookup_response_subdomains_item import SubdomainsLookupResponseSubdomainsItem


class SubdomainsLookupResponse(UniversalBaseModel):
    domain: str
    status: bool
    query_time: str
    current_page: int
    total_pages: int
    total_records: int
    subdomains: typing.List[SubdomainsLookupResponseSubdomainsItem]

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
