# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata


class SwiftCodeLookupResponse(UniversalBaseModel):
    swift_code: typing_extensions.Annotated[str, FieldMetadata(alias="swiftCode"), pydantic.Field(alias="swiftCode")]
    country_code: typing_extensions.Annotated[
        str, FieldMetadata(alias="countryCode"), pydantic.Field(alias="countryCode")
    ]
    bank_address: typing_extensions.Annotated[
        str, FieldMetadata(alias="bankAddress"), pydantic.Field(alias="bankAddress")
    ]
    bank_code: typing_extensions.Annotated[str, FieldMetadata(alias="bankCode"), pydantic.Field(alias="bankCode")]
    bank_name: typing_extensions.Annotated[str, FieldMetadata(alias="bankName"), pydantic.Field(alias="bankName")]
    city: str
    country: str

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
