# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class TimezoneConvertResponse(UniversalBaseModel):
    original_time: dt.datetime = pydantic.Field()
    """
    Original time before conversion
    """

    converted_time: dt.datetime = pydantic.Field()
    """
    Time after conversion
    """

    diff_hour: float = pydantic.Field()
    """
    Difference in hours
    """

    diff_min: float = pydantic.Field()
    """
    Difference in minutes
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
