# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class TimezoneLookupV2ResponseTimeZoneDstEnd(UniversalBaseModel):
    """
    DST transition details (used for both the DST start and DST end transitions). Always present as a key on the parent TimeZone object; returned as an empty object {} when dst_exists is false, so none of its properties are required.
    """

    utc_time: typing.Optional[str] = pydantic.Field(default=None)
    """
    DST transition moment in UTC.
    """

    duration: typing.Optional[str] = pydantic.Field(default=None)
    """
    Clock change at the DST transition, in hours.
    """

    gap: typing.Optional[bool] = pydantic.Field(default=None)
    """
    true if local time jumps forward (some times do not exist).
    """

    date_time_after: typing.Optional[str] = pydantic.Field(default=None)
    """
    Local date/time immediately after the DST transition.
    """

    date_time_before: typing.Optional[str] = pydantic.Field(default=None)
    """
    Local date/time immediately before the DST transition.
    """

    overlap: typing.Optional[bool] = pydantic.Field(default=None)
    """
    true if local times repeat around the DST transition.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
