# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class TimezoneLookupV2ResponseAirportDetails(UniversalBaseModel):
    """
    Airport information, present when queried by IATA or ICAO code.
    """

    type: typing.Optional[str] = pydantic.Field(default=None)
    """
    Classification of the airport based on size and traffic.
    """

    name: typing.Optional[str] = pydantic.Field(default=None)
    """
    The full name of the airport.
    """

    latitude: typing.Optional[str] = pydantic.Field(default=None)
    """
    The latitude coordinate of the airport.
    """

    longitude: typing.Optional[str] = pydantic.Field(default=None)
    """
    The longitude coordinate of the airport.
    """

    elevation_ft: typing.Optional[int] = pydantic.Field(default=None)
    """
    The elevation of the airport above sea level, measured in feet.
    """

    continent_code: typing.Optional[str] = pydantic.Field(default=None)
    """
    The two-letter code of the continent.
    """

    country_code: typing.Optional[str] = pydantic.Field(default=None)
    """
    The ISO 3166-1 alpha-2 code for the country where the airport is located.
    """

    state_code: typing.Optional[str] = pydantic.Field(default=None)
    """
    Code of the state/province/region where the airport is located.
    """

    city: typing.Optional[str] = pydantic.Field(default=None)
    """
    The city or administrative region that the airport serves.
    """

    iata_code: typing.Optional[str] = pydantic.Field(default=None)
    """
    The three-letter IATA airport code (e.g., LHR).
    """

    icao_code: typing.Optional[str] = pydantic.Field(default=None)
    """
    The four-letter ICAO airport code (e.g., EGLL).
    """

    faa_code: typing.Optional[str] = pydantic.Field(default=None)
    """
    The FAA location identifier, used primarily in the United States.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
