# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class TimezoneLookupV2ResponseLocation(UniversalBaseModel):
    """
    Geographic location information. Only present for location (address) and ip (or client-IP fallback) lookups; absent for tz, lat/long, iata_code/icao_code, and lo_code lookups. Field set varies by mode: location returns location_string plus a basic field set (country_name, state_prov, city, locality, latitude, longitude); ip/default returns a richer geo-IP field set (continent_code, continent_name, country_code2, country_code3, country_name_official, is_eu, state_code, district, zipcode) plus the common fields, but never location_string or locality.
    """

    location_string: typing.Optional[str] = pydantic.Field(default=None)
    """
    The provided location parameter as location. Present only for location (address) lookups; absent for ip lookups.
    """

    continent_code: typing.Optional[str] = pydantic.Field(default=None)
    """
    The two-letter code of the continent (e.g., NA). Geo-IP field only: present for ip param or default client-IP lookups; absent for location lookups.
    """

    continent_name: typing.Optional[str] = pydantic.Field(default=None)
    """
    The full name of the continent (e.g., North America). Geo-IP field only: present for ip param or default client-IP lookups; absent for location lookups.
    """

    country_code2: typing.Optional[str] = pydantic.Field(default=None)
    """
    The ISO 3166-1 alpha-2 two-letter country code (e.g., US). Geo-IP field only: present for ip param or default client-IP lookups; absent for location lookups.
    """

    country_code3: typing.Optional[str] = pydantic.Field(default=None)
    """
    The ISO 3166-1 alpha-3 three-letter country code (e.g., USA). Geo-IP field only: present for ip param or default client-IP lookups; absent for location lookups.
    """

    country_name: typing.Optional[str] = pydantic.Field(default=None)
    """
    The common name of the country (e.g., United States). Present for both location and ip lookups.
    """

    country_name_official: typing.Optional[str] = pydantic.Field(default=None)
    """
    The official full name of the country (e.g., United States of America). Geo-IP field only: present for ip param or default client-IP lookups; absent for location lookups.
    """

    is_eu: typing.Optional[bool] = pydantic.Field(default=None)
    """
    Whether the country belongs to the European Union. Geo-IP field only: present for ip param or default client-IP lookups; absent for location lookups.
    """

    state_prov: typing.Optional[str] = pydantic.Field(default=None)
    """
    Name of the state/province/region. Present for both location and ip lookups.
    """

    state_code: typing.Optional[str] = pydantic.Field(default=None)
    """
    Code of the state/province/region. Geo-IP field only: present for ip param or default client-IP lookups; absent for location lookups.
    """

    district: typing.Optional[str] = pydantic.Field(default=None)
    """
    Name of the district or county. Geo-IP field only: present for ip param or default client-IP lookups; absent for location lookups.
    """

    city: typing.Optional[str] = pydantic.Field(default=None)
    """
    Name of the city. Present for both location and ip lookups.
    """

    locality: typing.Optional[str] = pydantic.Field(default=None)
    """
    Smaller area, part or region of a city. Only present for location (address) lookups (may be an empty string); absent for ip lookups.
    """

    zipcode: typing.Optional[str] = pydantic.Field(default=None)
    """
    ZIP/Postal code of the place. Geo-IP field only: present for ip param or default client-IP lookups; absent for location lookups.
    """

    latitude: typing.Optional[str] = pydantic.Field(default=None)
    """
    The geographic latitude of the location. Present for both location and ip lookups.
    """

    longitude: typing.Optional[str] = pydantic.Field(default=None)
    """
    The geographic longitude of the location. Present for both location and ip lookups.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
