# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class TimezoneLookupResponseAirportDetails(UniversalBaseModel):
    type: typing.Optional[str] = None
    name: typing.Optional[str] = None
    longitude: typing.Optional[float] = None
    latitude: typing.Optional[float] = None
    elevation_ft: typing.Optional[float] = None
    continent_code: typing.Optional[str] = None
    country_code: typing.Optional[str] = None
    state_code: typing.Optional[str] = None
    city: typing.Optional[str] = None
    iata_code: typing.Optional[str] = None
    icao_code: typing.Optional[str] = None
    faa_code: typing.Optional[str] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
