# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .timezone_lookup_v2_response_airport_details import TimezoneLookupV2ResponseAirportDetails
from .timezone_lookup_v2_response_lo_code_details import TimezoneLookupV2ResponseLoCodeDetails
from .timezone_lookup_v2_response_location import TimezoneLookupV2ResponseLocation
from .timezone_lookup_v2_response_time_zone import TimezoneLookupV2ResponseTimeZone


class TimezoneLookupV2Response(UniversalBaseModel):
    """
    Timezone lookup result. time_zone is always present. Exactly which other object accompanies it depends on the lookup mode: tz name and lat/long coordinates return time_zone only (no location, no ip); location address returns a basic location object; ip param or client-IP fallback returns a rich location object plus top-level ip; iata_code/icao_code returns airport_details instead of location; lo_code returns lo_code_details instead of location.
    """

    ip: typing.Optional[str] = pydantic.Field(default=None)
    """
    The IP address used for the timezone lookup. Present when queried using the ip parameter, or with no location-identifying parameter at all (client-IP fallback). Absent for every other lookup mode.
    """

    time_zone: TimezoneLookupV2ResponseTimeZone = pydantic.Field()
    """
    Timezone and date/time information for the location.
    """

    location: typing.Optional[TimezoneLookupV2ResponseLocation] = pydantic.Field(default=None)
    """
    Geographic location information. Only present for location (address) and ip (or client-IP fallback) lookups; absent for tz, lat/long, iata_code/icao_code, and lo_code lookups. Field set varies by mode: location returns location_string plus a basic field set (country_name, state_prov, city, locality, latitude, longitude); ip/default returns a richer geo-IP field set (continent_code, continent_name, country_code2, country_code3, country_name_official, is_eu, state_code, district, zipcode) plus the common fields, but never location_string or locality.
    """

    airport_details: typing.Optional[TimezoneLookupV2ResponseAirportDetails] = pydantic.Field(default=None)
    """
    Airport information, present when queried by IATA or ICAO code.
    """

    lo_code_details: typing.Optional[TimezoneLookupV2ResponseLoCodeDetails] = pydantic.Field(default=None)
    """
    UN/LOCODE location details, present when queried by LO code.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
