# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class TimezoneLookupV2ResponseLoCodeDetails(UniversalBaseModel):
    """
    UN/LOCODE location details, present when queried by LO code.
    """

    lo_code: typing.Optional[str] = pydantic.Field(default=None)
    """
    A unique identifier for the location, often used in logistics and shipping (e.g., USNYC).
    """

    city: typing.Optional[str] = pydantic.Field(default=None)
    """
    The name of the city or location associated with the LO code.
    """

    state_code: typing.Optional[str] = pydantic.Field(default=None)
    """
    The code for the state, province or region.
    """

    country_code: typing.Optional[str] = pydantic.Field(default=None)
    """
    The ISO 3166-1 alpha-2 country code (e.g., US).
    """

    country_name: typing.Optional[str] = pydantic.Field(default=None)
    """
    The name of the country in an administrative context.
    """

    location_type: typing.Optional[str] = pydantic.Field(default=None)
    """
    The type of location as comma-separated list of facilities (e.g., Port, Rail Terminal, Road Terminal, Airport).
    """

    latitude: typing.Optional[str] = pydantic.Field(default=None)
    """
    The latitude coordinate of the location.
    """

    longitude: typing.Optional[str] = pydantic.Field(default=None)
    """
    The longitude coordinate of the location.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
