# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .timezone_lookup_response_airport_details import TimezoneLookupResponseAirportDetails
from .timezone_lookup_response_lo_code_details import TimezoneLookupResponseLoCodeDetails
from .timezone_lookup_response_location import TimezoneLookupResponseLocation
from .timezone_lookup_response_time_zone import TimezoneLookupResponseTimeZone


class TimezoneLookupResponse(UniversalBaseModel):
    ip: typing.Optional[str] = None
    location: typing.Optional[TimezoneLookupResponseLocation] = None
    time_zone: typing.Optional[TimezoneLookupResponseTimeZone] = None
    airport_detail: typing.Optional[TimezoneLookupResponseAirportDetails] = None
    lo_code_details: typing.Optional[TimezoneLookupResponseLoCodeDetails] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
