# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .timezone_lookup_response_time_zone_dst_end import TimezoneLookupResponseTimeZoneDstEnd
from .timezone_lookup_response_time_zone_dst_start import TimezoneLookupResponseTimeZoneDstStart


class TimezoneLookupResponseTimeZone(UniversalBaseModel):
    name: str
    offset: float
    offset_with_dst: float
    date: str
    date_time: str
    date_time_txt: str
    date_time_wti: str
    date_time_ymd: str
    date_time_unix: float
    time24: typing_extensions.Annotated[str, FieldMetadata(alias="time_24"), pydantic.Field(alias="time_24")]
    time12: typing_extensions.Annotated[str, FieldMetadata(alias="time_12"), pydantic.Field(alias="time_12")]
    week: int
    month: int
    year: int
    year_abbr: str
    is_dst: bool
    dst_savings: float
    dst_exists: bool
    dst_start: TimezoneLookupResponseTimeZoneDstStart
    dst_end: TimezoneLookupResponseTimeZoneDstEnd

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
