# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .timezone_lookup_v2_response_time_zone_dst_end import TimezoneLookupV2ResponseTimeZoneDstEnd
from .timezone_lookup_v2_response_time_zone_dst_start import TimezoneLookupV2ResponseTimeZoneDstStart


class TimezoneLookupV2ResponseTimeZone(UniversalBaseModel):
    """
    Timezone and date/time information for the location.
    """

    name: str = pydantic.Field()
    """
    The IANA timezone name/identifier for the location.
    """

    offset: float = pydantic.Field()
    """
    The Standard time zone offset from UTC in hours.
    """

    offset_with_dst: float = pydantic.Field()
    """
    The time zone offset from UTC in hours, accounting for DST.
    """

    current_time: str = pydantic.Field()
    """
    The current date and time with timezone offset in YYYY-MM-DD HH:mm:ss.SSS±ZZZZ format.
    """

    current_time_unix: float = pydantic.Field()
    """
    The Unix timestamp representing the date and time in seconds.
    """

    date: str = pydantic.Field()
    """
    The current date in YYYY-MM-DD format.
    """

    date_time: str = pydantic.Field()
    """
    The current date and time in YYYY-MM-DD HH:mm:ss format.
    """

    date_time_txt: str = pydantic.Field()
    """
    The current date and time in descriptive format EEEE, MMMM dd, yyyy HH:mm:ss.
    """

    date_time_wti: str = pydantic.Field()
    """
    The date and time with time zone information in EEE, dd MMM yyyy HH:mm:ss Z format.
    """

    date_time_ymd: str = pydantic.Field()
    """
    The date and time with timezone offset in ISO 8601 format YYYY-MM-DDTHH:mm:ss±HHMM.
    """

    time24: typing_extensions.Annotated[
        str,
        FieldMetadata(alias="time_24"),
        pydantic.Field(alias="time_24", description="The current time in 24-hour format HH:mm:ss."),
    ]
    """
    The current time in 24-hour format HH:mm:ss.
    """

    time12: typing_extensions.Annotated[
        str,
        FieldMetadata(alias="time_12"),
        pydantic.Field(alias="time_12", description="The current time in 12-hour format with AM/PM notation."),
    ]
    """
    The current time in 12-hour format with AM/PM notation.
    """

    week: int = pydantic.Field()
    """
    The week number of the year (1-52).
    """

    month: int = pydantic.Field()
    """
    The current month as a number (1-12).
    """

    year: int = pydantic.Field()
    """
    The four-digit current year.
    """

    year_abbr: str = pydantic.Field()
    """
    The two-digit abbreviation for the year.
    """

    current_tz_abbreviation: str = pydantic.Field()
    """
    Abbreviation of the time zone currently in effect (standard or DST).
    """

    current_tz_full_name: str = pydantic.Field()
    """
    Full name of the time zone currently in effect.
    """

    standard_tz_abbreviation: str = pydantic.Field()
    """
    Abbreviation of the standard (non-DST) time zone.
    """

    standard_tz_full_name: str = pydantic.Field()
    """
    Full name of the standard (non-DST) time zone.
    """

    is_dst: bool = pydantic.Field()
    """
    Is the time zone in daylight savings?
    """

    dst_tz_abbreviation: typing.Optional[str] = pydantic.Field(default=None)
    """
    Abbreviation of the DST time zone. Always present as a key; holds an empty string when dst_exists is false.
    """

    dst_tz_full_name: typing.Optional[str] = pydantic.Field(default=None)
    """
    Full name of the DST time zone. Always present as a key; holds an empty string when dst_exists is false.
    """

    dst_savings: float = pydantic.Field()
    """
    The amount of time added for daylight saving in hours.
    """

    dst_exists: bool = pydantic.Field()
    """
    Indicates whether DST is observed in the region.
    """

    dst_start: typing.Optional[TimezoneLookupV2ResponseTimeZoneDstStart] = pydantic.Field(default=None)
    """
    DST transition details (used for both the DST start and DST end transitions). Always present as a key on the parent TimeZone object; returned as an empty object {} when dst_exists is false, so none of its properties are required.
    """

    dst_end: typing.Optional[TimezoneLookupV2ResponseTimeZoneDstEnd] = pydantic.Field(default=None)
    """
    DST transition details (used for both the DST start and DST end transitions). Always present as a key on the parent TimeZone object; returned as an empty object {} when dst_exists is false, so none of its properties are required.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
