# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class TimezoneLookupV2ResponseLocation(UniversalBaseModel):
    location_string: typing.Optional[str] = None
    continent_code: typing.Optional[str] = None
    continent_name: typing.Optional[str] = None
    country_code2: typing.Optional[str] = None
    country_code3: typing.Optional[str] = None
    country_name: typing.Optional[str] = None
    country_name_official: typing.Optional[str] = None
    is_eu: typing.Optional[bool] = None
    state_prov: typing.Optional[str] = None
    state_code: typing.Optional[str] = None
    district: typing.Optional[str] = None
    city: typing.Optional[str] = None
    locality: typing.Optional[str] = None
    zipcode: typing.Optional[str] = None
    latitude: typing.Optional[str] = None
    longitude: typing.Optional[str] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class TimezoneLookupV2ResponseAirportDetails(UniversalBaseModel):
    type: typing.Optional[str] = None
    name: typing.Optional[str] = None
    latitude: typing.Optional[float] = None
    longitude: typing.Optional[float] = None
    elevation_ft: typing.Optional[float] = None
    continent_code: typing.Optional[str] = None
    country_code: typing.Optional[str] = None
    state_code: typing.Optional[str] = None
    city: typing.Optional[str] = None
    iata_code: typing.Optional[str] = None
    icao_code: typing.Optional[str] = None
    faa_code: typing.Optional[str] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class TimezoneLookupV2ResponseLoCodeDetails(UniversalBaseModel):
    lo_code: typing.Optional[str] = None
    city: typing.Optional[str] = None
    state_code: typing.Optional[str] = None
    country_code: typing.Optional[str] = None
    country_name: typing.Optional[str] = None
    location_type: typing.Optional[str] = None
    latitude: typing.Optional[float] = None
    longitude: typing.Optional[float] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class TimezoneLookupV2ResponseTimeZoneDstStart(UniversalBaseModel):
    utc_time: typing.Optional[str] = None
    duration: typing.Optional[str] = None
    gap: typing.Optional[bool] = None
    date_time_after: typing.Optional[str] = None
    date_time_before: typing.Optional[str] = None
    overlap: typing.Optional[bool] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class TimezoneLookupV2ResponseTimeZoneDstEnd(UniversalBaseModel):
    utc_time: typing.Optional[str] = None
    duration: typing.Optional[str] = None
    gap: typing.Optional[bool] = None
    date_time_after: typing.Optional[str] = None
    date_time_before: typing.Optional[str] = None
    overlap: typing.Optional[bool] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class TimezoneLookupV2ResponseTimeZone(UniversalBaseModel):
    name: typing.Optional[str] = None
    offset: typing.Optional[float] = None
    offset_with_dst: typing.Optional[float] = None
    current_time: typing.Optional[str] = None
    current_time_unix: typing.Optional[float] = None
    date: typing.Optional[str] = None
    date_time: typing.Optional[str] = None
    date_time_txt: typing.Optional[str] = None
    date_time_wti: typing.Optional[str] = None
    date_time_ymd: typing.Optional[str] = None
    time_24: typing.Optional[str] = None
    time_12: typing.Optional[str] = None
    week: typing.Optional[int] = None
    month: typing.Optional[int] = None
    year: typing.Optional[int] = None
    year_abbr: typing.Optional[str] = None
    current_tz_abbreviation: typing.Optional[str] = None
    current_tz_full_name: typing.Optional[str] = None
    standard_tz_abbreviation: typing.Optional[str] = None
    standard_tz_full_name: typing.Optional[str] = None
    is_dst: typing.Optional[bool] = None
    dst_savings: typing.Optional[float] = None
    dst_exists: typing.Optional[bool] = None
    dst_tz_abbreviation: typing.Optional[str] = None
    dst_tz_full_name: typing.Optional[str] = None
    dst_start: typing.Optional[TimezoneLookupV2ResponseTimeZoneDstStart] = None
    dst_end: typing.Optional[TimezoneLookupV2ResponseTimeZoneDstEnd] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class TimezoneLookupV2Response(UniversalBaseModel):
    ip: typing.Optional[str] = None
    location: typing.Optional[TimezoneLookupV2ResponseLocation] = None
    airport_details: typing.Optional[TimezoneLookupV2ResponseAirportDetails] = None
    lo_code_details: typing.Optional[TimezoneLookupV2ResponseLoCodeDetails] = None
    time_zone: typing.Optional[TimezoneLookupV2ResponseTimeZone] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
