# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .user_agent_lookup_response_device import UserAgentLookupResponseDevice
from .user_agent_lookup_response_engine import UserAgentLookupResponseEngine
from .user_agent_lookup_response_operating_system import UserAgentLookupResponseOperatingSystem


class UserAgentLookupResponse(UniversalBaseModel):
    user_agent_string: str = pydantic.Field()
    """
    User-agent string that is parsed for browser, device and operating system details.
    """

    name: str = pydantic.Field()
    """
    Agent name or the actual browser name that was used.
    """

    type: str = pydantic.Field()
    """
    Agent type or the browser type that was used. Possible values:
    1. Browser
    2. Browser Webview
    3. Mobile App
    4. Robot Mobile
    5. Cloud Application
    6. Email Client
    7. Voice
    8. Special
    9. Testclient
    10. Hacker
    11. Unknown
    """

    version: str = pydantic.Field()
    """
    Agent version or the browser version
    """

    version_major: str = pydantic.Field()
    """
    Agent version major or the browser version major
    """

    device: UserAgentLookupResponseDevice
    engine: UserAgentLookupResponseEngine
    operating_system: UserAgentLookupResponseOperatingSystem

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
