# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .vat_supported_countries_response_vat_supported_countries_and_states_item import (
    VatSupportedCountriesResponseVatSupportedCountriesAndStatesItem,
)


class VatSupportedCountriesResponse(UniversalBaseModel):
    vat_supported_countries_and_states: typing_extensions.Annotated[
        typing.Optional[typing.List[VatSupportedCountriesResponseVatSupportedCountriesAndStatesItem]],
        FieldMetadata(alias="VAT_Supported_Countries_And_States"),
        pydantic.Field(alias="VAT_Supported_Countries_And_States"),
    ] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
