# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .vat_validate_response_company import VatValidateResponseCompany
from .vat_validate_response_validation import VatValidateResponseValidation


class VatValidateResponse(UniversalBaseModel):
    country_code: str
    vat_number: str
    requester_country_code: str
    requester_vat_number: str
    requested_at: dt.datetime
    validation: VatValidateResponseValidation
    company: VatValidateResponseCompany

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
