# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .weak_words_detect_response_weak_words_item import WeakWordsDetectResponseWeakWordsItem


class WeakWordsDetectResponse(UniversalBaseModel):
    weak_words: typing.List[WeakWordsDetectResponseWeakWordsItem] = pydantic.Field()
    """
    List of detected weak words
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
