# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata


class WeatherForecastResponseForecastValueMinutelyItem(UniversalBaseModel):
    timestamp: typing.Optional[dt.datetime] = pydantic.Field(default=None)
    """
    ISO 8601 formatted timestamp
    """

    temperature2m: typing_extensions.Annotated[
        typing.Optional[float],
        FieldMetadata(alias="temperature_2m"),
        pydantic.Field(alias="temperature_2m", description="Air temperature at 2m (°C)"),
    ] = None
    relative_humidity2m: typing_extensions.Annotated[
        typing.Optional[int],
        FieldMetadata(alias="relative_humidity_2m"),
        pydantic.Field(alias="relative_humidity_2m", description="Relative humidity at 2m (%)"),
    ] = None
    dew_point2m: typing_extensions.Annotated[
        typing.Optional[float],
        FieldMetadata(alias="dew_point_2m"),
        pydantic.Field(alias="dew_point_2m", description="Dew point at 2m (°C)"),
    ] = None
    apparent_temperature: typing.Optional[float] = pydantic.Field(default=None)
    """
    Feels-like temperature (°C)
    """

    precipitation: typing.Optional[float] = pydantic.Field(default=None)
    """
    Precipitation at this minute (mm)
    """

    rain: typing.Optional[float] = pydantic.Field(default=None)
    """
    Rainfall (mm)
    """

    snowfall: typing.Optional[float] = pydantic.Field(default=None)
    """
    Snowfall (cm)
    """

    weather_code: typing.Optional[int] = pydantic.Field(default=None)
    """
    Weather condition code
    """

    wind_speed10m: typing_extensions.Annotated[
        typing.Optional[float],
        FieldMetadata(alias="wind_speed_10m"),
        pydantic.Field(alias="wind_speed_10m", description="Wind speed at 10m (km/h)"),
    ] = None
    wind_direction10m: typing_extensions.Annotated[
        typing.Optional[int],
        FieldMetadata(alias="wind_direction_10m"),
        pydantic.Field(alias="wind_direction_10m", description="Wind direction at 10m (°)"),
    ] = None
    wind_gusts10m: typing_extensions.Annotated[
        typing.Optional[float],
        FieldMetadata(alias="wind_gusts_10m"),
        pydantic.Field(alias="wind_gusts_10m", description="Wind gusts at 10m (km/h)"),
    ] = None
    visibility: typing.Optional[float] = pydantic.Field(default=None)
    """
    Visibility distance (m)
    """

    shortwave_radiation: typing.Optional[float] = pydantic.Field(default=None)
    """
    Shortwave radiation (W/m²)
    """

    direct_radiation: typing.Optional[float] = pydantic.Field(default=None)
    """
    Direct solar radiation (W/m²)
    """

    diffuse_radiation: typing.Optional[float] = pydantic.Field(default=None)
    """
    Diffuse solar radiation (W/m²)
    """

    direct_normal_irradiance: typing.Optional[float] = pydantic.Field(default=None)
    """
    Direct normal irradiance (W/m²)
    """

    global_tilted_irradiance: typing.Optional[float] = pydantic.Field(default=None)
    """
    Global tilted irradiance (W/m²)
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
