# This file was auto-generated by Fern from our API Definition.

import typing

from .weather_time_series_response_location_city import WeatherTimeSeriesResponseLocationCity
from .weather_time_series_response_location_continent_code import WeatherTimeSeriesResponseLocationContinentCode
from .weather_time_series_response_location_zero import WeatherTimeSeriesResponseLocationZero

WeatherTimeSeriesResponseLocation = typing.Union[
    WeatherTimeSeriesResponseLocationZero,
    WeatherTimeSeriesResponseLocationContinentCode,
    WeatherTimeSeriesResponseLocationCity,
]
