# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .weather_forecast_response_forecast_value_astronomy import WeatherForecastResponseForecastValueAstronomy
from .weather_forecast_response_forecast_value_daily import WeatherForecastResponseForecastValueDaily
from .weather_forecast_response_forecast_value_hourly_item import WeatherForecastResponseForecastValueHourlyItem
from .weather_forecast_response_forecast_value_minutely_item import WeatherForecastResponseForecastValueMinutelyItem


class WeatherForecastResponseForecastValue(UniversalBaseModel):
    daily: typing.Optional[WeatherForecastResponseForecastValueDaily] = pydantic.Field(default=None)
    """
    Daily forecast data
    """

    hourly: typing.Optional[typing.List[WeatherForecastResponseForecastValueHourlyItem]] = pydantic.Field(default=None)
    """
    Hourly forecast data
    """

    minutely: typing.Optional[typing.List[WeatherForecastResponseForecastValueMinutelyItem]] = pydantic.Field(
        default=None
    )
    """
    Minutely forecast data
    """

    astronomy: typing.Optional[WeatherForecastResponseForecastValueAstronomy] = pydantic.Field(default=None)
    """
    Astronomy data
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
