# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata


class WeatherForecastResponseForecastValueDaily(UniversalBaseModel):
    """
    Daily forecast data
    """

    timestamp: typing.Optional[dt.datetime] = pydantic.Field(default=None)
    """
    ISO 8601 formatted timestamp
    """

    weather_code: typing.Optional[int] = pydantic.Field(default=None)
    """
    Weather condition code
    """

    temperature2m_max: typing_extensions.Annotated[
        typing.Optional[float],
        FieldMetadata(alias="temperature_2m_max"),
        pydantic.Field(alias="temperature_2m_max", description="Maximum air temperature at 2m (°C)"),
    ] = None
    temperature2m_min: typing_extensions.Annotated[
        typing.Optional[float],
        FieldMetadata(alias="temperature_2m_min"),
        pydantic.Field(alias="temperature_2m_min", description="Minimum air temperature at 2m (°C)"),
    ] = None
    temperature2m_mean: typing_extensions.Annotated[
        typing.Optional[float],
        FieldMetadata(alias="temperature_2m_mean"),
        pydantic.Field(alias="temperature_2m_mean", description="Mean air temperature at 2m (°C)"),
    ] = None
    apparent_temperature_max: typing.Optional[float] = pydantic.Field(default=None)
    """
    Maximum feels-like temperature (°C)
    """

    apparent_temperature_min: typing.Optional[float] = pydantic.Field(default=None)
    """
    Minimum feels-like temperature (°C)
    """

    apparent_temperature_mean: typing.Optional[float] = pydantic.Field(default=None)
    """
    Mean feels-like temperature (°C)
    """

    uv_index_max: typing.Optional[float] = pydantic.Field(default=None)
    """
    Daily maximum UV index
    """

    uv_index_clear_sky_max: typing.Optional[float] = pydantic.Field(default=None)
    """
    UV index clear sky max
    """

    rain_sum: typing.Optional[float] = pydantic.Field(default=None)
    """
    Total rain (mm)
    """

    showers_sum: typing.Optional[float] = pydantic.Field(default=None)
    """
    Total showers (mm)
    """

    snowfall_sum: typing.Optional[float] = pydantic.Field(default=None)
    """
    Total snowfall (cm)
    """

    precipitation_sum: typing.Optional[float] = pydantic.Field(default=None)
    """
    Total precipitation (mm)
    """

    precipitation_probability_mean: typing.Optional[int] = pydantic.Field(default=None)
    """
    Mean probability of precipitation (%)
    """

    wind_speed10m_max: typing_extensions.Annotated[
        typing.Optional[float],
        FieldMetadata(alias="wind_speed_10m_max"),
        pydantic.Field(alias="wind_speed_10m_max", description="Max wind speed at 10m (km/h)"),
    ] = None
    wind_speed10m_min: typing_extensions.Annotated[
        typing.Optional[float],
        FieldMetadata(alias="wind_speed_10m_min"),
        pydantic.Field(alias="wind_speed_10m_min", description="Min wind speed at 10m (km/h)"),
    ] = None
    wind_speed10m_mean: typing_extensions.Annotated[
        typing.Optional[float],
        FieldMetadata(alias="wind_speed_10m_mean"),
        pydantic.Field(alias="wind_speed_10m_mean", description="Mean wind speed at 10m (km/h)"),
    ] = None
    wind_gusts10m_max: typing_extensions.Annotated[
        typing.Optional[float],
        FieldMetadata(alias="wind_gusts_10m_max"),
        pydantic.Field(alias="wind_gusts_10m_max", description="Max wind gusts at 10m (km/h)"),
    ] = None
    wind_gusts10m_min: typing_extensions.Annotated[
        typing.Optional[float],
        FieldMetadata(alias="wind_gusts_10m_min"),
        pydantic.Field(alias="wind_gusts_10m_min", description="Min wind gusts at 10m (km/h)"),
    ] = None
    wind_gusts10m_mean: typing_extensions.Annotated[
        typing.Optional[float],
        FieldMetadata(alias="wind_gusts_10m_mean"),
        pydantic.Field(alias="wind_gusts_10m_mean", description="Mean wind gusts at 10m (km/h)"),
    ] = None
    wind_direction10m_dominant: typing_extensions.Annotated[
        typing.Optional[int],
        FieldMetadata(alias="wind_direction_10m_dominant"),
        pydantic.Field(alias="wind_direction_10m_dominant", description="Dominant wind direction at 10m (°)"),
    ] = None
    shortwave_radiation_sum: typing.Optional[float] = pydantic.Field(default=None)
    """
    Total shortwave radiation (MJ/m²)
    """

    surface_pressure_mean: typing.Optional[float] = pydantic.Field(default=None)
    """
    Mean surface pressure (hPa)
    """

    pressure_msl_mean: typing.Optional[float] = pydantic.Field(default=None)
    """
    Mean sea-level pressure (hPa)
    """

    visibility_mean: typing.Optional[float] = pydantic.Field(default=None)
    """
    Mean visibility distance (m)
    """

    cloud_cover_mean: typing.Optional[int] = pydantic.Field(default=None)
    """
    Mean cloud cover (%)
    """

    dew_point2m_max: typing_extensions.Annotated[
        typing.Optional[float],
        FieldMetadata(alias="dew_point_2m_max"),
        pydantic.Field(alias="dew_point_2m_max", description="Max dew point at 2m (°C)"),
    ] = None
    dew_point2m_min: typing_extensions.Annotated[
        typing.Optional[float],
        FieldMetadata(alias="dew_point_2m_min"),
        pydantic.Field(alias="dew_point_2m_min", description="Min dew point at 2m (°C)"),
    ] = None
    dew_point2m_mean: typing_extensions.Annotated[
        typing.Optional[float],
        FieldMetadata(alias="dew_point_2m_mean"),
        pydantic.Field(alias="dew_point_2m_mean", description="Mean dew point at 2m (°C)"),
    ] = None
    relative_humidity2m_max: typing_extensions.Annotated[
        typing.Optional[int],
        FieldMetadata(alias="relative_humidity_2m_max"),
        pydantic.Field(alias="relative_humidity_2m_max", description="Max relative humidity (%)"),
    ] = None
    relative_humidity2m_min: typing_extensions.Annotated[
        typing.Optional[int],
        FieldMetadata(alias="relative_humidity_2m_min"),
        pydantic.Field(alias="relative_humidity_2m_min", description="Min relative humidity (%)"),
    ] = None
    relative_humidity2m_mean: typing_extensions.Annotated[
        typing.Optional[int],
        FieldMetadata(alias="relative_humidity_2m_mean"),
        pydantic.Field(alias="relative_humidity_2m_mean", description="Mean relative humidity (%)"),
    ] = None
    et0fao_evapotranspiration_sum: typing_extensions.Annotated[
        typing.Optional[float],
        FieldMetadata(alias="et0_fao_evapotranspiration_sum"),
        pydantic.Field(alias="et0_fao_evapotranspiration_sum", description="ET₀ Reference Evapotranspiration (mm)"),
    ] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
