# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .weather_forecast_response_forecast_value import WeatherForecastResponseForecastValue
from .weather_forecast_response_location import WeatherForecastResponseLocation


class WeatherForecastResponse(UniversalBaseModel):
    location: typing.Optional[WeatherForecastResponseLocation] = pydantic.Field(default=None)
    """
    Location information
    """

    forecast: typing.Optional[typing.Dict[str, WeatherForecastResponseForecastValue]] = pydantic.Field(default=None)
    """
    Forecast data object of the provided date range
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
