# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .web_scrape_request_body_block_url_cookies_item import WebScrapeRequestBodyBlockUrlCookiesItem
from .web_scrape_request_body_block_url_instructions_item import WebScrapeRequestBodyBlockUrlInstructionsItem


class WebScrapeRequestBodyBlockUrl(UniversalBaseModel):
    block_url: typing_extensions.Annotated[
        typing.Optional[typing.List[str]],
        FieldMetadata(alias="blockUrl"),
        pydantic.Field(
            alias="blockUrl", description="List of script or URL patterns to block during network requests."
        ),
    ] = None
    cookies: typing.Optional[typing.List[WebScrapeRequestBodyBlockUrlCookiesItem]] = pydantic.Field(default=None)
    """
    List of cookies to be set in the browser session.
    """

    instructions: typing.List[WebScrapeRequestBodyBlockUrlInstructionsItem] = pydantic.Field()
    """
    An ordered list of step-by-step scraping instructions to be executed in the browser.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
