# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata


class WebScrapeRequestBodyBlockUrlInstructionsItemBlockElement(UniversalBaseModel):
    block_element: typing_extensions.Annotated[
        typing.Optional[typing.List[str]],
        FieldMetadata(alias="blockElement"),
        pydantic.Field(
            alias="blockElement",
            description="List of CSS selectors or XPaths for elements to block or hide on the page.",
        ),
    ] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
