# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .web_scrape_request_body_block_url_instructions_item_general_image_captcha_general_image_captcha_item_model import (
    WebScrapeRequestBodyBlockUrlInstructionsItemGeneralImageCaptchaGeneralImageCaptchaItemModel,
)


class WebScrapeRequestBodyBlockUrlInstructionsItemGeneralImageCaptchaGeneralImageCaptchaItem(UniversalBaseModel):
    image_path: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="imagePath"), pydantic.Field(alias="imagePath")
    ] = None
    text_field: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="textField"), pydantic.Field(alias="textField")
    ] = None
    image_update_path: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="imageUpdatePath"), pydantic.Field(alias="imageUpdatePath")
    ] = None
    captcha_failed_path: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="captchaFailedPath"), pydantic.Field(alias="captchaFailedPath")
    ] = None
    model: typing.Optional[
        WebScrapeRequestBodyBlockUrlInstructionsItemGeneralImageCaptchaGeneralImageCaptchaItemModel
    ] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
