# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class WebScrapeRequestBodyBlockUrlInstructionsItemExtractExtract(UniversalBaseModel):
    """
    Defines what data to extract and how to extract it.
    """

    html: typing.Optional[str] = pydantic.Field(default=None)
    """
    CSS selector or XPath to extract HTML content. Example: "/html/body"
    """

    text: typing.Optional[str] = pydantic.Field(default=None)
    """
    CSS selector or XPath to extract text content. Example: "/html/body/div/div[2]/text"
    """

    user_data: typing.Optional[str] = pydantic.Field(default=None)
    """
    CSS selector or XPath to extract user data. Example: "/html/body/div/div[2]"
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
