# This file was auto-generated by Fern from our API Definition.

import typing

WebScrapeRequestBodyBlockUrlInstructionsItemGeneralImageCaptchaGeneralImageCaptchaItemModel = typing.Union[
    typing.Literal["mini-ocr-v1", "Model20", "Model05", "Model141", "Model150", "Model102"], typing.Any
]
