# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata


class WebScrapeResponse(UniversalBaseModel):
    extracted_data: typing_extensions.Annotated[
        typing.Dict[str, typing.Any],
        FieldMetadata(alias="extractedData"),
        pydantic.Field(alias="extractedData", description="Extracted data based on the extract instructions"),
    ]

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
