# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .web_scrape_request_body_block_url_instructions_item_screenshot_screenshot import (
    WebScrapeRequestBodyBlockUrlInstructionsItemScreenshotScreenshot,
)


class WebScrapeRequestBodyBlockUrlInstructionsItemScreenshot(UniversalBaseModel):
    screenshot: typing.Optional[WebScrapeRequestBodyBlockUrlInstructionsItemScreenshotScreenshot] = pydantic.Field(
        default=None
    )
    """
    Captures screenshot of the page.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
