# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .web_scrape_request_body_one_instructions_item_get_form_get_form import (
    WebScrapeRequestBodyOneInstructionsItemGetFormGetForm,
)


class WebScrapeRequestBodyOneInstructionsItemGetForm(UniversalBaseModel):
    get_form: typing_extensions.Annotated[
        typing.Optional[WebScrapeRequestBodyOneInstructionsItemGetFormGetForm],
        FieldMetadata(alias="getForm"),
        pydantic.Field(
            alias="getForm",
            description="Submits a form using GET method. Provide the form's XPath/CSS selector and input values.",
        ),
    ] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
