# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .web_scrape_request_body_block_url_instructions_item_general_image_captcha_general_image_captcha_item import (
    WebScrapeRequestBodyBlockUrlInstructionsItemGeneralImageCaptchaGeneralImageCaptchaItem,
)


class WebScrapeRequestBodyBlockUrlInstructionsItemGeneralImageCaptcha(UniversalBaseModel):
    general_image_captcha: typing_extensions.Annotated[
        typing.Optional[
            typing.List[WebScrapeRequestBodyBlockUrlInstructionsItemGeneralImageCaptchaGeneralImageCaptchaItem]
        ],
        FieldMetadata(alias="generalImageCaptcha"),
        pydantic.Field(alias="generalImageCaptcha", description="Instructions for solving image captchas."),
    ] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
