# This file was auto-generated by Fern from our API Definition.

import typing

from .web_scrape_request_body_block_url import WebScrapeRequestBodyBlockUrl
from .web_scrape_request_body_one import WebScrapeRequestBodyOne

WebScrapeRequestBody = typing.Union[WebScrapeRequestBodyBlockUrl, WebScrapeRequestBodyOne]
