# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .web_scrape_request_body_one_instructions_item_post_form_post_form_data import (
    WebScrapeRequestBodyOneInstructionsItemPostFormPostFormData,
)


class WebScrapeRequestBodyOneInstructionsItemPostFormPostForm(UniversalBaseModel):
    """
    Submits a form using POST method. Provide the form's XPath/CSS selector and input values.
    """

    selector: typing.Optional[str] = None
    data: typing.Optional[WebScrapeRequestBodyOneInstructionsItemPostFormPostFormData] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
