# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .web_scrape_request_body_one_instructions_item_get_page_get_page import (
    WebScrapeRequestBodyOneInstructionsItemGetPageGetPage,
)


class WebScrapeRequestBodyOneInstructionsItemGetPage(UniversalBaseModel):
    get_page: typing_extensions.Annotated[
        typing.Optional[WebScrapeRequestBodyOneInstructionsItemGetPageGetPage],
        FieldMetadata(alias="getPage"),
        pydantic.Field(alias="getPage", description="Retrieves page content."),
    ] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
