# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .zipcode_distance_match_response_results_item import ZipcodeDistanceMatchResponseResultsItem


class ZipcodeDistanceMatchResponse(UniversalBaseModel):
    results_count: typing.Optional[str] = pydantic.Field(default=None)
    """
    Number of matching ZIP/postal code pairs returned
    """

    results: typing.Optional[typing.List[ZipcodeDistanceMatchResponseResultsItem]] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
