# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .zipcode_distance_response_results_item import ZipcodeDistanceResponseResultsItem


class ZipcodeDistanceResponse(UniversalBaseModel):
    result_count: typing.Optional[int] = pydantic.Field(default=None)
    """
    Number of distance results returned
    """

    results: typing.Optional[typing.List[ZipcodeDistanceResponseResultsItem]] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
