# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class ZipcodeSearchByRegionResponse(UniversalBaseModel):
    total_results: typing.Optional[int] = pydantic.Field(default=None)
    """
    Total number of ZIP/postal codes found
    """

    total_pages: typing.Optional[int] = pydantic.Field(default=None)
    """
    Total number of pages available
    """

    current_page: typing.Optional[int] = pydantic.Field(default=None)
    """
    Current page number
    """

    current_page_size: typing.Optional[int] = pydantic.Field(default=None)
    """
    Number of ZIP/postal codes in the current page
    """

    codes: typing.Optional[typing.List[str]] = pydantic.Field(default=None)
    """
    List of ZIP/postal codes
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
