# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.api_error import ApiError
from ..types.no_response_error_body import NoResponseErrorBody


class NoResponseError(ApiError):
    def __init__(self, body: NoResponseErrorBody, headers: typing.Optional[typing.Dict[str, str]] = None):
        super().__init__(status_code=444, headers=headers, body=body)
